// packages/survey-creator-angular/ui-preset-editor/src/presets.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { SurveyCreatorModel } from "survey-creator-core";

@Component({
  selector: "svc-tab-presets",
  templateUrl: "./presets.component.html",
  styles: [":host { display: none; }"]
})
export class TabPresetsComponent extends BaseAngular<any> {
  @Input() model: any = undefined;
  public get survey() {
    return this.model.model;
  }
  public get navigationBar() {
    return this.model.navigationBar;
  }
  public get creator() {
    return this.model.creator;
  }
  protected getModel() {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-tab-presets", TabPresetsComponent);

<ng-template #template>
  <div class="svc-flex-column">
    <ng-template *ngIf="creator?.showToolbox" [component]="{ name: 'svc-toolbox', data: {model: creator} }">
    </ng-template>
  </div>
  <div class="svc-tab-designer svc-tab-designer--presets">
    <sv-scroll>
      <sv-action-bar [model]="navigationBar" [handleClick]="false"></sv-action-bar>
      <ng-template [component]="{ name: 'survey', data: {model: survey} }">
      </ng-template>
    </sv-scroll>
  </div>
</ng-template>

// packages/survey-creator-vue/src/ui-preset-editor/Presets.vue
<template>
  <div class="svc-flex-column">
    <SvComponent
      :is="'svc-toolbox'"
      v-if="creator.showToolbox"
      :model="creator"
    />
  </div>
  <div class="svc-tab-designer svc-tab-designer--presets">
    <SvComponent :is="'sv-scroll'">
      <SvComponent
        :is="'sv-action-bar'"
        :model="navigationBar"
      ></SvComponent>
      <SvComponent :is="'survey'" :model="model" />
    </SvComponent>
  </div>
</template>

<script setup lang="ts">
import { SvComponent } from "survey-vue3-ui";
import { useBase } from "survey-vue3-ui";
import { computed } from "vue";

const props = defineProps<{
  model: any;
}>();

const model = computed(() => props.model?.model);
const navigationBar = computed(() => props.model?.navigationBar);
const creator = computed(() => props.model?.creator);

useBase(() => model.value);
</script>
