// packages/survey-creator-react/src/tabs/translation/TranslationLocaleItem.tsx
import * as React from "react";
import { ItemValue } from "survey-core";
import { ReactElementFactory, SurveyElementBase } from "survey-react-ui";
import { getTranslationLocaleProgress, translationLocaleItemComponentName } from "survey-creator-core";

// An item of the target language dropdown: the language name and, at the right edge, how much of
// the survey is already translated into it. The counts are precomputed on the choices themselves
// (see updateTargetLocaleChoices) - a language with no translations carries none.
export class TranslationLocaleItemComponent extends SurveyElementBase<{ item: ItemValue }, any> {
  private get item(): any {
    return this.props.item;
  }
  protected getStateElement(): ItemValue {
    return this.item;
  }
  renderElement(): React.JSX.Element {
    const item = this.item;
    if (!item) return null;
    const progress = getTranslationLocaleProgress(item);
    return (
      <div className="svc-translation-locale-item">
        <span className="svc-translation-locale-item__name">
          {this.renderLocString(item.locTitle, undefined, "locString")}
        </span>
        {!!progress ? <span className="svc-translation-locale-item__progress">{progress}</span> : null}
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  translationLocaleItemComponentName,
  (props) => {
    return React.createElement(TranslationLocaleItemComponent, props);
  }
);

// packages/survey-creator-angular/src/tabs/translation/translation-locale-item.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { ItemValue } from "survey-core";
import { getTranslationLocaleProgress, translationLocaleItemComponentName } from "survey-creator-core";

// An item of the target language dropdown: the language name and, at the right edge, how much of
// the survey is already translated into it. The counts are precomputed on the choices themselves
// (see updateTargetLocaleChoices) - a language with no translations carries none. The angular list
// item passes the item itself as "model" (react and vue pass it as "item").
@Component({
  selector: "svc-translation-locale-item",
  templateUrl: "./translation-locale-item.component.html",
  styles: [":host { display: none }"]
})
export class TranslationLocaleItemComponent extends BaseAngular<ItemValue> {
  @Input() model!: ItemValue;
  protected override getModel(): ItemValue {
    return this.model;
  }
  public get progress(): string {
    return getTranslationLocaleProgress(this.model);
  }
}

AngularComponentFactory.Instance.registerComponent(translationLocaleItemComponentName, TranslationLocaleItemComponent);

<ng-template #template>
  <div class="svc-translation-locale-item">
    <span class="svc-translation-locale-item__name">
      <sv-ng-string [model]="model.locTitle"></sv-ng-string>
    </span>
    <span *ngIf="!!progress" class="svc-translation-locale-item__progress">{{ progress }}</span>
  </div>
</ng-template>
