// packages/survey-creator-vue/src/components/ActionButton.vue
<template>
  <template v-if="!iconName">
    <span
      v-if="disabled"
      class="svc-action-button svc-action-button--disabled"
      :class="classes"
      :title="title"
      >{{ text }}</span
    >
    <span
      role="button"
      class="svc-action-button"
      @click="onClick"
      v-key2click
      :class="getButtonCss()"
      :title="title"
      >{{ text }}</span
    >
  </template>
  <template v-if="iconName">
    <span
      v-if="disabled"
      :class="getButtonCss()"
      :title="title"
      ><SvComponent :is="'sv-svg-icon'" :iconName="iconName" :size="'auto'"></SvComponent
    ></span>
    <span
      role="button"
      @click="onClick"
      v-key2click
      :class="getButtonCss()"
      :title="title"
      ><SvComponent :is="'sv-svg-icon'" :iconName="iconName" :size="'auto'"></SvComponent
    ></span>
  </template>
</template>
<script lang="ts" setup>
import { key2ClickDirective as vKey2click, SvComponent } from "survey-vue3-ui";
import { toCssClasses } from "survey-core";
const props = defineProps<{
  classes?: string;
  selected?: boolean;
  disabled?: boolean;
  text: string;
  title?: string;
  allowBubble?: boolean;
  click: () => void;
  iconName?: string;
}>();

const onClick = (event: Event) => {
  props.click();
  if (!props.allowBubble) {
    event.stopPropagation();
  }
};
const getButtonCss = () => {
  return toCssClasses(
    props.classes,
    "svc-action-button",
    !!props.iconName && "svc-action-button--icon",
    !!props.selected && "svc-action-button--selected",
    !!props.disabled && "svc-action-button--disabled"
  );
};
</script>

// packages/survey-creator-angular/src/components/action-button.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "survey-angular-ui";

@Component({
  selector: "svc-action-button",
  templateUrl: "./action-button.component.html",
  styles: [":host { display: none; }"]
})
export class ActionButtonComponent {

  @Input() classes: string = "";
  @Input() click!: () => void;
  @Input() selected: boolean = false;
  @Input() disabled: boolean = false;
  @Input() text: string = "";
  @Input() title: string = "";
  @Input() allowBubble: boolean = false;
  onClick(event: any) {
    this.click();
    if (!this.allowBubble) {
      event.stopPropagation();
    }
  }
}

AngularComponentFactory.Instance.registerComponent("svc-action-button", ActionButtonComponent);


<ng-template #template>
  <ng-container *ngIf="!iconName">
    <span *ngIf="disabled" class="svc-action-button svc-action-button--disabled" [class]="classes"
      [attr.title]="title">{{text}}</span>
    <span *ngIf="!disabled" role="button" class="svc-action-button" (click)="onClick($event)" [key2click]
      [attr.title]="title" [class.svc-action-button--selected]="selected" [class]="classes">{{text}}</span>
  </ng-container>
  <ng-container *ngIf="iconName">
    <span *ngIf="disabled" class="svc-action-button svc-action-button--disabled svc-action-button--icon"
      [class]="classes" [attr.title]="title">
      <svg [iconName]="iconName" [size]="'auto'" sv-ng-svg-icon></svg>
    </span>
    <span *ngIf="!disabled" class="svc-action-button svc-action-button--icon" (click)="onClick($event)" [key2click]
      [attr.title]="title" [attr.aria-label]="text" [class]="classes" [class.svc-action-button--selected]="selected">
      <svg [iconName]="iconName" [size]="'auto'" sv-ng-svg-icon></svg>
    </span>
  </ng-container>
</ng-template>
