// packages/survey-creator-vue/src/components/CollabRow.vue
<template>
  <div
    v-if="item.visible"
    :class="item.rowCss"
    :role="item.rowRole || undefined"
    :aria-expanded="item.ariaExpanded"
  >
    <span v-if="item.hasMarkerText" :class="item.markerCss">{{ item.markerText }}</span>
    <span v-else-if="item.hasMarkerIcon" class="svc-collab-row__icon">
      <SvComponent
        :is="'sv-svg-icon'"
        :iconName="item.markerIconName"
        :size="item.markerIconSize"
      />
    </span>
    <span class="svc-collab-row__title">{{ item.title }}</span>
    <span v-if="item.hasSubtitle" class="svc-collab-row__subtitle">{{ item.subtitle }}</span>
  </div>
</template>
<script lang="ts">
// sv-list also passes `model` (the ListModel) and `itemData`; without this they
// would be spread onto the root div as stray attributes.
export default {
  inheritAttrs: false,
};
</script>
<script lang="ts" setup>
import { SvComponent, useBase } from "survey-vue3-ui";
import type { CollabRowAction } from "survey-creator-core/collaboration";
const props = defineProps<{ item: CollabRowAction }>();
useBase(() => props.item);
</script>

// packages/survey-creator-angular/src/components/collab-row.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

// See the React CollabRow for what this renders. Presentation only, no events.
@Component({
  selector: "svc-collab-row",
  templateUrl: "./collab-row.component.html",
  styles: [":host { display: none; }"]
})
export class CollabRowComponent extends BaseAngular {
  // sv-list hands the action over as `model`, while the React and Vue list
  // renderers name it `item` - an inconsistency in survey-library. The
  // ComponentContainerModel elements built in creator-core therefore pass the
  // row under BOTH names, and each framework reads the one it expects.
  @Input() model: any;

  getModel() {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-collab-row", CollabRowComponent);

<ng-template #template>
  <div *ngIf="model.visible" [class]="model.rowCss" [attr.role]="model.rowRole || null"
    [attr.aria-expanded]="model.ariaExpanded">
    <span *ngIf="model.hasMarkerText" [class]="model.markerCss">{{ model.markerText }}</span>
    <span *ngIf="!model.hasMarkerText && model.hasMarkerIcon" class="svc-collab-row__icon">
      <svg [iconName]="model.markerIconName" [size]="model.markerIconSize" sv-ng-svg-icon></svg>
    </span>
    <span class="svc-collab-row__title">{{ model.title }}</span>
    <span *ngIf="model.hasSubtitle" class="svc-collab-row__subtitle">{{ model.subtitle }}</span>
  </div>
</ng-template>
