// packages/survey-creator-react/src/CollabRow.tsx
import * as React from "react";
// Type-only: the models live in the separate "survey-creator-core/collaboration"
// bundle, and this import is erased at build - the view carries no runtime
// dependency on it and stays in the main renderer bundle.
import type { CollabRowAction } from "survey-creator-core/collaboration";
import { Base } from "survey-core";
import { ReactElementFactory, SurveyElementBase, SvgIcon } from "survey-react-ui";

interface ICollabRowProps {
  item: CollabRowAction;
}

// The collaboration feature's only row renderer: a leading marker (avatar circle
// or icon), a title and an optional subtitle. Shared by the connection plate, a
// roster entry, a Version History row and the floating panel's title.
//
// Presentation only - it binds NO events. Interaction belongs to whatever wraps
// the row (the <li> of sv-list, the <button> of sv-action-bar) or to nothing at
// all, as for the connection plate. See CollabRowAction.
export class CollabRowComponent extends SurveyElementBase<ICollabRowProps, any> {
  get item(): CollabRowAction {
    return this.props.item;
  }

  protected getStateElement(): Base {
    return this.item;
  }

  protected canRender(): boolean {
    return !!this.item && this.item.visible && super.canRender();
  }

  private renderMarker(): JSX.Element {
    const item = this.item;
    if (item.hasMarkerText) {
      return <span className={item.markerCss}>{item.markerText}</span>;
    }
    if (item.hasMarkerIcon) {
      return (
        <span className="svc-collab-row__icon">
          <SvgIcon iconName={item.markerIconName} size={item.markerIconSize}></SvgIcon>
        </span>
      );
    }
    return null;
  }

  renderElement() {
    const item = this.item;
    return (
      <div
        className={item.rowCss}
        role={item.rowRole || undefined}
        aria-expanded={item.ariaExpanded}
      >
        {this.renderMarker()}
        <span className="svc-collab-row__title">{item.title}</span>
        {item.hasSubtitle ? <span className="svc-collab-row__subtitle">{item.subtitle}</span> : null}
      </div>
    );
  }
}

export default CollabRowComponent;

ReactElementFactory.Instance.registerElement("svc-collab-row", (props) => {
  return React.createElement(CollabRowComponent, props);
});

// packages/survey-creator-angular/src/components/collab-row.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

// See the React CollabRow for what this renders. Presentation only, no events.
@Component({
  selector: "svc-collab-row",
  templateUrl: "./collab-row.component.html",
  styles: [":host { display: none; }"]
})
export class CollabRowComponent extends BaseAngular {
  // sv-list hands the action over as `model`, while the React and Vue list
  // renderers name it `item` - an inconsistency in survey-library. The
  // ComponentContainerModel elements built in creator-core therefore pass the
  // row under BOTH names, and each framework reads the one it expects.
  @Input() model: any;

  getModel() {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-collab-row", CollabRowComponent);

<ng-template #template>
  <div *ngIf="model.visible" [class]="model.rowCss" [attr.role]="model.rowRole || null"
    [attr.aria-expanded]="model.ariaExpanded">
    <span *ngIf="model.hasMarkerText" [class]="model.markerCss">{{ model.markerText }}</span>
    <span *ngIf="!model.hasMarkerText && model.hasMarkerIcon" class="svc-collab-row__icon">
      <svg [iconName]="model.markerIconName" [size]="model.markerIconSize" sv-ng-svg-icon></svg>
    </span>
    <span class="svc-collab-row__title">{{ model.title }}</span>
    <span *ngIf="model.hasSubtitle" class="svc-collab-row__subtitle">{{ model.subtitle }}</span>
  </div>
</ng-template>
