// packages/survey-creator-react/src/QuestionError.tsx
import * as React from "react";
import { SurveyError } from "survey-core";
import { ReactElementFactory, SvgIcon } from "survey-react-ui";
import { SurveyLocStringViewer } from "survey-react-ui";

export interface IQuestionErrorComponentProps {
  error: SurveyError;
  cssClasses: any;
  element: any;
}

export class QuestionErrorComponent extends React.Component<IQuestionErrorComponentProps, any> {
  render(): React.JSX.Element | null {
    return (
      <div>
        <SvgIcon aria-hidden="true" iconName="icon-alert_24x24" size={"auto"} className={this.props.cssClasses.error.icon}></SvgIcon>
        <span className={this.props.cssClasses.error.item || undefined}>
          <SurveyLocStringViewer model={this.props.error.locText} />
        </span>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-question-error", (props) => {
  return React.createElement(QuestionErrorComponent, props);
});

// packages/survey-creator-angular/src/components/question-error.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "survey-angular-ui";
import { SurveyError } from "survey-core";

@Component({
  selector: "svc-question-error",
  templateUrl: "./question-error.component.html"
})
export class QuestionPgErrorComponent {
  @Input() error!: SurveyError;
  @Input() cssClasses?: any;
  @Input() element: any;
}
AngularComponentFactory.Instance.registerComponent("svc-question-error", QuestionPgErrorComponent);
<div>
  <svg [class]="cssClasses.error.icon" [iconName]="('icon-alert_24x24')" [size]="'auto'" sv-ng-svg-icon></svg>
  <span [class]="cssClasses ? cssClasses.error.item : 'panel-error-item'" [model]="error.locText" sv-ng-string>
  </span>
</div>
