// packages/survey-creator-vue/src/components/QuestionError.vue
<template>
  <div :key="errorKey">
    <SvComponent
      :is="'sv-svg-icon'"
      :class="cssClasses.error.icon"
      :iconName="'icon-alert_24x24'"
      :size="'auto'"
    ></SvComponent>
    <span
      :class="
        cssClasses ? cssClasses.error.item || undefined : 'panel-error-item'
      "
    >
      <SvComponent :is="'survey-string'" :locString="error.locText" />
    </span>
  </div>
</template>

<script lang="ts" setup>
import { SurveyError } from "survey-core";
import { SvComponent } from "survey-vue3-ui";
defineProps<{
  errorKey: string;
  error: SurveyError;
  cssClasses: any;
  element: any;
}>();
</script>

// packages/survey-creator-angular/src/components/question-error.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "survey-angular-ui";
import { SurveyError } from "survey-core";

@Component({
  selector: "svc-question-error",
  templateUrl: "./question-error.component.html"
})
export class QuestionPgErrorComponent {
  @Input() error!: SurveyError;
  @Input() cssClasses?: any;
  @Input() element: any;
}
AngularComponentFactory.Instance.registerComponent("svc-question-error", QuestionPgErrorComponent);
<div>
  <svg [class]="cssClasses.error.icon" [iconName]="('icon-alert_24x24')" [size]="'auto'" sv-ng-svg-icon></svg>
  <span [class]="cssClasses ? cssClasses.error.item : 'panel-error-item'" [model]="error.locText" sv-ng-string>
  </span>
</div>
