// packages/survey-creator-vue/src/tabs/preview/Simulator.vue
<template>
  <div
    :class="model.getRootCss()"
    @keydown="model.tryToZoom(undefined, $event)"
    @mouseover="activateZoom()"
    @mouseout="deactivateZoom()"
  >
    <div
      v-if="model.hasFrame"
      class="svd-simulator-wrapper"
      id="svd-simulator-wrapper"
      :style="{
        width: simulatorFrame.frameWidth + 'px',
        height: simulatorFrame.frameHeight + 'px',
      }"
    >
      <div
        class="svd-simulator-frame"
        :style="{
          width: simulatorFrame.landscapedFrameWidth + 'px',
          height: simulatorFrame.landscapedFrameHeight + 'px',
        }"
        :class="simulatorFrame.cssClass"
      ></div>
      <div
        class="svd-simulator"
        :style="{
          width: simulatorFrame.deviceWidth + 'px',
          height: simulatorFrame.deviceHeight + 'px',
          transform:
            'scale(' + simulatorFrame.scale + ') translate(-50%, -50%)',
        }"
      >
        <div class="svd-simulator-content">
          <survey-widget :model="model.survey"></survey-widget>
        </div>
      </div>
    </div>
    <div v-if="!model.hasFrame" class="svd-simulator-content">
      <survey-widget :model="model.survey"></survey-widget>
    </div>
  </div>
</template>
<script lang="ts" setup>
import type { SurveySimulatorModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { computed } from "vue";
const props = defineProps<{ model: SurveySimulatorModel }>();
useBase(() => props.model);
const simulatorFrame = computed(() => props.model.simulatorFrame);
const activateZoom = () => {
  if (props.model.device !== "desktop") {
    props.model.activateZoom();
  }
};
const deactivateZoom = () => {
  if (props.model.device !== "desktop") {
    props.model.deactivateZoom();
  }
};
</script>

// packages/survey-creator-angular/src/components/simulator.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { SurveySimulatorModel } from "survey-creator-core";

@Component({
  selector: "survey-simulator",
  templateUrl: "./simulator.component.html",
  styles: [":host { display: none; }"]
})
export class SimulatorComponent extends BaseAngular<SurveySimulatorModel> {
  @Input() model!: SurveySimulatorModel;
  protected getModel(): SurveySimulatorModel {
    return this.model;
  }
  public get simulatorFrame(): any {
    return this.model.simulatorFrame;
  }
  activateZoom() {
    if (this.model.device !== "desktop") {
      this.model.activateZoom();
    }
  }
  deactivateZoom() {
    if (this.model.device !== "desktop") {
      this.model.deactivateZoom();
    }
  }
}
<div [class]="'svd-simulator-main' + model.simulatorMainCssClass + (model.device === 'desktop' ? ' svd-simulator-main--desktop' : '')" (keydown)="model.tryToZoom($event, $event)" (mouseover)="activateZoom()" (mouseout)="deactivateZoom()">
  <div *ngIf="model.hasFrame" class="svd-simulator-wrapper" id="svd-simulator-wrapper" [style.width]="simulatorFrame.frameWidth + 'px'" [style.height]="simulatorFrame.frameHeight + 'px'">
    <div class="svd-simulator-frame" [style.width]="simulatorFrame.landscapedFrameWidth + 'px'" [style.height]="simulatorFrame.landscapedFrameHeight + 'px'" [class]="simulatorFrame.cssClass"></div>
    <div class="svd-simulator" [style.width]="simulatorFrame.deviceWidth + 'px'" [style.height]="simulatorFrame.deviceHeight + 'px'" [style.transform]="'scale(' + simulatorFrame.scale + ') translate(-50%, -50%)'">
      <div class="svd-simulator-content">
        <ng-template [component]="{ name: 'survey-widget', data: { model: model.survey } }"></ng-template>
      </div>
    </div>
  </div>
  <div *ngIf="!model.hasFrame" class="svd-simulator-content">
    <ng-template [component]="{ name: 'survey-widget', data: { model: model.survey } }"></ng-template>
  </div>
</div>
