// packages/survey-creator-vue/src/components/VersionHistory.vue
<template>
  <div class="svc-version-history">
    <template v-for="row in model.rows" :key="row.id">
      <!-- The group header is the only interactive row. -->
      <button
        v-if="row.kind === 'group'"
        type="button"
        :class="row.css"
        :aria-expanded="row.expanded"
        v-on:click="model.toggleGroup(row.groupKey)"
      >
        <span class="svc-version-history__icon">
          <SvComponent
            :is="'sv-svg-icon'"
            :iconName="row.expanded ? 'icon-chevrondown-16x16' : 'icon-chevronright-16x16'"
            :size="16"
          />
        </span>
        <span class="svc-version-history__title">{{ row.title }}</span>
      </button>
      <div v-else :class="row.css">
        <span class="svc-version-history__title">{{ row.title }}</span>
        <span v-if="row.time" class="svc-version-history__time">{{ row.time }}</span>
      </div>
    </template>
  </div>
</template>
<script lang="ts" setup>
import { SvComponent, useBase } from "survey-vue3-ui";
import type { VersionHistoryModel } from "survey-creator-core/collaboration";
const props = defineProps<{ model: VersionHistoryModel }>();
useBase(() => props.model);
</script>

// packages/survey-creator-angular/src/components/version-history.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-version-history",
  templateUrl: "./version-history.component.html",
  styles: [":host { display: none; }"]
})
export class VersionHistoryComponent extends BaseAngular {
  @Input() model: any;

  getModel() {
    return this.model;
  }

  // Row ids are stable across rebuilds, so ngFor keeps the DOM when only a
  // group's expansion changed.
  public trackByRowId(_index: number, row: any): string {
    return row.id;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-version-history", VersionHistoryComponent);

<ng-template #template>
  <div class="svc-version-history">
    <ng-container *ngFor="let row of model.rows; trackBy: trackByRowId">
      <!-- The group header is the only interactive row. -->
      <button *ngIf="row.kind === 'group'; else plain" type="button" [class]="row.css"
        [attr.aria-expanded]="row.expanded" (click)="model.toggleGroup(row.groupKey)">
        <span class="svc-version-history__icon">
          <svg [iconName]="row.expanded ? 'icon-chevrondown-16x16' : 'icon-chevronright-16x16'" [size]="16"
            sv-ng-svg-icon></svg>
        </span>
        <span class="svc-version-history__title">{{ row.title }}</span>
      </button>
      <ng-template #plain>
        <div [class]="row.css">
          <span class="svc-version-history__title">{{ row.title }}</span>
          <span *ngIf="row.time" class="svc-version-history__time">{{ row.time }}</span>
        </div>
      </ng-template>
    </ng-container>
  </div>
</ng-template>
