// packages/survey-creator-angular/presets/src/presets-property-grid.component.ts
import { Component, Input } from "@angular/core";
import { getLocString, PropertyGridViewModel } from "survey-creator-core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-presets-property-grid",
  templateUrl: "./presets-property-grid.component.html",
  styles: [":host { display: none; }"]
})
export class PresetsPropertyGridWrapperComponent extends BaseAngular<PropertyGridViewModel> {
  @Input() model?: PropertyGridViewModel;

  showPresets() {
    (this.model as any)["showPresets"]?.();
  }

  buttonTitle = getLocString("presets.plugin.buttonTitle");
  buttonDescription = getLocString("presets.plugin.buttonDescription");

  protected getModel(): PropertyGridViewModel {
    return this.model!;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-presets-property-grid", PresetsPropertyGridWrapperComponent);
<ng-template #template>
  <div class="sps-launch">
    <button class="sps-launch__card" (click)="showPresets()">
      <div class="sps-launch__container">
        <div class="sps-launch__text">{{buttonTitle}}</div>
        <div class="sps-launch__text2">{{buttonDescription}}</div>
        <div class="sps-launch__icon">
          <div class="sps-launch__chevron-right-16-x-16">
            <div class="sps-launch__icon2">
              <svg size="auto" iconName="chevrondown-24x24" sv-ng-svg-icon></svg>
            </div>
          </div>
        </div>
      </div>
    </button>
  </div>
  <ng-template [component]="{ name: 'svc-property-grid', data: {model: model} }">
  </ng-template>
</ng-template>

// packages/survey-creator-vue/src/presets/PresetsPropertyGrid.vue
<template>
  <div class="sps-launch">
    <button class="sps-launch__card" @click="showPresets">
      <div class="sps-launch__container">
        <div class="sps-launch__text">{{buttonTitle}}</div>
        <div class="sps-launch__text2">{{buttonDescription}}</div>
      </div>
      <div class="sps-launch__icon">
        <div class="sps-launch__chevron-right-16-x-16">
          <div class="sps-launch__icon2">
            <SvComponent
              :is="'sv-svg-icon'"
              size="auto"
              iconName="chevrondown-24x24"
            />
          </div>
        </div>
      </div>
    </button>
  </div>
  <SvComponent :is="'svc-property-grid'" :model="model" />
</template>

<script setup lang="ts">
import { SvComponent } from "survey-vue3-ui";
import { getLocString, type PropertyGridViewModel } from "survey-creator-core";

const props = defineProps<{
  model: PropertyGridViewModel;
}>();
const buttonTitle = getLocString("presets.plugin.buttonTitle");
const buttonDescription = getLocString("presets.plugin.buttonDescription");

const showPresets = () => {
  (props.model as any)["showPresets"]?.();
};
</script>
