// packages/survey-creator-react/src/ui-preset-editor/PresetsPropertyGrid.tsx
import * as React from "react";
import {
  ReactElementFactory,
  SvgIcon,
} from "survey-react-ui";
import { getLocString, PropertyGridViewModel } from "survey-creator-core";
interface IPresetsPropertyGridWrapperProps {
  model: PropertyGridViewModel;
}
export class PresetsPropertyGridWrapper extends React.Component<IPresetsPropertyGridWrapperProps, any> {
  constructor(props: IPresetsPropertyGridWrapperProps) {
    super(props);
  }
  render() {
    const model = this.props.model;
    if (!model) return null;

    return (
      <React.Fragment>
        <div className="sps-launch">
          <button className="sps-launch__card"
            onClick={ model["showPresets"] }
          >
            <div className="sps-launch__container">
              <div className="sps-launch__text">{getLocString("presets.plugin.buttonTitle")}</div>
              <div className="sps-launch__text2">{getLocString("presets.plugin.buttonDescription")}</div>
            </div>
            <div className="sps-launch__icon">
              <div className="sps-launch__chevron-right-16-x-16">
                <div className="sps-launch__icon2">
                  <SvgIcon size={"auto"} iconName={"chevrondown-24x24"}></SvgIcon>
                </div>
              </div>
            </div>
          </button>
        </div>
        { ReactElementFactory.Instance.createElement("svc-property-grid", { model: model })}
      </React.Fragment>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-presets-property-grid", (props) => {
  return React.createElement(PresetsPropertyGridWrapper, props as IPresetsPropertyGridWrapperProps);
});

// packages/survey-creator-vue/src/presets/PresetsPropertyGrid.vue
<template>
  <div class="sps-launch">
    <button class="sps-launch__card" @click="showPresets">
      <div class="sps-launch__container">
        <div class="sps-launch__text">{{buttonTitle}}</div>
        <div class="sps-launch__text2">{{buttonDescription}}</div>
      </div>
      <div class="sps-launch__icon">
        <div class="sps-launch__chevron-right-16-x-16">
          <div class="sps-launch__icon2">
            <SvComponent
              :is="'sv-svg-icon'"
              size="auto"
              iconName="chevrondown-24x24"
            />
          </div>
        </div>
      </div>
    </button>
  </div>
  <SvComponent :is="'svc-property-grid'" :model="model" />
</template>

<script setup lang="ts">
import { SvComponent } from "survey-vue3-ui";
import { getLocString, type PropertyGridViewModel } from "survey-creator-core";

const props = defineProps<{
  model: PropertyGridViewModel;
}>();
const buttonTitle = getLocString("presets.plugin.buttonTitle");
const buttonDescription = getLocString("presets.plugin.buttonDescription");

const showPresets = () => {
  (props.model as any)["showPresets"]?.();
};
</script>
