// packages/survey-creator-angular/src/tabs/logic/logic.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { SurveyLogicUI } from "survey-creator-core";

@Component({
  selector: "svc-tab-logic",
  templateUrl: "./logic.component.html",
  styles: [":host { display: none; }"]
})
export class LogicTabComponent extends BaseAngular<SurveyLogicUI> {
  @Input() model!: SurveyLogicUI;

  protected getModel(): SurveyLogicUI {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-tab-logic", LogicTabComponent);


<ng-template #template>
  <div class="svc-creator-tab__content">
    <div class="svc-plugin-tab__content svc-logic-tab__content" [class.svc-logic-tab__empty]="!model.hasItems">
      <survey-content [model]="model.itemsSurvey"></survey-content>
      <div *ngIf="!model.hasItems" class="svc-logic-tab__content-empty">
        <span class="svc-text">{{model.emptyTabPlaceHolder}}</span>
      </div>
      <ng-container *ngIf="!model.readOnly">
        <svc-tab-logic-add-btn [model]="model.addNewButton"></svc-tab-logic-add-btn>
      </ng-container>
    </div>
  </div>
</ng-template>

// packages/survey-creator-vue/src/tabs/logic/Logic.vue
<template>
  <div class="svc-creator-tab__content">
    <div
      class="svc-plugin-tab__content svc-logic-tab__content"
      :class="{ 'svc-logic-tab__empty': !model.hasItems }"
    >
      <SurveyComponent :model="model.itemsSurvey"></SurveyComponent>
      <div v-if="!model.hasItems" class="svc-logic-tab__content-empty">
        <span class="svc-text">{{ model.emptyTabPlaceholder }}</span>
      </div>
      <LogicAddButton
        v-if="!model.readOnly"
        :model="model.addNewButton"
      ></LogicAddButton>
    </div>
  </div>
</template>
<script lang="ts" setup>
import type { SurveyLogicUI } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import LogicAddButton from "./LogicAddButton.vue";

const props = defineProps<{
  model: SurveyLogicUI;
}>();
useBase(() => props.model);
</script>
