// packages/survey-creator-vue/src/page-navigator/PageNavigator.vue
<template>
  <div class="svc-page-navigator" v-show="model.visible" ref="root">
    <div>
      <div
        role="button"
        class="svc-page-navigator__selector svc-page-navigator__button"
        @click="model.togglePageSelector($event)"
        v-key2click
        :title="model.pageSelectorCaption"
        :class="{ 'svc-page-navigator__button--pressed': model.isPopupOpened }"
      >
        <SvComponent
          :is="'sv-svg-icon'"
          class="svc-page-navigator__button-icon"
          :iconName="model.icon"
          :size="'auto'"
        ></SvComponent>
      </div>
      <SvComponent :is="'sv-popup'" :model="model.popupModel"></SvComponent>
    </div>
    <div>
      <SvComponent
        :is="'svc-page-navigator-item'"
        v-for="item in model.visibleItems"
        :key="item.id"
        :model="item"
      ></SvComponent>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { key2ClickDirective as vKey2click } from "survey-vue3-ui";
import { SvComponent } from "survey-vue3-ui";
import { useCreatorModel } from "@/creator-model";
import {
  PageNavigatorViewModel,
  type PagesController,
} from "survey-creator-core";
import { onBeforeUnmount, onMounted, onUnmounted, ref } from "vue";

const props = defineProps<{
  pagesController: PagesController;
  pageEditMode: string;
}>();
const model = useCreatorModel(
  () => new PageNavigatorViewModel(props.pagesController, props.pageEditMode),
  [() => props.pagesController, () => props.pageEditMode]
);
const root = ref<HTMLDivElement>();

onMounted(() => {
  const el = root.value;
  const modelValue = model.value;
  if(el) {
    modelValue.attachToUI(el);
  }
});

onBeforeUnmount(() => {
  const modelValue = model.value;
  modelValue.stopItemsContainerHeightObserver();
  modelValue.setScrollableContainer(undefined as any);
});
onUnmounted(() => {
  const modelValue = model.value;
  modelValue.dispose();
});
</script>

// packages/survey-creator-angular/src/page-navigator/page-navigator.component.ts
import { AfterViewInit, Component, ElementRef, Input, ViewChild } from "@angular/core";
import { PageNavigatorViewModel, PagesController } from "survey-creator-core";
import { CreatorModelComponent } from "../creator-model.component";

@Component({
  selector: "svc-page-navigator",
  templateUrl: "./page-navigator.component.html",
  styles: [":host { display: none; }"]
})
export class PageNavigatorComponent extends CreatorModelComponent<PageNavigatorViewModel> implements AfterViewInit {
  public model!: PageNavigatorViewModel;
  @Input() pagesController!: PagesController;
  @Input() pageEditMode!: string;
  @ViewChild("container") container!: ElementRef<HTMLDivElement>;
  createModel(): void {
    this.model = new PageNavigatorViewModel(
      this.pagesController,
      this.pageEditMode
    );
  }
  protected getModel(): PageNavigatorViewModel {
    return this.model;
  }
  protected getPropertiesToTrack(): string[] {
    return ["pagesController", "pageEditMode"];
  }
  public ngAfterViewInit(): void {
    const el = this.container.nativeElement;
    this.model.attachToUI(el);
  }
  public override ngOnDestroy(): void {
    super.ngOnDestroy();
    this.model.stopItemsContainerHeightObserver();
    this.model.setScrollableContainer(undefined as any);
    this.model.dispose();
  }
}
<ng-template #template>
  <div class="svc-page-navigator" #container [visible]="model.visible">
      <div role="button" class="svc-page-navigator__selector svc-page-navigator__button"
          (click)="model.togglePageSelector($event)" [key2click] [attr.title]="model.pageSelectorCaption" [class.svc-page-navigator__button--pressed]="model.isPopupOpened">
          <svg class="svc-page-navigator__button-icon" [iconName]="model.icon" [size]="'auto'" sv-ng-svg-icon></svg>
      </div>
      <sv-ng-popup [popupModel]="model.popupModel"></sv-ng-popup>
      <div>
        <svc-page-navigator-item *ngFor="let item of model.visibleItems" [model]="item"></svc-page-navigator-item>
      </div>
  </div>
</ng-template>
