// packages/survey-creator-vue/src/custom-questions/BooleanSwitch.vue
<template>
  <div class="spg-boolean-switch" role="checkbox"
      :aria-required="question.ariaRequired"
      :aria-label="question.ariaLabel"
      :aria-invalid="question.ariaInvalid"
      :aria-errormessage="question.ariaErrormessage"
      @click="question.value = !question.value"
    >
    <div class="spg-boolean-switch__button" tabindex="0"
      :class="question.value ? 'spg-boolean-switch__button--checked' : ''"
      v-key2click="{ disableTabStop: true }"
      >
      <div class="spg-boolean-switch__thumb">
        <div class="spg-boolean-switch__thumb-circle spg-boolean-switch__thumb--left"></div>
      </div>
      <div class="spg-boolean-switch__thumb">
        <div class="spg-boolean-switch__thumb-circle spg-boolean-switch__thumb--right"></div>
      </div>
    </div>
    <div class="spg-boolean-switch__caption">
      <div class="spg-boolean-switch__title">
        <SvComponent
            :is="'survey-string'"
            :locString="question.locTitle"
          />
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { RendererFactory } from "survey-core";
import { ref } from "vue";
import { useQuestion, SvComponent } from "survey-vue3-ui";
defineOptions({ inheritAttrs: false });
const props = defineProps<{ question: any }>();
const root = ref(null);
useQuestion(props, root);
</script>

<script lang="ts">
RendererFactory.Instance.registerRenderer(
  "boolean",
  "switch",
  "sv-boolean-switch"
);
</script>

// packages/survey-creator-react/src/custom-questions/BooleanSwitch.tsx
import * as React from "react";
import { RendererFactory } from "survey-core";
import { ReactQuestionFactory, SurveyElementBase, SurveyQuestionElementBase } from "survey-react-ui";

export class SurveyQuestionBooleanSwitch extends SurveyQuestionElementBase {
  protected renderElement(): JSX.Element {
    return (
      <div className="spg-boolean-switch" onClick={() => this.questionBase.value = !this.questionBase.value}>
        <div className={"spg-boolean-switch__button" + (this.questionBase.value ? " spg-boolean-switch__button--checked" : "")} tabIndex={0}
          role="checkbox"
          aria-required={this.questionBase.ariaRequired}
          aria-label={this.questionBase.ariaLabel}
          aria-invalid={this.questionBase.ariaInvalid}
          aria-errormessage={this.questionBase.ariaErrormessage}
        >
          <div className="spg-boolean-switch__thumb">
            <div className="spg-boolean-switch__thumb-circle spg-boolean-switch__thumb--left"></div>
          </div>
          <div className="spg-boolean-switch__thumb">
            <div className="spg-boolean-switch__thumb-circle spg-boolean-switch__thumb--right"></div>
          </div>
        </div>
        <div className="spg-boolean-switch__caption">
          <div className="spg-boolean-switch__title">
            {SurveyElementBase.renderLocString(this.questionBase.locTitle)}
          </div>
        </div>
      </div>
    );
  }
}

ReactQuestionFactory.Instance.registerQuestion(
  "sv-boolean-switch",
  (props) => {
    return React.createElement(SurveyQuestionBooleanSwitch, props);
  }
);

RendererFactory.Instance.registerRenderer(
  "boolean",
  "switch",
  "sv-boolean-switch"
);
