// packages/survey-creator-angular/src/tab-control/tab-button.component.ts
import { Component, Input } from "@angular/core";
import { Action, CssClassBuilder } from "survey-core";
import { BaseAngular, AngularComponentFactory } from "survey-angular-ui";

@Component({
  selector: "svc-tab-button",
  templateUrl: "./tab-button.component.html",
  styles: [":host { display: none; }"]
})
export class TabButtonComponent extends BaseAngular<Action> {
  @Input() model!: Action;
  protected getModel(): Action {
    return this.model;
  }

  get buttonClassName(): string {
    const className = new CssClassBuilder()
      .append("svc-menu-action__button")
      .append("svc-menu-action__button--selected", !!this.model.active)
      .toString();
    return className;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-tab-button", TabButtonComponent);
<ng-template #template>
  <div class="svc-menu-action">
    <div [class]="model.buttonClassName" [attr.title]="model.tooltip" (click)="model.action()">
      <div class="svc-menu-action__icon">
        <div class="svc-menu-action__icon-container">
          <svg [iconName]="model.iconName" [size]="24" sv-ng-svg-icon></svg>
        </div>
      </div>
    </div>
  </div>
</ng-template>

// packages/survey-creator-vue/src/tab-control/TabButton.vue
<template>
  <div class="svc-menu-action">
    <div :class="buttonClassName" :title="model.tooltip" @click="model.action()">
      <div class="svc-menu-action__icon">
        <div class="svc-menu-action__icon-container">
          <sv-svg-icon
            :iconName="model.iconName"
            :size="24"
          ></sv-svg-icon>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { Action, CssClassBuilder } from "survey-core";
import { useBase } from "survey-vue3-ui";
import { computed } from "vue";
const props = defineProps<{ model: Action }>();
const buttonClassName = computed<string>(
  () => {
    const className = new CssClassBuilder()
      .append("svc-menu-action__button")
      .append("svc-menu-action__button--selected", !!props.model.active)
      .toString();
    return className;
  }
);
useBase(() => props.model);
</script>
