// packages/survey-creator-angular/src/tab-control/tab-control.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular, AngularComponentFactory } from "survey-angular-ui";
import { TabControlModel } from "survey-creator-core";

@Component({
  selector: "svc-tab-control",
  templateUrl: "./tab-control.component.html",
  styles: [":host { display: none; }"]
})
export class TabControlComponent extends BaseAngular<TabControlModel> {
  @Input() model!: TabControlModel;
  protected getModel(): TabControlModel {
    return this.model;
  }

  get sideBarClassName(): string {
    return "svc-sidebar-tabs" + (this.model.sidePanel.visible ? "" : " svc-sidebar-tabs--collapsed");
  }
}
AngularComponentFactory.Instance.registerComponent("svc-tab-control", TabControlComponent);
<ng-template #template>
  <div [class]="sideBarClassName">
    <div class="svc-sidebar-tabs__top-container">
      <div class="svc-sidebar-tabs__collapse-button">
        <svc-tab-button [model]="this.model.expandCollapseAction"></svc-tab-button>
      </div>
      <div className="svc-sidebar-tabs__separator">
        <div></div>
      </div>
      <div className="svc-sidebar-tabs__items">
        <svc-tabs [model]="this.model.topToolbar"></svc-tabs>
      </div>
    </div>
    <div className="svc-sidebar-tabs__bottom-container">
      <div className="svc-sidebar-tabs__items">
        <svc-tabs [model]="this.model.bottomToolbar"></svc-tabs>
      </div>
    </div>
  </div>
</ng-template>

// packages/survey-creator-vue/src/tab-control/TabControl.vue
<template>
  <div :class="sideBarClassName">
    <div class="svc-sidebar-tabs__top-container">
      <div class="svc-sidebar-tabs__collapse-button">
        <svc-tab-button :model="model.expandCollapseAction"></svc-tab-button>
      </div>
      <div class="svc-sidebar-tabs__separator">
        <div></div>
      </div>
      <div class="svc-sidebar-tabs__items">
        <svc-tabs :model="model.topToolbar"></svc-tabs>
      </div>
    </div>
    <div class="svc-sidebar-tabs__bottom-container">
      <div class="svc-sidebar-tabs__items">
        <svc-tabs :model="model.bottomToolbar"></svc-tabs>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { TabControlModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { computed } from "vue";
const props = defineProps<{ model: TabControlModel }>();
const sideBarClassName = computed<string>(
  () => "svc-sidebar-tabs" + (props.model.sidePanel.visible ? "" : " svc-sidebar-tabs--collapsed")
);

useBase(() => props.model);
</script>
