// packages/survey-creator-react/src/tab-control/TabControl.tsx
import * as React from "react";
import { Action, ActionContainer, Base } from "survey-core";
import { SurveyElementBase, ReactElementFactory } from "survey-react-ui";
import { TabControlModel } from "survey-creator-core";
import { TabButtonComponent } from "./TabButton";

interface ITabControlProps {
  model?: TabControlModel;
}

class TabControl extends SurveyElementBase<any, any> {
  constructor(props: ITabControlProps) {
    super(props);
  }

  protected getStateElement(): Base {
    return this.props.model;
  }

  public canRender(): boolean {
    if (!this.props.model) return false;
    return super.canRender();
  }
  renderElement() {
    const className = "svc-sidebar-tabs" + (this.props.model.sidePanel.visible ? "" : " svc-sidebar-tabs--collapsed");
    return (
      <div className={className}>
        <div className="svc-sidebar-tabs__top-container">
          <div className="svc-sidebar-tabs__collapse-button">
            <TabButtonComponent model={this.props.model.expandCollapseAction} ></TabButtonComponent>
          </div>
          <div className="svc-sidebar-tabs__separator">
            <div></div>
          </div>
          <div className="svc-sidebar-tabs__items">
            <TabsComponent model={this.props.model.topToolbar}></TabsComponent>
          </div>
        </div>
        <div className="svc-sidebar-tabs__bottom-container">
          <div className="svc-sidebar-tabs__items">
            <TabsComponent model={this.props.model.bottomToolbar}></TabsComponent>
          </div>
        </div>
      </div>
    );
  }

}

ReactElementFactory.Instance.registerElement("svc-tab-control", (props) => {
  return React.createElement(TabControl, props);
});

class TabsComponent extends SurveyElementBase<{ model: ActionContainer }, any> {
  constructor(props: { model: ActionContainer }) {
    super(props);
  }

  protected getStateElement(): Base {
    return this.props.model;
  }

  protected renderElement(): JSX.Element | null {
    return <>{this.props.model.actions.map(
      (item: Action, itemIndex: number) => <TabButtonComponent model={item} key={"item" + itemIndex}></TabButtonComponent>
    )}</>;
  }
}

// packages/survey-creator-vue/src/tab-control/TabControl.vue
<template>
  <div :class="sideBarClassName">
    <div class="svc-sidebar-tabs__top-container">
      <div class="svc-sidebar-tabs__collapse-button">
        <svc-tab-button :model="model.expandCollapseAction"></svc-tab-button>
      </div>
      <div class="svc-sidebar-tabs__separator">
        <div></div>
      </div>
      <div class="svc-sidebar-tabs__items">
        <svc-tabs :model="model.topToolbar"></svc-tabs>
      </div>
    </div>
    <div class="svc-sidebar-tabs__bottom-container">
      <div class="svc-sidebar-tabs__items">
        <svc-tabs :model="model.bottomToolbar"></svc-tabs>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { TabControlModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { computed } from "vue";
const props = defineProps<{ model: TabControlModel }>();
const sideBarClassName = computed<string>(
  () => "svc-sidebar-tabs" + (props.model.sidePanel.visible ? "" : " svc-sidebar-tabs--collapsed")
);

useBase(() => props.model);
</script>
