// packages/survey-creator-vue/src/side-bar/SideBarHeader.vue
<template>
  <div class="svc-side-bar__container-header svc-sidebar__header-container">
    <div v-if="!model.subTitle" class="svc-side-bar__container-title">{{ model.title }}</div>
    <div v-if="!!model.subTitle" class="svc-sidebar__header-caption">
      <span class="svc-sidebar__header-title">{{ model.title }}</span>
      <span class="svc-sidebar__header-subtitle">{{ model.subTitle }}</span>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { SidebarHeaderModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ model: SidebarHeaderModel }>();
useBase(() => props.model);
</script>

<ng-template #template>
</ng-template>

// packages/survey-creator-angular/src/side-bar/side-bar-header.component.ts

import { Component, Input } from "@angular/core";
import { BaseAngular } from "survey-angular-ui";
import { SidebarHeaderModel } from "survey-creator-core";

@Component({
  selector: "svc-side-bar-header",
  templateUrl: "./side-bar-header.component.html",
  styles: [":host { display: none; }"]
})
export class SidebarHeaderComponent extends BaseAngular<SidebarHeaderModel> {
  @Input() model!: SidebarHeaderModel;
  protected getModel(): SidebarHeaderModel {
    return this.model;
  }
}
<ng-template #template>
  <div class="svc-side-bar__container-header svc-sidebar__header-container">
    <ng-container *ngIf="!model.subTitle">
      <div class="svc-side-bar__container-title">{{model.title}}</div>
    </ng-container>
    <ng-container *ngIf="!!model.subTitle">
      <div class="svc-sidebar__header-caption">
        <span class="svc-sidebar__header-title">{{model.title}}</span>
        <span class="svc-sidebar__header-subtitle">{{model.subTitle}}</span>
      </div>
    </ng-container>
  </div>
</ng-template>
