// packages/survey-creator-vue/src/side-bar/SideBar.vue
<template>
  <div
    class="svc-side-bar"
    :class="{ 'svc-flyout-side-bar': model.flyoutPanelMode }"
    v-show="model.hasVisiblePages"
  >
    <div
      class="svc-side-bar__shadow"
      @click="() => model.collapseSidebar()"
    ></div>
    <div class="svc-flex-row svc-side-bar__wrapper">
      <div
        class="svc-side-bar__container"
        v-show="model.renderedIsVisible"
        ref="root"
      >
        <div class="svc-side-bar__container-header">
          <div class="svc-side-bar__container-actions">
            <sv-action-bar :model="model.toolbar"></sv-action-bar>
          </div>
          <div v-if="!!model.headerText" class="svc-side-bar__container-title">
            {{ model.headerText }}
          </div>
        </div>
        <div class="svc-side-bar__container-content">
          <template v-for="(page, index) in model.pages" :key="index">
            <svc-side-bar-page :model="page"></svc-side-bar-page>
          </template>
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { onMounted, onUnmounted, ref } from "vue";
import type { SidebarModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ model: SidebarModel }>();
const root = ref<HTMLDivElement>();
useBase(() => props.model);
onMounted(() => {
  props.model.initResizeManager(root.value as HTMLDivElement);
});
onUnmounted(() => {
  props.model.resetResizeManager();
});
</script>

// packages/survey-creator-angular/src/side-bar/side-bar.component.ts
import { SidebarModel } from "survey-creator-core";
import { AfterViewInit, Component, ElementRef, Input, OnInit, ViewChild } from "@angular/core";
import { BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-side-bar",
  templateUrl: "./side-bar.component.html",
  styles: [":host { display: none; }"]
})
export class SidebarComponent extends BaseAngular<SidebarModel> implements AfterViewInit {
  @Input() model!: SidebarModel;
  @ViewChild("container") container!: ElementRef<HTMLElement>;
  protected getModel(): SidebarModel {
    return this.model;
  }

  override ngOnDestroy(): void {
    this.model.resetResizeManager();
    super.ngOnDestroy();
  }
  ngAfterViewInit(): void {
    this.model.initResizeManager(this.container.nativeElement as HTMLDivElement);
  }
}
<ng-template #template>
  <div class="svc-side-bar" [class.svc-flyout-side-bar]="model.flyoutPanelMode" [visible]="model.hasVisiblePages">
    <div class="svc-side-bar__shadow" (click)="model.collapseSidebar()"></div>
    <div class="svc-flex-row svc-side-bar__wrapper">
      <div class="svc-side-bar__container" [visible]="model.renderedIsVisible" #container>
        <ng-container *ngIf="model.headerComponentName">
          <ng-template
            [component]="{ name: model.headerComponentName, data: { model: model.headerComponentData } }"></ng-template>
        </ng-container>
        <ng-container *ngIf="!model.headerComponentName">
          <div class="svc-side-bar__container-header">
            <div class="svc-side-bar__container-actions">
              <sv-action-bar [model]="model.toolbar"></sv-action-bar>
            </div>
            <div *ngIf="!!model.headerText" class="svc-side-bar__container-title">{{model.headerText}}</div>
          </div>
        </ng-container>
        <div class="svc-side-bar__container-content">
          <ng-container *ngFor="let page of model.pages">
            <svc-side-bar-page [model]="page"></svc-side-bar-page>
          </ng-container>
        </div>
      </div>
      <ng-container *ngIf="model.sideAreaComponentName">
        <ng-template
          [component]="{ name: model.sideAreaComponentName, data: { model: model.sideAreaComponentData } }"></ng-template>
      </ng-container>
    </div>
  </div>
</ng-template>
