// packages/survey-creator-vue/src/side-bar/TabButton.vue
<template>
  <div v-if="model.visible" class="svc-menu-action">
    <div
      :class="model.buttonClassName"
      :title="model.tooltip"
      @click="model.action()"
      v-key2click="{ processEsc: false, disableTabStop: model.disableTabStop }"
    >
      <div class="svc-menu-action__icon">
        <div class="svc-menu-action__icon-container">
          <SvComponent
            :is="'sv-svg-icon'"
            :iconName="model.iconName"
            :size="'auto'"
          ></SvComponent>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { MenuButton } from "survey-creator-core";
import {
  SvComponent,
  useBase,
  key2ClickDirective as vKey2click,
} from "survey-vue3-ui";
const props = defineProps<{ model: MenuButton }>();

useBase(() => props.model);
</script>

// packages/survey-creator-angular/src/side-bar/tab-button.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular, AngularComponentFactory } from "survey-angular-ui";
import { Action } from "survey-core";
@Component({
  selector: "svc-tab-button",
  templateUrl: "./tab-button.component.html",
  styles: [":host { display: none; }"]
})
export class TabButtonComponent extends BaseAngular<Action> {
  @Input() model!: Action;
  protected getModel(): Action {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-tab-button", TabButtonComponent);
<ng-template #template>
  <div *ngIf="model.visible" class="svc-menu-action">
    <div [class]="model.buttonClassName" [key2click]="{ processEsc: false, disableTabStop: model.disableTabStop }"
      [attr.title]="model.tooltip" (click)="model.action()">
      <div class="svc-menu-action__icon">
        <div class="svc-menu-action__icon-container">
          <svg [iconName]="model.iconName" [size]="'auto'" sv-ng-svg-icon></svg>
        </div>
      </div>
    </div>
  </div>
</ng-template>
