// packages/survey-creator-vue/src/side-bar/Tabs.vue
<template>
  <template v-for="(action, index) in model.actions" :key="index">
    <SvComponent :is="'svc-tab-button'" :model="action"></SvComponent>
  </template>
</template>

<script lang="ts" setup>
import type { ActionContainer, Action } from "survey-core";
import { useBase } from "survey-vue3-ui";
import { SvComponent } from "survey-vue3-ui";
const props = defineProps<{ model: ActionContainer<Action> }>();
useBase(() => props.model);
</script>

// packages/survey-creator-angular/src/side-bar/tabs.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "survey-angular-ui";
import { Action, ActionContainer } from "survey-core";
@Component({
  selector: "svc-tabs",
  templateUrl: "./tabs.component.html",
  styles: [":host { display: none; }"]
})
export class TabsComponent extends BaseAngular<ActionContainer<Action>> {
  @Input() model!: ActionContainer<Action>;
  protected getModel(): ActionContainer<Action> {
    return this.model;
  }
}
<ng-template #template>
  <ng-container *ngFor="let action of model.actions">
    <svc-tab-button [model]="action"></svc-tab-button>
  </ng-container>
</ng-template>
