// packages/survey-creator-vue/src/toolbox/AdaptiveToolbox.vue
<template>
  <div
    class="svc-toolbox"
    :class="{ 'svc-toolbox--compact': toolbox.isCompact }"
    @scroll="(e) => { toolbox.onScroll(toolbox, e); }"
    ref="root"
  >
    <div class="svc-toolbox__container">
      <template
        v-if="
          !(
            toolbox.isCompact ||
            toolbox.categories.length == 1 ||
            !toolbox.showCategoryTitles
          )
        "
      >
        <svc-toolbox-category
          v-for="(category, index) in toolbox.categories"
          :key="index"
          :category="category"
          :toolbox="toolbox"
        ></svc-toolbox-category>
      </template>
      <template
        v-if="
          toolbox.isCompact ||
          toolbox.categories.length == 1 ||
          !toolbox.showCategoryTitles
        "
      >
        <div class="svc-toolbox__category">
          <template v-for="(item, index) in renderedActions" :key="index">
            <div
              v-if="item.needSeparator && !creator.toolbox.showCategoryTitles"
              class="svc-toolbox__category-separator"
            ></div>
            <svc-toolbox-tool
              :creator="creator"
              :item="item"
              :parentModel="toolbox"
              :isCompact="toolbox.isCompact"
            ></svc-toolbox-tool>
          </template>
        </div>
      </template>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { VerticalResponsivityManager } from "survey-core";
import type { SurveyCreatorModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { computed, onMounted, onUnmounted, ref } from "vue";
const props = defineProps<{ creator: SurveyCreatorModel }>();
const toolbox = computed(() => {
  return props.creator.toolbox;
});

const root = ref<HTMLDivElement>();

useBase(() => toolbox.value);
let responsivityManager: VerticalResponsivityManager;
onMounted(() => {
  responsivityManager = new VerticalResponsivityManager(
    root.value as HTMLDivElement,
    toolbox.value,
    ".svc-toolbox__tool:not(.sv-dots)"
  );
});
onUnmounted(() => {
  responsivityManager?.dispose();
});
const renderedActions = computed(() => toolbox.value.renderedActions);
</script>

// packages/survey-creator-react/src/components/toolbox/AdaptiveToolbox.tsx
import React from "react";
import { VerticalResponsivityManager } from "survey-core";
import { ReactElementFactory } from "survey-react-ui";
import { SurveyCreatorToolboxTool } from "./ToolboxItem";
import { ISurveyCreatorToolboxProps, Toolbox } from "./Toolbox";

export class AdaptiveToolbox extends Toolbox {
  private manager: VerticalResponsivityManager;
  private rootRef: React.RefObject<HTMLDivElement>;

  constructor(props: ISurveyCreatorToolboxProps) {
    super(props);
    this.rootRef = React.createRef();
  }

  componentDidMount() {
    super.componentDidMount();
    const container = this.rootRef.current;
    if (!container) return;
    this.manager = new VerticalResponsivityManager(
      container,
      this.toolbox,
      ".svc-toolbox__tool:not(.sv-dots)>.sv-action__content",
      40
    );
  }
  componentWillUnmount() {
    this.manager && (this.manager.dispose());
    super.componentWillUnmount();
  }
  render(): JSX.Element {
    if (!this.toolbox.hasActions) return null;

    const className = "svc-toolbox" + (this.toolbox.isCompact ? " svc-toolbox--compact" : "");
    return (
      <div ref={this.rootRef} className={className}>
        <div className="svc-toolbox__container">
          {(this.toolbox.isCompact || this.toolbox.categories.length == 1) ?
            (<div className="svc-toolbox__category">
              {this.renderItems(this.toolbox.renderedActions, this.toolbox.isCompact)}
            </div>)
            : this.renderCategories()
          }
        </div>
      </div>
    );
  }

  renderItems(items: Array<any>, isCompact?: boolean) {
    return items.map((item, itemIndex) =>
      <SurveyCreatorToolboxTool item={(item as any)} creator={this.creator} isCompact={isCompact} key={"item" + itemIndex}></SurveyCreatorToolboxTool>
    );
  }

  protected renderCategoryContent(category: any): Array<any> {
    let items = [];
    if (!category.collapsed) {
      items = this.renderItems(category.items, false);
    }
    return items;
  }
}

ReactElementFactory.Instance.registerElement("svc-adaptive-toolbox", (props) => {
  return React.createElement(AdaptiveToolbox, props);
});
