// packages/survey-creator-angular/src/toolbox/toolbox-item.component.ts
import { Component, Input } from "@angular/core";
import { ToolboxToolViewModel, CreatorBase, IQuestionToolboxItem, editorLocalization } from "survey-creator-core";
import { BaseAngular, AngularComponentFactory } from "survey-angular-ui";
import { Action } from "survey-core";

@Component({
  selector: "svc-toolbox-item",
  templateUrl: "./toolbox-item.component.html",
  styles: [":host { display: none; }"]
})
export class ToolboxItemComponent extends BaseAngular<ToolboxToolViewModel> {
  @Input() creator!: CreatorBase;
  @Input() model!: Action;
  @Input() isCompact: boolean = false;
  @Input() viewModel!: ToolboxToolViewModel
  protected getModel(): ToolboxToolViewModel {
    return this.viewModel;
  }
  public get item() {
    return this.model;
  }
  public get ariaLabel(): string {
    return this.item.tooltip + " " + editorLocalization.getString("toolbox") + " item";
  }
}
AngularComponentFactory.Instance.registerComponent("svc-toolbox-item", ToolboxItemComponent);

<ng-template #template>
  <div role="button" [attr.aria-label]="this.item.tooltip" [class]="this.item.renderedCss"
    (click)="viewModel.click($event)" [key2click]>
    <span class="svc-toolbox__item-container">
      <svg *ngIf="item.iconName" [iconName]="item.iconName" [size]="'auto'" class="svc-toolbox__item-icon" [title]="this.item.tooltip"
        sv-ng-svg-icon></svg>
    </span>
    <span *ngIf="!isCompact" class="svc-toolbox__item-title">{{item.title}}</span>
    </div>
  <span *ngIf="isCompact" class="svc-toolbox__item-banner" (click)="viewModel.click($event)">
    <svg *ngIf="item.iconName" [iconName]="item.iconName" [size]="'auto'" class="svc-toolbox__item-icon"
      sv-ng-svg-icon></svg>
    <span>{{item.title}}</span>
    </span>
</ng-template>

// packages/survey-creator-react/src/components/toolbox/ToolboxItem.tsx
import {
    CreatorBase,
    editorLocalization,
    IQuestionToolboxItem
  } from "@survey/creator";
  import React from "react";
  import { ToolboxItemViewModel } from "@survey/creator";
  import {
    Base,
    SurveyModel
  } from "survey-core";
  import {
    ReactElementFactory,
    SurveyElementBase,
    SvgIcon
  } from "survey-react-ui";
  
  export interface ISurveyCreatorToolboxItemProps {
    item: IQuestionToolboxItem;
    creator: CreatorBase<SurveyModel>;
    isCompact: boolean
  }
  
  export class SurveyCreatorToolboxItem extends SurveyElementBase<
    ISurveyCreatorToolboxItemProps,
    any
  > {
    model: ToolboxItemViewModel;
    constructor(props) {
      super(props);
      const toolboxItem: IQuestionToolboxItem = this.props.item;
      this.model = new ToolboxItemViewModel(toolboxItem, this.props.creator);
    }
    public get item() {
      return this.props.item;
    }
    public get creator() {
      return this.props.creator;
    }
    protected getStateElement(): Base {
      return this.model;
    }
    render(): JSX.Element {
      const className =
        "svc-toolbox__item svc-toolbox__item--" + this.item.iconName;
      return (
        <div
          className={className}
          tabIndex={0}
          title={this.item.tooltip}
          role="button"
          aria-label={
            this.item.tooltip +
            " " +
            editorLocalization.getString("toolbox") +
            " item"
          }
          onPointerDown={(event: any) => {
            event.persist();
            this.model.onPointerDown(event);
          }}
        >
          <span className="svc-toolbox__item-container">
            <SvgIcon size={24} iconName={this.item.iconName}></SvgIcon>
          </span>
          {(this.props.isCompact ?
            <span className="svc-toolbox__item-banner">
              <SvgIcon size={24} iconName={this.item.iconName}></SvgIcon>
              <span className="svc-toolbox__item-title">{this.item.title}</span>
            </span>
            :
            <span className="svc-toolbox__item-title">{this.item.title}</span>
          )}
        </div>
      );
    }
  }
  
  ReactElementFactory.Instance.registerElement("svc-toolbox-item", (props) => {
    return React.createElement(SurveyCreatorToolboxItem, props);
  });
