// packages/survey-creator-angular/src/side-bar/side-bar-tab.component.ts

import { Component, Input } from "@angular/core";
import { BaseAngular } from "survey-angular-ui";
import { SidebarTabModel } from "survey-creator-core";

@Component({
  selector: "svc-side-bar-tab",
  templateUrl: "./side-bar-tab.component.html",
  styles: [":host { display: none; }"]
})
export class SidebarTabComponent extends BaseAngular<SidebarTabModel> {
  @Input() model!: SidebarTabModel;
  protected getModel(): SidebarTabModel {
    return this.model;
  }
}
<ng-template #template>
  <ng-container *ngIf="model.visible">
    <ng-template [component]="{ name: model.componentName, data: { model: model.model } }"></ng-template>
  </ng-container>
</ng-template>

// packages/survey-creator-vue/src/side-bar/SideBarTab.vue
<template>
  <SvComponent
    v-if="model.visible"
    :name="model.componentName"
    :model="model.model"
  ></SvComponent>
</template>

<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import type { SidebarTabModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ model: SidebarTabModel }>();
useBase(() => props.model);
</script>
