// packages/survey-creator-angular/src/side-bar/side-bar-default-header.component.ts

import { Component, Input } from "@angular/core";
import { BaseAngular } from "survey-angular-ui";
import { SidebarHeaderModel } from "survey-creator-core";

@Component({
  selector: "svc-side-bar-default-header",
  templateUrl: "./side-bar-default-header.component.html",
  styles: [":host { display: none; }"]
})
export class SidebarDefaultHeaderComponent extends BaseAngular<SidebarHeaderModel> {
  @Input() model!: SidebarHeaderModel;
  protected getModel(): SidebarHeaderModel {
    return this.model;
  }
}
<ng-template #template>
  <div class="svc-side-bar__container-header">
    <div class="svc-side-bar__container-actions">
      <sv-action-bar [model]="model.toolbar"></sv-action-bar>
    </div>
    <div *ngIf="!!model.title" class="svc-side-bar__container-title">{{model.title}}</div>
  </div>
</ng-template>

// packages/survey-creator-vue/src/side-bar/SideBarDefaultHeader.vue
<template>
  <div class="svc-side-bar__container-header">
    <div class="svc-side-bar__container-actions">
      <SvComponent :is="'sv-action-bar'" :model="model.toolbar"></SvComponent>
    </div>
    <div v-if="!!model.title" class="svc-side-bar__container-title">
      {{ model.title }}
    </div>
  </div>
</template>

<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import type { SidebarHeaderModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ model: SidebarHeaderModel }>();
useBase(() => props.model);
</script>
