// packages/survey-creator-vue/src/tabs/preview/Simulator.vue
<template>
  <div
    :class="model.getRootCss()"
    @keydown="model.tryToZoom(undefined, $event)"
    @mouseover="activateZoom()"
    @mouseout="deactivateZoom()"
  >
    <div v-if="!model.hasFrame" class="svd-simulator-content">
      <SvComponent :name="'survey-widget'" :model="model.survey"></SvComponent>
    </div>
    <div
      v-if="model.hasFrame"
      class="svd-simulator-wrapper"
      id="svd-simulator-wrapper"
      :style="{
        width: simulatorFrame.frameWidth + 'px',
        height: simulatorFrame.frameHeight + 'px',
      }"
    >
      <div
        class="svd-simulator"
        :style="{
          width: simulatorFrame.deviceWidth + 'px',
          height: simulatorFrame.deviceHeight + 'px',
          transform:
            'scale(' + simulatorFrame.scale + ') translate(-50%, -50%)',
        }"
      >
        <div class="svd-simulator-content">
          <SvComponent :name="'survey-widget'" :model="model.survey"></SvComponent>
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
 import { SvComponent } from "survey-vue3-ui";
import type { SurveySimulatorModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { computed } from "vue";
const props = defineProps<{ model: SurveySimulatorModel }>();
useBase(() => props.model);
const simulatorFrame = computed(() => props.model.simulatorFrame);
const activateZoom = () => {
  if (props.model.device !== "desktop") {
    props.model.activateZoom();
  }
};
const deactivateZoom = () => {
  if (props.model.device !== "desktop") {
    props.model.deactivateZoom();
  }
};
</script>

// packages/survey-creator-angular/src/tabs/preview/simulator.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { SurveySimulatorModel } from "survey-creator-core";

@Component({
  selector: "survey-simulator",
  templateUrl: "./simulator.component.html",
  styles: [":host { display: none; }"]
})
export class SimulatorComponent extends BaseAngular<SurveySimulatorModel> {
  @Input() model!: SurveySimulatorModel;
  private layoutRafId = 0;
  protected getModel(): SurveySimulatorModel {
    return this.model;
  }
  public get simulatorFrame(): any {
    return this.model.simulatorFrame;
  }
  public get simulatorShellStyle(): { [key: string]: string } | null {
    const h = this.model.popupOverlayHeight;
    return h ? { "--sv-popup-overlay-height": h } : null;
  }
  activateZoom() {
    if (this.model.device !== "desktop") {
      this.model.activateZoom();
    }
  }
  deactivateZoom() {
    if (this.model.device !== "desktop") {
      this.model.deactivateZoom();
    }
  }
  public override ngAfterViewChecked(): void {
    super.ngAfterViewChecked();
    const win = typeof window !== "undefined" ? window : undefined;
    const raf = win?.requestAnimationFrame?.bind(win);
    const caf = win?.cancelAnimationFrame?.bind(win);
    if (!raf) {
      this.model.survey?.forceProcessResponsiveness();
      return;
    }
    if (this.layoutRafId && caf) {
      caf(this.layoutRafId);
    }
    this.layoutRafId = raf(() => {
      this.layoutRafId = 0;
      this.model?.survey?.forceProcessResponsiveness();
    });
  }
}
<ng-template #template>
  <div [class]="model.getRootCss()" (keydown)="model.tryToZoom($event, $event)" (mouseover)="activateZoom()"
    (mouseout)="deactivateZoom()">
    <div *ngIf="model.hasFrame" class="svd-simulator-wrapper" id="svd-simulator-wrapper"
      [style.width]="simulatorFrame.frameWidth + 'px'" [style.height]="simulatorFrame.frameHeight + 'px'">
      <div class="svd-simulator" [style.width]="simulatorFrame.deviceWidth + 'px'"
        [style.height]="simulatorFrame.deviceHeight + 'px'"
        [style.transform]="'scale(' + simulatorFrame.scale + ') translate(-50%, -50%)'">
        <div class="svd-simulator-content" [ngStyle]="simulatorShellStyle">
          <ng-template [component]="{ name: 'survey-widget', data: { model: model.survey } }"></ng-template>
        </div>
      </div>
    </div>
    <div *ngIf="!model.hasFrame" class="svd-simulator-content" [ngStyle]="simulatorShellStyle">
      <ng-template [component]="{ name: 'survey-widget', data: { model: model.survey } }"></ng-template>
    </div>
  </div>
</ng-template>
