// packages/survey-creator-vue/src/tabs/preview/SurveyResultsRow.vue
<template>
  <tr @click="model.toggle" v-key2click>
    <td
      class="svd-dark-border-color"
      :style="{ paddingLeft: model.textMargin }"
    >
      <span
        v-if="model.isNode"
        class="svd-test-results__marker"
        :class="{ 'svd-test-results__marker--expanded': !model.collapsed }"
        :style="{ left: model.markerMargin }"
      >
        <sv-svg-icon :iconName="'icon-expand_16x16'" :size="16"></sv-svg-icon>
      </span>
      <span>{{ model.title }}</span>
    </td>
    <td
      :class="{
        'svd-test-results__node-value': model.isNode,
        'svd-dark-border-color': !model.isNode,
      }"
    >
      {{ model.getString(model.displayValue) }}
    </td>
  </tr>
  <template v-if="model.isNode && !model.collapsed">
    <survey-results-table-row
      v-for="(row, index) in model.data"
      :model="row"
      :key="index + 1"
    ></survey-results-table-row>
  </template>
</template>

<script lang="ts" setup>
import type { SurveyResultsItemModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ model: SurveyResultsItemModel }>();
useBase(() => props.model);
</script>

// packages/survey-creator-angular/src/tabs/preview/survey-results-row.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "survey-angular-ui";
import { Action } from "survey-core";
import { SurveyResultsItemModel } from "survey-creator-core";

@Component({
  selector: "survey-results-table-row",
  templateUrl: "./survey-results-row.component.html",
  styles: [":host { display: none; }"]
})
export class SurveyResultsTableRowComponent extends BaseAngular<SurveyResultsItemModel> {
  @Input() model!: SurveyResultsItemModel;
  protected getModel(): SurveyResultsItemModel {
    return this.model;
  }
}
<ng-template #template>
  <tr (click)="model.toggle()" [key2click]>
    <td class="svd-dark-border-color"
        [style.paddingLeft]="model.textMargin ">
        <span *ngIf="model.isNode" class="svd-test-results__marker"
              [class.svd-test-results__marker--expanded]="!model.collapsed"
                         [style.left]="model.markerMargin">
            <svg [iconName]="'icon-expand_16x16'" [size]="16" sv-ng-svg-icon></svg>
        </span>
        <span >{{model.title}}</span></td>
    <td [class.svd-test-results__node-value]="model.isNode" [class.svd-dark-border-color]="!model.isNode">
      {{model.getString(model.displayValue)}}
    </td>
  <ng-container *ngIf="model.isNode && !model.collapsed">
    <ng-container *ngFor="let row of model.data">
      <survey-results-table-row [model]="row"></survey-results-table-row>
    </ng-container>
  </ng-container>
</ng-template>
