// packages/survey-creator-vue/src/toolbox/AdaptiveToolbox.vue
<template>
  <div :class="toolbox.classNames" ref="root">
    <div @focusout="(e) => toolbox.focusOut(e)" class="svc-toolbox__panel">
      <div v-if="toolbox.showSearch" class="svc-toolbox__search-container">
        <template v-if="toolbox.isCompactRendered">
          <SvComponent
            :is="'svc-toolbox-tool'"
            :creator="creator"
            key="searchitem"
            :item="toolbox.searchItem"
            :parentModel="toolbox"
            :isCompact="toolbox.isCompactRendered"
          ></SvComponent>
        </template>
        <SvComponent
            :is="'svc-search'"
            :model="toolbox.searchManager"
        ></SvComponent>
        <div
            class="svc-toolbox__category-separator svc-toolbox__category-separator--search"
          ></div>
      </div>
      <div @focusout="(e) => toolbox.focusOut(e)" class="svc-toolbox__scroll-wrapper">
        <div
          class="svc-toolbox__scroller sv-drag-target-skipped"
          @scroll="
            (e) => {
              toolbox.onScroll(toolbox, e);
            }
          "
        >
          <div v-if="toolbox.showPlaceholder" class="svc-toolbox__placeholder">
            {{ toolbox.toolboxNoResultsFound }}
          </div>
          <div class="svc-toolbox__container">
            <template v-if="!toolbox.showInSingleCategory">
              <SvComponent
                :is="'svc-toolbox-category'"
                v-for="(category, index) in toolbox.categories"
                :key="index"
                :category="category"
                :toolbox="toolbox"
              ></SvComponent>
            </template>
            <template v-if="toolbox.showInSingleCategory">
              <div class="svc-toolbox__category">
                <template v-for="(item, index) in renderedActions" :key="index">
                  <SvComponent
                    :is="'svc-toolbox-tool'"
                    :creator="creator"
                    :item="item"
                    :parentModel="toolbox"
                    :isCompact="toolbox.isCompactRendered"
                  ></SvComponent>
                </template>
              </div>
            </template>
          </div>
        </div>
        <div class="svc-toolbox__scrollbar" @scroll="
            (e) => {
              toolbox.onScrollbarScroll(e);
            }
          ">
          <div class="svc-toolbox__scrollbar-sizer">
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import { VerticalResponsivityManager } from "survey-core";
import type { SurveyCreatorModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { computed, onMounted, onUnmounted, ref } from "vue";
const props = defineProps<{ creator: SurveyCreatorModel }>();
const toolbox = computed(() => {
  return props.creator.toolbox;
});

const root = ref<HTMLDivElement>();

useBase(() => toolbox.value);
let responsivityManager: VerticalResponsivityManager;
onMounted(() => {
  toolbox.value.setRootElement(root.value as HTMLDivElement);
  responsivityManager = new VerticalResponsivityManager(
    toolbox.value.containerElement as HTMLDivElement,
    toolbox.value,
    toolbox.value.itemSelector
  );
});
onUnmounted(() => {
  responsivityManager?.dispose();
  toolbox.value.setRootElement(undefined as any);
  toolbox.value.unsubscribeRootElement();
});
const renderedActions = computed(() => toolbox.value.renderedActions);
</script>

// packages/survey-creator-angular/src/toolbox/adaptive-toolbox.component.ts
import { AfterViewInit, Component, ElementRef, Input, ViewChild } from "@angular/core";
import { SurveyCreatorModel, QuestionToolbox } from "survey-creator-core";
import { Action, VerticalResponsivityManager } from "survey-core";
import { BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-adaptive-toolbox",
  templateUrl: "./adaptive-toolbox.component.html",
  styles: [":host { display: none; }"]
})
export class AdaptiveToolboxComponent extends BaseAngular<QuestionToolbox> implements AfterViewInit {
  @Input() creator!: SurveyCreatorModel;
  @ViewChild("container") container!: ElementRef<HTMLElement>;
  private responsivityManager: VerticalResponsivityManager | undefined;
  public get model() {
    return this.creator.toolbox;
  }
  public get searchItem() {
    return this.model.searchItem as Action;
  }
  ngAfterViewInit() {
    this.model.setRootElement(this.container.nativeElement as HTMLDivElement);
    this.responsivityManager =
      new VerticalResponsivityManager(this.model.containerElement as HTMLDivElement,
        this.model, this.model.itemSelector);
  }
  protected getModel(): QuestionToolbox {
    return this.model;
  }
  override ngOnDestroy(): void {
    this.responsivityManager?.dispose();
    this.model.unsubscribeRootElement();
    super.ngOnDestroy();
  }
}

<ng-template #template>
  <div [class]="model.classNames" #container>
    <div (focusout)="model.focusOut($event)" class="svc-toolbox__panel">
      <div *ngIf="model.showSearch" class="svc-toolbox__search-container">
        <ng-container *ngIf="model.isCompactRendered">
          <svc-toolbox-tool [creator]="creator" [item]="searchItem" [parentModel]="model"
            [isCompact]="model.isCompactRendered"></svc-toolbox-tool>
          <div class="svc-toolbox__category-separator svc-toolbox__category-separator--search"></div>
        </ng-container>
        <svc-search [model]="model.searchManager"></svc-search>
      </div>
      <div class="svc-toolbox__scroll-wrapper">
        <div class="svc-toolbox__scroller sv-drag-target-skipped" (scroll)="model.onScroll(model, $event)">
          <div *ngIf="model.showPlaceholder" class="svc-toolbox__placeholder">{{model.toolboxNoResultsFound}}</div>
          <div class="svc-toolbox__container">
            <ng-container *ngIf="!model.showInSingleCategory">
              <svc-toolbox-category *ngFor="let category of model.categories" [category]="category"
                [toolbox]="model"></svc-toolbox-category>
            </ng-container>
            <ng-container *ngIf="model.showInSingleCategory">
              <div class="svc-toolbox__category">
                <ng-container *ngFor="let item of model.renderedActions">
                  <svc-toolbox-tool [creator]="creator" [item]="item" [parentModel]="model"
                    [isCompact]="model.isCompactRendered"></svc-toolbox-tool>
                </ng-container>
              </div>
            </ng-container>
          </div>
        </div>
        <div class="svc-toolbox__scrollbar" (scroll)="model.onScrollbarScroll($event)">
          <div class="svc-toolbox__scrollbar-sizer">
          </div>
        </div>
      </div>
    </div>
  </div>
</ng-template>
