// packages/survey-creator-vue/src/tabbed-menu/TabbedMenuItemWrapper.vue
<template>
  <span
    class="svc-tabbed-menu-item-container"
    :class="[!item.isVisible ? 'sv-action--hidden' : '', item.css]"
  >
    <div class="sv-action__content">
      <SvComponent
        :name="item.component || 'svc-tabbed-menu-item'"
        :item="item"
      ></SvComponent>
    </div>
  </span>
</template>
<script setup lang="ts">
 import { SvComponent } from "survey-vue3-ui";
import type { TabbedMenuItem } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ item: TabbedMenuItem }>();
useBase(() => props.item);
</script>

// packages/survey-creator-angular/src/tabbed-menu/tabbed-menu/tabbed-menu-item-wrapper.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "survey-angular-ui";
import { TabbedMenuItem } from "survey-creator-core";

@Component({
  selector: "svc-tabbed-menu-item-wrapper",
  templateUrl: "./tabbed-menu-item-wrapper.component.html",
  styles: [":host { display: none; }"]
})
export class TabbedMenuItemWrapperComponent extends BaseAngular<TabbedMenuItem> {
  @Input() model!: TabbedMenuItem;
  protected getModel(): TabbedMenuItem {
    return this.model;
  }
}
<ng-template #template>
  <span class="svc-tabbed-menu-item-container" [class.svc-tabbed-menu-item-container--hidden]="!model.isVisible" [class]="model.css"
    #container>
    <div class="svc-tabbed-menu-item-container__content">
      <ng-template [component]="{ name: model.component || 'svc-tabbed-menu-item', data: { model } }"></ng-template>
    </div>
  </span>
</ng-template>
