// packages/survey-creator-angular/src/creator.component.ts
import { ChangeDetectorRef, Component, Input } from "@angular/core";
import { BaseAngular } from "survey-angular-ui";
import { CreatorBase } from "survey-creator-core";

@Component({
  selector: "svc-creator",
  templateUrl: "./creator.component.html",
  styleUrls: []
})
export class CreatorComponent extends BaseAngular<CreatorBase> {
  @Input() model!: CreatorBase;

  constructor(changeDetectorRef: ChangeDetectorRef) {
    super(changeDetectorRef);
    changeDetectorRef.detach();
  }
  protected getModel(): CreatorBase {
    return this.model;
  }
  public get creator(): CreatorBase {
    return this.model;
  }
  protected override onModelChanged(): void {
    this.changeDetectorRef.detectChanges();
  }
}
<ng-container *ngIf="!creator.isCreatorDisposed">
  <div class="svc-creator" [class.svc-creator--mobile]="creator.isMobileView">
    <div>
      <!-- ko component: { name: 'svc-svg-bundle'} -->
      <!-- /ko -->
    </div>
    <div class="svc-full-container svc-creator__area svc-flex-column"
      [class.svc-creator__area--with-banner]="!creator.haveCommercialLicense">
      <div class="svc-flex-row svc-full-container"
        [class.svc-creator__side-bar--left]="creator.sidebarLocation == 'left'">
        <div class="svc-flex-column svc-flex-row__element svc-flex-row__element--growing">
          <div class="svc-top-bar">
            <div class="svc-tabbed-menu-wrapper" [visible]="creator.showTabs">
              <span>TODO TABBED MENU</span>
              <!-- ko component: { name: 'svc-tabbed-menu', params: { model: creator.tabbedMenu } } -->
              <!-- /ko -->
            </div>
            <div *ngIf="creator.showToolbar" class="svc-toolbar-wrapper" [visible]="creator.showToolbar">
              <sv-action-bar [model]="creator.toolbar"></sv-action-bar>
            </div>
          </div>
          <div class="svc-creator__content-wrapper svc-flex-row"
            [class.svc-creator__content-wrapper--footer-toolbar]="creator.isMobileView">
            <div class="svc-creator__content-holder svc-flex-column">
              <ng-container *ngFor="let tab of creator.tabs">
                <div class="svc-creator-tab" *ngIf="creator.viewType == tab.id && tab.visible"
                  [attr.id]="'scrollableDiv-' + tab.id" [class.svc-creator__toolbox--right]="creator.toolboxLocation == 'right'">
                  <ng-template [component]="{ name: tab.componentContent, data: { model: tab.data.model } }"></ng-template>
                </div>
              </ng-container>
            </div>
          </div>
          <div *ngIf="creator.isMobileView" class="svc-footer-bar">
            <div class="svc-toolbar-wrapper" [visible]="creator.isMobileView">
              <sv-action-bar [model: creator.footerToolbar]></sv-action-bar>
            </div>
          </div>
        </div>
        <div *ngIf="creator.sidebar" [class.sv-mobile-side-bar]="creator.isMobileView">
          <span>TODO implement sidebar</span>
          <!-- <svc-side-bar params="model: creator.sidebar"> </svc-side-bar> -->
        </div>
      </div>
      <div class="svc-creator__banner" *ngIf="!creator.haveCommercialLicense">
        <span class="svc-creator__non-commercial-text">
          <a href="https://surveyjs.io/buy">
            {{creator.licenseText}}
          </a>
        </span>
      </div>
      <!-- ko component: { name: 'svc-notifier', params: { creator: creator, notifier: creator.notifier } } -->
      <!-- /ko -->
    </div>
  </div>
</ng-container>

// packages/survey-creator-vue/src/Creator.vue
<template>
  <template v-if="!model.isCreatorDisposed">
    <survey-popup-modal></survey-popup-modal>
    <div
      class="svc-creator"
      :class="{
        'svc-creator--mobile': model.isMobileView,
      }"
      ref="root"
    >
      <div>
        <sv-svg-bundle></sv-svg-bundle>
      </div>
      <div
        class="svc-full-container svc-creator__area svc-flex-column"
        :class="{
          'svc-creator__area--with-banner': !model.haveCommercialLicense,
        }"
      >
        <div
          class="svc-flex-row svc-full-container"
          :class="{
            'svc-creator__side-bar--left': model.sidebarLocation == 'left',
          }"
        >
          <div
            class="svc-flex-column svc-flex-row__element svc-flex-row__element--growing"
          >
            <div class="svc-top-bar">
              <div class="svc-tabbed-menu-wrapper" v-show="model.showTabs">
                <svc-tabbed-menu :model="model.tabbedMenu"></svc-tabbed-menu>
              </div>
              <div
                v-if="model.showToolbar"
                class="svc-toolbar-wrapper"
                :v-show="model.showToolbar"
              >
                <sv-action-bar :model="model.toolbar"></sv-action-bar>
              </div>
            </div>
            <div
              class="svc-creator__content-wrapper svc-flex-row"
              :class="{
                'svc-creator__content-wrapper--footer-toolbar':
                  model.isMobileView,
              }"
            >
              <div class="svc-creator__content-holder svc-flex-column">
                <template v-for="tab in model.tabs">
                  <div
                    class="svc-creator-tab"
                    v-bind:key="tab.id"
                    v-if="model.viewType == tab.id && tab.visible"
                    :id="'scrollableDiv-' + tab.id"
                    :class="{
                      'svc-creator__toolbox--right':
                        model.toolboxLocation == 'right',
                    }"
                  >
                    <component
                      :is="tab.componentContent"
                      :model="tab.data.model"
                    ></component>
                  </div>
                </template>
              </div>
            </div>
            <div v-if="model.isMobileView" class="svc-footer-bar">
              <div class="svc-toolbar-wrapper" :v-show="model.isMobileView">
                <sv-action-bar :model="model.footerToolbar"></sv-action-bar>
              </div>
            </div>
          </div>
          <div
            v-if="model.sidebar"
            :class="{ 'sv-mobile-side-bar': model.isMobileView }"
          >
            <svc-side-bar :model="model.sidebar"></svc-side-bar>
          </div>
        </div>
        <div class="svc-creator__banner" v-if="!model.haveCommercialLicense">
          <span class="svc-creator__non-commercial-text">
            <a href="https://surveyjs.io/buy">
              {{ model.licenseText }}
            </a>
          </span>
        </div>
        <sv-notifier :model="model.notifier"></sv-notifier>
      </div>
    </div>
  </template>
</template>
<script setup lang="ts">
import type { CreatorBase } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { computed, onMounted, onUnmounted, ref, toRaw } from "vue";
const props = defineProps<{ model: CreatorBase }>();
const model = computed(() => {
  return toRaw(props.model);
});
const root = ref<HTMLDivElement>();
useBase(() => model.value);
onMounted(() => {
  if (root.value) {
    props.model.setRootElement(root.value);
  }
});
onUnmounted(() => {
  props.model.unsubscribeRootElement();
});
</script>
