// packages/survey-creator-angular/src/question-editor.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, EmbeddedViewContentComponent } from "survey-angular-ui";
import { Question, SurveyModel } from "survey-core";

@Component({
  selector: "svc-question-editor-content",
  templateUrl: "./question-editor.component.html"
})
export class QuestionEditorComponent extends EmbeddedViewContentComponent {
  @Input() survey!: SurveyModel
  get question(): Question {
    return this.survey.getAllQuestions()[0];
  }
  protected get elementComponentName(): string {
    return this.question.isPanel ? "panel" : "question";
  }
  public get componentName(): string {
    const survey = this.survey;
    if (!!survey) {
      const name = survey.getElementWrapperComponentName(this.question);
      if (!!name) {
        return name;
      }
    }
    return this.elementComponentName;
  }
  public get componentData(): any {
    const survey = this.survey as SurveyModel;
    let data: any;
    if (!!survey) {
      data = survey.getElementWrapperComponentData(this.question);
    }
    return {
      componentName: this.elementComponentName,
      componentData: {
        model: this.question,
        data: data
      }
    };
  }
}

AngularComponentFactory.Instance.registerComponent("svc-question-editor-content", QuestionEditorComponent);
<ng-template #template>
  <div [style]="style">
    <ng-template [component]="{ name: componentName, data: componentData }"></ng-template>
  </div>
</ng-template>

// packages/survey-creator-vue/src/QuestionEditor.vue
<template>
  <component :is="componentName" v-bind="componentData"></component>
</template>
<script lang="ts" setup>
import type { SurveyModel } from "survey-core";
import { computed } from "vue";

const props = defineProps<{ survey: SurveyModel }>();

const question = computed(() => props.survey?.getAllQuestions()[0]);

const componentName = computed(() => {
  const survey = props.survey;
  if (survey && question.value) {
    const name = survey.getElementWrapperComponentName(question.value);
    if (name) {
      return name;
    }
  }
  return "survey-question";
});
const componentData = computed(() => {
  const survey = props.survey;
  let data: any;
  if (survey && question.value) {
    data = survey.getElementWrapperComponentData(question.value);
  }
  return {
    componentName: "survey-question",
    componentData: {
      element: question.value,
      data: data,
    },
  };
});
</script>
