// packages/survey-creator-react/src/side-bar/ObjectSelector.tsx
import * as React from "react";
import { ObjectSelectorModel } from "survey-creator-core";
import { Base } from "survey-core";
import { ReactElementFactory, SurveyElementBase, List } from "survey-react-ui";

interface IObjectSelectorComponentProps {
  model: ObjectSelectorModel;
}
class ObjectSelectorComponent extends SurveyElementBase<IObjectSelectorComponentProps, any> {
  protected get model(): ObjectSelectorModel {
    return this.props.model;
  }
  protected getStateElement(): Base {
    return this.model;
  }
  renderElement(): React.JSX.Element {
    if (!this.model.isVisible) return null;

    return (<List model={this.model.list}></List>);
  }
}

ReactElementFactory.Instance.registerElement("svc-object-selector", (props) => {
  return React.createElement(
    ObjectSelectorComponent,
    props as IObjectSelectorComponentProps
  );
});

// packages/survey-creator-angular/src/property-panel/object-selector.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { ObjectSelectorModel, SidebarTabModel } from "survey-creator-core";

@Component({
  selector: "svc-object-selector",
  templateUrl: "./object-selector.component.html",
  styles: [":host { display: none; }"]
})
export class ObjectSelectorComponent extends BaseAngular<ObjectSelectorModel> {
  @Input() model!: ObjectSelectorModel;
  protected getModel(): ObjectSelectorModel {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-object-selector", ObjectSelectorComponent);
<ng-template #template>
    <div class="svc-object-selector" *ngIf="model.isVisible">
        <sv-ng-list [model]="model.list"></sv-ng-list>
    </div>
</ng-template>
