// packages/survey-creator-vue/src/side-bar/PropertyGrid.vue
<template>
  <div
    class="spg-container"
    :class="{ 'spg-container_search': model.searchEnabled }"
  >
    <SvComponent :is="'svc-search'" :model="model.searchManager"></SvComponent>
    <SurveyComponent
      v-if="!!model.survey"
      :survey="model.survey"
    ></SurveyComponent>
  </div>
</template>
<script lang="ts" setup>
import { SurveyComponent, SvComponent } from "survey-vue3-ui";
import type { PropertyGridViewModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ model: PropertyGridViewModel }>();
useBase(() => props.model);
</script>

// packages/survey-creator-angular/src/property-panel/property-grid.component.ts
import { PropertyGridViewModel } from "survey-creator-core";
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular, ButtonGroupQuestionComponent } from "survey-angular-ui";

@Component({
  selector: "svc-property-grid",
  templateUrl: "./property-grid.component.html",
  styles: [":host { display: none; }"]
})
export class PropertyGridComponent extends BaseAngular<PropertyGridViewModel> {
  @Input() model!: PropertyGridViewModel;
  protected getModel(): PropertyGridViewModel {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("buttongroup-question", ButtonGroupQuestionComponent);
AngularComponentFactory.Instance.registerComponent("svc-property-grid", PropertyGridComponent);
<ng-template #template>
    <div class="spg-container" [class.spg-container_search]="model.searchEnabled">
        <svc-search [model]="model.searchManager"></svc-search>
        <survey-content *ngIf="!!model.survey" [model]="model.survey"></survey-content>
    </div>
</ng-template>
