// packages/survey-creator-vue/src/tabs/theme/Theme.vue
<template>
  <div
    class="svc-creator-tab__content svc-test-tab__content"
    :class="{
      'svc-creator-tab__content--with-toolbar': model.isPageToolbarVisible,
    }"
  >
    <div v-if="model.survey.isEmpty" class="svc-test-tab--empty">
      <SurfacePlaceholder :name="'theme'" :placeholderTitleText="model.placeholderTitleText" :placeholderDescriptionText="model.placeholderDescriptionText" />
    </div>
    <div v-if="!model.survey.isEmpty" class="svc-plugin-tab__content">
      <SvComponent
        :is="'survey-simulator'"
        :model="model.simulator"
      ></SvComponent>
      <SvComponent
        :is="'survey-results'"
        v-if="model.showResults"
        :survey="model.survey"
      ></SvComponent>
    </div>
    <div
      v-if="model.isPageToolbarVisible"
      class="svc-plugin-tab__content-actions svc-test-tab__content-actions"
    >
      <SvComponent :is="'sv-action-bar'" :model="model.pages"></SvComponent>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import type { ThemeTabViewModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import SurfacePlaceholder from "../../components/SurfacePlaceholder.vue";
const props = defineProps<{ model: ThemeTabViewModel }>();
useBase(() => props.model);
</script>

// packages/survey-creator-angular/src/tabs/theme/theme.component.ts
import { ThemeTabViewModel } from "survey-creator-core";
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-tab-theme",
  templateUrl: "./theme.component.html",
  styles: [":host { display: none; }"]
})
export class ThemeTabComponent extends BaseAngular<ThemeTabViewModel> {
  @Input() model!: ThemeTabViewModel;
  protected getModel(): ThemeTabViewModel {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-tab-theme", ThemeTabComponent);

<ng-template #template>
  <div class="svc-creator-tab__content svc-test-tab__content"
    [class.svc-creator-tab__content--with-toolbar]="model.isPageToolbarVisible">
    <div *ngIf="model.survey.isEmpty" class="svc-test-tab--empty">
      <svc-surface-placeholder [name]="'theme'" [placeholderTitleText]="model.placeholderTitleText"
        [placeholderDescriptionText]="model.placeholderDescriptionText">
      </svc-surface-placeholder>
    </div>
    <div *ngIf="!model.survey.isEmpty" class="svc-plugin-tab__content">
      <survey-simulator [model]="model.simulator"></survey-simulator>
      <ng-container *ngIf="model.showResults">
        <survey-results [survey]="model.survey"></survey-results>
      </ng-container>
    </div>
    <div *ngIf="model.isPageToolbarVisible" class="svc-plugin-tab__content-actions svc-test-tab__content-actions">
      <sv-action-bar [model]="model.pages"></sv-action-bar>
    </div>
  </div>
</ng-template>
