// packages/survey-creator-angular/src/tabs/json/json-editor-ace.component.ts

import { AceJsonEditorModel, TabJsonEditorAcePlugin } from "survey-creator-core";
import { AfterViewInit, Component, ElementRef, Input, OnInit, ViewChild } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-tab-json-editor-ace",
  templateUrl: "./json-editor-ace.component.html",
  styles: [":host { display: none; }"]
})
export class AceJsonEditorComponent extends BaseAngular<AceJsonEditorModel> implements AfterViewInit {
  @Input() model!: AceJsonEditorModel;
  @ViewChild("inputEl") inputEl!: ElementRef<HTMLElement>;
  protected getModel(): AceJsonEditorModel {
    return this.model;
  }

  public ngAfterViewInit(): void {
    //todo fix ts 
    this.model.init((<any>window).ace.edit(
      this.inputEl.nativeElement
    ));
  }
}
AngularComponentFactory.Instance.registerComponent("svc-tab-json-editor-ace", AceJsonEditorComponent);
<ng-template #template>
    <div class="svc-creator-tab__content">
        <div class="svc-json-editor-tab__content">
            <div class="svc-json-editor-tab__ace-editor" #inputEl></div>
            <div className="svc-json-editor-tab__errros_list" [visible]="model.hasErrors">
                <sv-ng-list [model]="model.errorList"></sv-ng-list>
            </div>
        </div>
    </div>
</ng-template>

// packages/survey-creator-vue/src/tabs/json/JsonEditorAce.vue
<template>
  <div class="svc-creator-tab__content">
    <div class="svc-json-editor-tab__content">
      <div class="svc-json-editor-tab__ace-editor" ref="inputEl"></div>
      <div class="svc-json-editor-tab__errros_list" v-show="model.hasErrors">
        <sv-list :model="model.errorList"></sv-list>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import type { AceJsonEditorModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { onMounted, ref } from "vue";
const props = defineProps<{ model: AceJsonEditorModel }>();
const inputEl = ref<HTMLTextAreaElement>();
useBase(() => props.model);
onMounted(() => props.model.init((window as any).ace.edit(inputEl.value)));
</script>
