// packages/survey-creator-angular/src/tabs/json/json-editor-textarea.component.ts
import { TabJsonEditorTextareaPlugin, TextareaJsonEditorModel } from "survey-creator-core";
import { Component, ElementRef, Input, OnInit, ViewChild } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-tab-json-editor-textarea",
  templateUrl: "./json-editor-textarea.component.html",
  styles: [":host { display: none; }"]
})
export class TextareaJsonEditorComponent extends BaseAngular<TextareaJsonEditorModel> implements OnInit {
  @Input() model!: TextareaJsonEditorModel;
  @ViewChild("inputEl") inputEl!: ElementRef<HTMLTextAreaElement>;
  protected getModel(): TextareaJsonEditorModel {
    return this.model;
  }
  public override ngOnInit(): void {
    this.model.canShowErrors = false;
    super.ngOnInit();
  }
  public ngAfterViewInit() {
    this.model.textElement = this.inputEl.nativeElement;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-tab-json-editor-textarea", TextareaJsonEditorComponent);
<ng-template #template>
  <div class="svc-creator-tab__content">
    <div class="svc-json-editor-tab__content">
      <textarea class="svc-json-editor-tab__content-area" [attr.aria-label]="model.ariaLabel"
        [disabled]="model.readOnly" [(ngModel)]="model.text" (keydown)="model.checkKey(model, $event)" #inputEl>
      </textarea>
      <div class="svc-json-editor-tab__errros_list" [visible]="model.hasErrors">
        <sv-ng-list [model]="model.errorList"></sv-ng-list>
      </div>
    </div>
  </div>
</ng-template>

// packages/survey-creator-vue/src/tabs/json/JsonEditorTextArea.vue
<template>
  <div class="svc-creator-tab__content">
    <div class="svc-json-editor-tab__content">
      <textarea
        class="svc-json-editor-tab__content-area"
        :aria-label="model.ariaLabel"
        :disabled="model.readOnly"
        v-model="model.text"
        @keydown="model.checkKey(model, $event)"
        ref="inputEl"
      >
      </textarea>
      <div class="svc-json-editor-tab__errros_list" v-show="model.hasErrors">
        <sv-list :model="model.errorList"></sv-list>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import type { TextareaJsonEditorModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { ref, onMounted } from "vue";

const props = defineProps<{ model: TextareaJsonEditorModel }>();
const inputEl = ref<HTMLTextAreaElement>();
const model = props.model;
model.canShowErrors = false;
useBase(() => props.model);
onMounted(() => {
  const model = props.model;
  model.textElement = inputEl.value as HTMLTextAreaElement;
});
</script>
