// packages/survey-creator-vue/src/side-bar/SideBarPropertyGridHeader.vue
<template>
  <div class="svc-sidebar__header svc-sidebar__header--tabbed">
    <div
      class="svc-sidebar__header-container svc-sidebar__header-container--with-subtitle"
    >
      <div class="svc-sidebar__header-content" @click="model.action()">
        <div :class="model.buttonClassName">
          <div class="svc-sidebar__header-caption">
            <span class="svc-sidebar__header-title">{{ model.title }}</span>
            <span class="svc-sidebar__header-subtitle">{{
              model.tooltip
            }}</span>
          </div>
        </div>
        <SvComponent :is="'sv-popup'" :model="model.popupModel"></SvComponent>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { SvComponent, useBase } from "survey-vue3-ui";
import { MenuButton } from "survey-creator-core";
const props = defineProps<{ model: MenuButton }>();

useBase(() => props.model);
</script>

// packages/survey-creator-react/src/side-bar/SideBarPropertyGridHeader.tsx
import * as React from "react";
import { Base, getActionDropdownButtonTarget } from "survey-core";
import { SurveyElementBase, ReactElementFactory, Popup } from "survey-react-ui";
import { MenuButton } from "survey-creator-core";

interface ISideBarPropertyGridHeaderProps {
  model: MenuButton;
}

class SideBarPropertyGridHeader extends SurveyElementBase<ISideBarPropertyGridHeaderProps, any> {
  get objectSelectionAction(): MenuButton {
    return this.props.model;
  }

  protected getStateElement(): Base | null {
    return this.objectSelectionAction;
  }

  renderElement(): JSX.Element {
    return (
      <div className="svc-sidebar__header svc-sidebar__header--tabbed">
        <div className="svc-sidebar__header-container svc-sidebar__header-container--with-subtitle">
          <div className="svc-sidebar__header-content" onClick={() => this.objectSelectionAction.action()}>
            <div className={this.objectSelectionAction.buttonClassName}>
              <div className="svc-sidebar__header-caption">
                <span className="svc-sidebar__header-title">{this.objectSelectionAction.title}</span>
                <span className="svc-sidebar__header-subtitle">{this.objectSelectionAction.tooltip}</span>
              </div>
            </div>
            <Popup model={this.objectSelectionAction.popupModel}></Popup>
          </div>
        </div>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-side-bar-property-grid-header", (props) => {
  return React.createElement(SideBarPropertyGridHeader, props);
});
