// packages/survey-creator-vue/src/side-bar/SideBarHeader.vue
<template>
  <div class="svc-side-bar__container-header svc-sidebar__header-container">
    <div v-if="!model.subTitle" class="svc-side-bar__container-title">{{ model.title }}</div>
    <div v-if="!!model.subTitle" class="svc-sidebar__header-caption">
      <span class="svc-sidebar__header-title">{{ model.title }}</span>
      <span class="svc-sidebar__header-subtitle">{{ model.subTitle }}</span>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { SidebarHeaderModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ model: SidebarHeaderModel }>();
useBase(() => props.model);
</script>

<ng-template #template>
</ng-template>

// packages/survey-creator-react/src/side-bar/SideBarHeader.tsx
import * as React from "react";
import { Base } from "survey-core";
import { SidebarHeaderModel } from "survey-creator-core";
import { SurveyElementBase, ReactElementFactory } from "survey-react-ui";

interface ISideBarHeaderProps {
  model: SidebarHeaderModel;
}

class SideBarHeader extends SurveyElementBase<ISideBarHeaderProps, any> {
  get model(): SidebarHeaderModel {
    return this.props.model;
  }

  protected getStateElement(): Base | null {
    return this.model;
  }

  renderElement(): JSX.Element {
    return (
      <div className="svc-side-bar__container-header svc-sidebar__header-container">
        {(this.model.subTitle) ?
          <div className="svc-sidebar__header-caption">
            <span className="svc-sidebar__header-title">{this.model.title}</span>
            <span className="svc-sidebar__header-subtitle">{this.model.subTitle}</span>
          </div>
          : <div className="svc-side-bar__container-title">{this.model.title}</div>
        }
      </div>);
  }
}

ReactElementFactory.Instance.registerElement("svc-side-bar-header", (props) => {
  return React.createElement(SideBarHeader, props);
});
