// packages/survey-creator-angular/src/side-bar/side-bar-property-grid-header.component.ts

import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { getActionDropdownButtonTarget, Action } from "survey-core";

@Component({
  selector: "svc-side-bar-property-grid-header",
  templateUrl: "./side-bar-property-grid-header.component.html",
  styles: [":host { display: none; }"]
})
export class SidebarPropertyGridHeaderComponent extends BaseAngular<Action> {
  @Input() model!: Action;
  public getTarget: (container: HTMLElement) => HTMLElement = getActionDropdownButtonTarget;

  protected getModel(): Action {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-side-bar-property-grid-header", SidebarPropertyGridHeaderComponent);

<ng-template #template>
  <div class="svc-sidebar__header svc-sidebar__header--tabbed">
    <div class="svc-sidebar__header-container svc-sidebar__header-container--with-subtitle">
      <div class="svc-sidebar__header-content">
        <div [class]="model.getActionBarItemCss() + ' svc-sidebar__header-object-selector'" (click)="model.action()" [key2click]="{ processEsc: false }">
          <div class="svc-sidebar__header-caption">
            <span class="svc-sidebar__header-title">{{model.title}}</span>
            <span class="svc-sidebar__header-subtitle">{{model.tooltip}}</span>
          </div>
        </div>
        <sv-ng-popup [popupModel]="model.popupModel"></sv-ng-popup>
      </div>
    </div>
  </div>
</ng-template>

// packages/survey-creator-react/src/side-bar/SideBarPropertyGridHeader.tsx
import * as React from "react";
import { Action, Base, getActionDropdownButtonTarget } from "survey-core";
import { SurveyElementBase, ReactElementFactory, Popup, attachKey2click } from "survey-react-ui";

interface ISideBarPropertyGridHeaderProps {
  model: Action;
}

class SideBarPropertyGridHeader extends SurveyElementBase<ISideBarPropertyGridHeaderProps, any> {
  get objectSelectionAction(): Action {
    return this.props.model;
  }

  protected getStateElement(): Base | null {
    return this.objectSelectionAction;
  }

  renderElement(): React.JSX.Element {
    const button = attachKey2click(
      <div className={this.objectSelectionAction.getActionBarItemCss() + " svc-sidebar__header-object-selector"} onClick={() => this.objectSelectionAction.action()}>
        <div className="svc-sidebar__header-caption">
          <span className="svc-sidebar__header-title">{this.objectSelectionAction.title}</span>
          <span className="svc-sidebar__header-subtitle">{this.objectSelectionAction.tooltip}</span>
        </div>
      </div>, this.props.model
    );

    return (
      <div className="svc-sidebar__header svc-sidebar__header--tabbed">
        <div className="svc-sidebar__header-container svc-sidebar__header-container--with-subtitle">
          <div className="svc-sidebar__header-content">
            {button}
            <Popup model={this.objectSelectionAction.popupModel}></Popup>
          </div>
        </div>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-side-bar-property-grid-header", (props) => {
  return React.createElement(SideBarPropertyGridHeader, props);
});
