// packages/survey-creator-vue/src/side-bar/TabButton.vue
<template>
  <div class="svc-menu-action">
    <div
      :class="model.buttonClassName"
      :title="model.tooltip"
      @click="model.action()"
    >
      <div class="svc-menu-action__icon">
        <div class="svc-menu-action__icon-container">
          <SvComponent
            :is="'sv-svg-icon'"
            :iconName="model.iconName"
            :size="'auto'"
          ></SvComponent>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { MenuButton } from "survey-creator-core";
import { SvComponent, useBase } from "survey-vue3-ui";
const props = defineProps<{ model: MenuButton }>();

useBase(() => props.model);
</script>

// packages/survey-creator-react/src/side-bar/TabButton.tsx

import * as React from "react";
import { Base } from "survey-core";
import { SurveyElementBase, SvgIcon } from "survey-react-ui";
import { MenuButton } from "survey-creator-core";

export class TabButtonComponent extends SurveyElementBase<{ model: MenuButton }, any> {
  constructor(props: { model: MenuButton }) {
    super(props);
  }

  protected getStateElement(): Base {
    return this.props.model;
  }

  protected renderElement(): JSX.Element | null {
    return (
      <div className="svc-menu-action">
        <div
          className={this.props.model.buttonClassName}
          title={this.props.model.tooltip}
          onClick={() => { this.props.model.action(); }}
        >
          <div className="svc-menu-action__icon">
            <div className="svc-menu-action__icon-container">
              <SvgIcon iconName={this.props.model.iconName} size={"auto"}></SvgIcon>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
