// packages/survey-creator-vue/src/tabs/json/JsonEditorAce.vue
<template>
  <div class="svc-creator-tab__content">
    <div class="svc-json-editor-tab__content">
      <div class="svc-json-editor-tab__ace-editor" ref="inputEl"></div>
      <div class="svc-json-editor-tab__errros_list" v-show="model.hasErrors">
        <sv-list :model="model.errorList"></sv-list>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import type { AceJsonEditorModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { onMounted, ref } from "vue";
const props = defineProps<{ model: AceJsonEditorModel }>();
const inputEl = ref<HTMLTextAreaElement>();
useBase(() => props.model);
onMounted(() => props.model.init((window as any).ace.edit(inputEl.value)));
</script>

// packages/survey-creator-react/src/tabs/JsonEditorAce.tsx
import React from "react";
import { Base } from "survey-core";
import { ReactElementFactory, SurveyElementBase } from "survey-react-ui";
import { AceJsonEditorModel } from "survey-creator-core";

interface ITabJsonEditorAceComponentProps {
  data: AceJsonEditorModel;
}

export class TabJsonEditorAceComponent extends SurveyElementBase<
  ITabJsonEditorAceComponentProps,
  any
> {
  private aceEditorrRef: React.RefObject<HTMLDivElement>;
  constructor(props: ITabJsonEditorAceComponentProps) {
    super(props);
    this.aceEditorrRef = React.createRef();
  }
  protected getStateElement(): Base {
    return this.model;
  }
  private get model(): AceJsonEditorModel {
    return this.props.data;
  }
  componentDidMount() {
    this.model.init(ace.edit(this.aceEditorrRef.current as HTMLElement));
  }
  renderElement(): JSX.Element {
    return (
      <div className="svc-creator-tab__content">
        <div className="svc-json-editor-tab__content">
          <div
            className="svc-json-editor-tab__ace-editor"
            ref={this.aceEditorrRef}
          ></div>
        </div>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "svc-tab-json-editor-ace",
  (props: ITabJsonEditorAceComponentProps) => {
    return React.createElement(TabJsonEditorAceComponent, props);
  }
);
