// packages/survey-creator-react/src/ui-preset-editor/Presets.tsx
import * as React from "react";
import { ActionContainer, Base, SurveyModel } from "survey-core";
import {
  ReactElementFactory,
  Scroll,
  Survey,
  SurveyActionBar,
  SurveyElementBase,
} from "survey-react-ui";
import { SurveyCreatorModel } from "survey-creator-core";
interface ITabPresetsComponentProps {
  data: any;
  creator: SurveyCreatorModel;
}

export class TabPresetsComponent extends SurveyElementBase<ITabPresetsComponentProps, any> {
  private get navigationBar(): ActionContainer {
    return this.props.data.navigationBar;
  }
  private get model(): SurveyModel {
    return this.props.data.model;
  }
  protected get creator(): SurveyCreatorModel {
    return this.props.creator;
  }

  protected getStateElement(): Base {
    return this.model;
  }

  renderElement(): React.JSX.Element {
    const presetsTabClassName = "svc-tab-designer svc-tab-designer--presets";

    return (
      <React.Fragment>
        <div className="svc-flex-column">
          {this.creator.showToolbox ? ReactElementFactory.Instance.createElement("svc-toolbox", { model: this.creator }) : null}
        </div>
        <div className={presetsTabClassName}>
          <Scroll>
            <SurveyActionBar model={this.navigationBar}></SurveyActionBar>
            <Survey model={this.model} />
          </Scroll>
        </div>
      </React.Fragment>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-tab-presets", (props) => {
  return React.createElement(
    TabPresetsComponent,
    props as ITabPresetsComponentProps
  );
});

// packages/survey-creator-angular/ui-preset-editor/src/presets.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { SurveyCreatorModel } from "survey-creator-core";

@Component({
  selector: "svc-tab-presets",
  templateUrl: "./presets.component.html",
  styles: [":host { display: none; }"]
})
export class TabPresetsComponent extends BaseAngular<any> {
  @Input() model: any = undefined;
  public get survey() {
    return this.model.model;
  }
  public get navigationBar() {
    return this.model.navigationBar;
  }
  public get creator() {
    return this.model.creator;
  }
  protected getModel() {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-tab-presets", TabPresetsComponent);

<ng-template #template>
  <div class="svc-flex-column">
    <ng-template *ngIf="creator?.showToolbox" [component]="{ name: 'svc-toolbox', data: {model: creator} }">
    </ng-template>
  </div>
  <div class="svc-tab-designer svc-tab-designer--presets">
    <sv-scroll>
      <sv-action-bar [model]="navigationBar" [handleClick]="false"></sv-action-bar>
      <ng-template [component]="{ name: 'survey', data: {model: survey} }">
      </ng-template>
    </sv-scroll>
  </div>
</ng-template>
