// packages/survey-creator-angular/src/property-panel/search.component.ts
import { SearchManager, SearchManager } from "survey-creator-core";
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-search",
  templateUrl: "./search.component.html",
  styles: [":host { display: none; }"]
})
export class SearchComponent extends BaseAngular<SearchManager> {
  @Input() model!: SearchManager;
  protected getModel(): SearchManager {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-search", SearchComponent);
<ng-template #template>
    <div *ngIf="model.isVisible" class="spg-search-editor_container">
        <div class="spg-search-editor_search-icon">
            <svg [iconName]="'icon-search'" [size]="'auto'" sv-ng-svg-icon></svg>
        </div>
        <input type="text" class="spg-search-editor_input" [(ngModel)]="model.filterString"
            [attr.aria-label]="model.filterStringPlaceholder" [attr.placeholder]="model.filterStringPlaceholder" />
        <div class="spg-search-editor_toolbar">
            <div class="spg-search-editor_toolbar-counter">{{model.matchCounterText}}</div>
            <sv-action-bar [model]="model.searchActionBar"></sv-action-bar>
        </div>
    </div>
</ng-template>

// packages/survey-creator-vue/src/property-panel/Search.vue
<template>
  <div v-if="model.isVisible" class="spg-search-editor_container">
    <div class="spg-search-editor_search-icon">
      <sv-svg-icon :iconName="'icon-search'" :size="'auto'"></sv-svg-icon>
    </div>
    <input
      type="text"
      class="spg-search-editor_input"
      v-model="filterString"
      :aria-label="model.filterStringPlaceholder"
      :placeholder="model.filterStringPlaceholder"
    />
    <div class="spg-search-editor_toolbar">
      <div class="spg-search-editor_toolbar-counter">
        {{ model.matchCounterText }}
      </div>
      <sv-action-bar :model="model.searchActionBar"></sv-action-bar>
    </div>
  </div>
</template>
<script lang="ts" setup>
import type { SearchManager } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { computed } from "vue";
const props = defineProps<{ model: SearchManager }>();
useBase(() => props.model);
const filterString = computed({
  get: () => props.model.filterString,
  set: (val: string) => {
    const model = props.model;
    model.filterString = val;
  },
});
</script>
