// packages/survey-creator-angular/src/custom-questions/color.component.ts
import { Component } from "@angular/core";
import { AngularComponentFactory, QuestionAngular } from "survey-angular-ui";
import { QuestionColorModel } from "survey-creator-core";

@Component({
  templateUrl: "color.component.html",
  selector: "svc-color"
})

export class QuestionColorComponent extends QuestionAngular<QuestionColorModel> {

}
AngularComponentFactory.Instance.registerComponent("color-question", QuestionColorComponent)
<div [class]="model.cssClasses.root" (keydown)="model.onKeyDown($event)">
  <label [class]="model.getSwatchCss()" [style]="model.getSwatchStyle()">
    <svg [iconName]="model.cssClasses.swatchIcon" [size]="'auto'" sv-ng-svg-icon></svg>
    <input type="color" [disabled]="model.isInputReadOnly" [class]="model.cssClasses.colorInput"
      [value]="model.renderedColorValue" (change)="model.onColorInputChange($event)" tabindex="-1" />
  </label>
  <input autocomplete="off" [disabled]="model.isInputReadOnly" [attr.id]="model.inputId"
    [attr.placeholder]="model.renderedPlaceholder" [attr.aria-required]="model.ariaRequired"
    [attr.aria-label]="model.ariaLabel" [attr.aria-invalid]="model.ariaInvalid"
    [attr.aria-describedby]="model.ariaDescribedBy" (change)="model.onChange($event)" (keyup)="model.onKeyUp($event)"
    (blur)="model.onBlur($event)" (beforeinput)="model.onBeforeInput($event)" [value]="model.renderedValue"
    [class]="model.cssClasses.control" />
  <ng-container *ngIf="model.showDropdownAction">
    <sv-action-bar-item [model]="model.dropdownAction"></sv-action-bar-item>
    <sv-ng-popup [popupModel]="model.dropdownAction.popupModel"></sv-ng-popup>
  </ng-container>
</div>

// packages/survey-creator-vue/src/custom-questions/Color.vue
<template>
  <div :class="question.cssClasses.root" @keydown="question.onKeyDown">
    <label :class="question.getSwatchCss()" :style="question.getSwatchStyle()">
      <sv-svg-icon
        :iconName="question.cssClasses.swatchIcon"
        :size="'auto'"
      ></sv-svg-icon>
      <input
        type="color"
        :disabled="question.isInputReadOnly"
        :class="question.cssClasses.colorInput"
        :value="question.renderedColorValue"
        tabindex="-1"
        @change="question.onColorInputChange"
      />
    </label>
    <input
      autocomplete="off"
      :disabled="question.isInputReadOnly"
      :id="question.inputId"
      :placeholder="question.renderedPlaceholder"
      :aria-required="question.ariaRequired"
      :aria-label="question.ariaLabel"
      :aria-invalid="question.ariaInvalid"
      :aria-describedby="question.ariaDescribedBy"
      @change="question.onChange"
      @keyup="question.onKeyUp"
      @blur="question.onBlur"
      @beforeinput="question.onBeforeInput"
      :value="question.renderedValue"
      :class="question.cssClasses.control"
    />
    <template v-if="question.showDropdownAction">
      <sv-action-bar-item :item="question.dropdownAction"></sv-action-bar-item>
      <sv-popup :model="question.dropdownAction.popupModel"></sv-popup>
    </template>
  </div>
</template>

<script lang="ts" setup>
import type { QuestionColorModel } from "survey-creator-core";
import { useQuestion } from "survey-vue3-ui";
import { ref } from "vue";
const props = defineProps<{ question: QuestionColorModel }>();
useQuestion(props, ref());
</script>
