// packages/survey-creator-react/src/custom-questions/ColorItem.tsx
import * as React from "react";
import { ItemValue } from "survey-core";
import { ReactElementFactory, SurveyElementBase } from "survey-react-ui";

class ItemTemplateComponent extends SurveyElementBase<{ item: ItemValue }, any> {
  render() {
    const item = this.props.item;
    return (
      <>
        <span className="spg-color-editor__color-swatch" style={{ backgroundColor: item.value }}></span>
        <span key={2}>{this.renderLocString(item.locTitle, undefined, "locString")}</span>
      </>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "color-item",
  (props) => {
    return React.createElement(ItemTemplateComponent, props);
  }
);

// packages/survey-creator-vue/src/custom-questions/ColorItem.vue
<template>
  <span class="spg-color-editor__color-swatch" :style="getStyle()"></span>
  <survey-string :locString="item.locTitle"></survey-string>
</template>
<script setup lang="ts">
import type { ItemValue } from "survey-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ item: ItemValue }>();
useBase(() => props.item);
const getStyle = () => {
  return { backgroundColor: props.item.value };
};
</script>
