// packages/survey-creator-angular/src/custom-questions/file.component.ts
import { Component } from "@angular/core";
import { AngularComponentFactory, QuestionAngular } from "survey-angular-ui";
import { QuestionFileEditorModel } from "survey-creator-core";

@Component({
  selector: "svc-file-editor",
  templateUrl: "./file.component.html"
})
export class QuestionFileEditorComponent extends QuestionAngular<QuestionFileEditorModel> {
}

AngularComponentFactory.Instance.registerComponent("fileedit-question", QuestionFileEditorComponent)
<div [class]="model.cssClasses.root" (dragenter)="model.onDragEnter($event)" (dragover)="model.onDragOver($event)"
  (drop)="model.onDrop($event)" (dragleave)="model.onDragLeave($event)" (keydown)="model.onKeyDown($event)"
  #contentElement>
  <input type="text" [disabled]="model.isTextInputReadOnly" [class]="model.cssClasses.control"
    [value]="model.renderedValue ||''" (change)="model.onInputChange($event)" (blur)="model.onInputBlur($event)"
    [attr.placeholder]="model.renderedPlaceholder" />
  <input type="file" [disabled]="model.isInputReadOnly" [class]="model.cssClasses.fileInput" [attr.id]="model.inputId"
    [attr.aria-required]="model.ariaRequired" [attr.aria-label]="model.ariaLabel"
    [attr.aria-invalid]="model.ariaInvalid" [attr.aria-describedby]="model.ariaDescribedBy" [attr.multiple]="false"
    [title]="model.inputTitle" [accept]="model.acceptedTypes" (change)="model.onFileInputChange($event)" tabindex="-1">
  <div [class]="model.cssClasses.buttonsContainer">
    <button type="button" [class]="model.cssClasses.clearButton" [disabled]="model.getIsClearButtonDisabled()"
      (click)="model.doClean()" [key2click] [title]="model.clearButtonCaption">
      <svg [iconName]="model.cssClasses.clearButtonIcon" size="'auto'" sv-ng-svg-icon></svg>
    </button>
    <label [class]="model.getChooseButtonCss()" [attr.for]="model.inputId" [attr.aria-label]="model.chooseButtonCaption"
      (click)="model.chooseFiles($event)" [key2click]>
      <svg [iconName]="model.cssClasses.chooseButtonIcon" size="'auto'" [title]="model.chooseButtonCaption"
        sv-ng-svg-icon></svg>
      <span class="sv-visuallyhidden">{{ model.chooseButtonCaption }}</span>
    </label>
  </div>
</div>

// packages/survey-creator-vue/src/custom-questions/File.vue
<template>
  <div
    :class="question.cssClasses.root"
    @dragenter="question.onDragEnter"
    @dragover="question.onDragOver"
    @drop="question.onDrop"
    @dragleave="question.onDragLeave"
    @keydown="question.onKeyDown"
    ref="root"
  >
    <input
      type="text"
      :disabled="question.isTextInputReadOnly"
      :class="question.cssClasses.control"
      :value="question.renderedValue || ''"
      @change="question.onInputChange"
      @blur="question.onInputBlur"
      :placeholder="question.renderedPlaceholder"
    />
    <input
      type="file"
      :disabled="question.isInputReadOnly"
      :class="question.cssClasses.fileInput"
      :id="question.inputId"
      :aria-required="question.ariaRequired"
      :aria-label="question.ariaLabel"
      :aria-invalid="question.ariaInvalid"
      :aria-describedby="question.ariaDescribedBy"
      :multiple="false"
      :title="question.inputTitle"
      :tabindex="-1"
      :accept="question.acceptedTypes"
      @change="question.onFileInputChange"
    />
    <div :class="question.cssClasses.buttonsContainer">
      <button
        :title="question.clearButtonCaption"
        :class="question.cssClasses.clearButton"
        v-key2click
        :disabled="question.getIsClearButtonDisabled()"
        @click="question.doClean"
      >
        <SvComponent
          :is="'sv-svg-icon'"
          :iconName="question.cssClasses.clearButtonIcon"
          :size="'auto'"
        ></SvComponent>
      </button>
      <label
        :class="question.getChooseButtonCss()"
        :for="question.inputId"
        :aria-label="question.chooseButtonCaption"
        @click="question.chooseFiles"
        v-key2click
      >
        <SvComponent
          :is="'sv-svg-icon'"
          :iconName="question.cssClasses.chooseButtonIcon"
          :size="'auto'"
          :title="question.chooseButtonCaption"
        ></SvComponent>
        <span class="sv-visuallyhidden">{{ question.chooseButtonCaption }}</span>
      </label>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { key2ClickDirective as vKey2click } from "survey-vue3-ui";
import { SvComponent } from "survey-vue3-ui";
import type { QuestionFileEditorModel } from "survey-creator-core";
import { useQuestion } from "survey-vue3-ui";
import { ref } from "vue";

const root = ref<HTMLElement>();

const props = defineProps<{ question: QuestionFileEditorModel }>();
useQuestion(props, root);
</script>
