// packages/survey-creator-angular/src/custom-questions/swatch.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "svc-swatch",
  templateUrl: "./swatch.component.html",
})
export class SwatchComponent {
  @Input() color!: string;
  @Input() showIcon?: boolean;
  @Input() className?: string;
  @Input() swatchIcon?: string;
  @Input() iconClassName?: string;
  @Input() colorInputClassName?: string;
  @Input() colorInputValue?: string;
  @Input() inputDisabled?: boolean;
  @Input() colorInputChange?: (event: Event) => void;
  @Input() arias?: { [index: string]: any };

  get rootClassName(): string {
    return this.className ?? "sd-color-swatch";
  }
  get rootStyle(): { [index: string]: string } {
    return { backgroundColor: this.color };
  }
  get isPicker(): boolean {
    return !!this.colorInputChange;
  }
  get iconName(): string {
    return this.swatchIcon ?? "icon-dropper-16x16";
  }
  get iconClass(): string {
    return this.iconClassName ?? "sd-color-swatch__icon";
  }
}

<ng-container [ngSwitch]="isPicker">
  <label *ngSwitchCase="true" [class]="rootClassName">
    <ng-container *ngTemplateOutlet="content"></ng-container>
  </label>
  <div *ngSwitchDefault [class]="rootClassName">
    <ng-container *ngTemplateOutlet="content"></ng-container>
  </div>
</ng-container>

<ng-template #content>
  <div class="sd-color-swatch__content" [style]="rootStyle">
    <svg *ngIf="showIcon" [iconName]="iconName" [class]="iconClass" [size]="'auto'" sv-ng-svg-icon></svg>
    <input *ngIf="isPicker"
      type="color"
      [disabled]="inputDisabled"
      [value]="colorInputValue"
      [class]="colorInputClassName"
      tabindex="-1"
      [attr.aria-required]="arias?.['aria-required']"
      [attr.aria-labelledby]="arias?.['aria-labelledby']"
      [attr.aria-label]="arias?.['aria-label']"
      [attr.aria-invalid]="arias?.['aria-invalid']"
      [attr.aria-describedby]="arias?.['aria-describedby']"
      (change)="colorInputChange!($event)" />
  </div>
</ng-template>

// packages/survey-creator-vue/src/custom-questions/Swatch.vue
<template>
  <component :is="rootTag" :class="rootClassName">
    <div class="sd-color-swatch__content" :style="rootStyle">
      <SvComponent
        v-if="showIcon"
        :is="'sv-svg-icon'"
        :iconName="swatchIcon ?? 'icon-dropper-16x16'"
        :class="iconClassName ?? 'sd-color-swatch__icon'"
        :size="'auto'"
      />
      <input
        v-if="colorInputChange"
        type="color"
        :disabled="inputDisabled"
        :value="colorInputValue"
        :class="colorInputClassName"
        tabindex="-1"
        v-bind="arias"
        @change="colorInputChange"
      />
    </div>
  </component>
</template>

<script lang="ts" setup>
import { computed } from "vue";
import { SvComponent } from "survey-vue3-ui";

const props = withDefaults(defineProps<{
  color: string;
  showIcon?: boolean;
  className?: string;
  swatchIcon?: string;
  iconClassName?: string;
  colorInputClassName?: string;
  colorInputValue?: string;
  inputDisabled?: boolean;
  colorInputChange?: (event: Event) => void;
  arias?: Record<string, any>;
}>(), {
  showIcon: false,
});

const rootTag = computed(() => props.colorInputChange ? "label" : "div");
const rootClassName = computed(() => props.className ?? "sd-color-swatch");
const rootStyle = computed(() => ({ backgroundColor: props.color }));
</script>
