// packages/survey-creator-angular/src/custom-questions/text-with-reset.component.ts
import { Component } from "@angular/core";
import { AngularComponentFactory, QuestionAngular } from "survey-angular-ui";
import { QuestionCommentWithResetModel, QuestionTextWithResetModel } from "survey-creator-core";

@Component({
  templateUrl: "./text-with-reset.component.html",
  selector: "svc-text-with-reset"
})
export class QuestionTextWithResetComponent extends QuestionAngular<QuestionTextWithResetModel | QuestionCommentWithResetModel> {
  getComponentName() {
    return this.model.wrappedQuestionTemplate + "-question";
  }
}
AngularComponentFactory.Instance.registerComponent("textwithreset-question", QuestionTextWithResetComponent);
AngularComponentFactory.Instance.registerComponent("commentwithreset-question", QuestionTextWithResetComponent);
<div [class]="model.getRootClass()">
    <ng-template [component]="{ name: getComponentName(), data: { model } }"></ng-template>
    <button [class]="model.cssClasses.resetButton" [disabled]="model.resetValueAdorner.isDisabled"
        (click)="model.resetValueAdorner.resetValue()" [attr.title]="model.resetValueAdorner.caption">
        <svg [iconName]="model.cssClasses.resetButtonIcon" size="'auto'" sv-ng-svg-icon></svg>
    </button>
</div>

// packages/survey-creator-vue/src/custom-questions/TextWithReset.vue
<template>
  <div :class="question.getRootClass()">
    <SvComponent :name="getComponentName()" :question="question"></SvComponent>
    <button
      :class="question.cssClasses.resetButton"
      :disabled="question.resetValueAdorner.isDisabled"
      @click="question.resetValueAdorner.resetValue"
      :title="question.resetValueAdorner.caption"
    >
      <SvComponent
        :name="'sv-svg-icon'"
        :iconName="question.cssClasses.resetButtonIcon"
        :size="'auto'"
      ></SvComponent>
    </button>
  </div>
</template>
<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import type {
  QuestionTextWithResetModel,
  QuestionCommentWithResetModel,
} from "survey-creator-core";
import { useQuestion } from "survey-vue3-ui";
import { ref } from "vue";

const props = defineProps<{
  question: QuestionTextWithResetModel | QuestionCommentWithResetModel;
}>();
const getComponentName = () => {
  return "survey-" + props.question.wrappedQuestionTemplate;
};
useQuestion(props, ref<HTMLElement>());
</script>
