// packages/survey-creator-react/src/QuestionLinkValue.tsx
import React from "react";
import {
  ReactQuestionFactory,
  SurveyQuestionElementBase
} from "survey-react-ui";
import { editorLocalization, QuestionLinkValueModel } from "survey-creator-core";
import { ActionButton } from "./ActionButton";

export class SurveyQuestionLinkValue extends SurveyQuestionElementBase {
  protected get question(): QuestionLinkValueModel {
    return this.questionBase as QuestionLinkValueModel;
  }
  protected renderClear(): JSX.Element {
    const showClear = (this.questionBase as any).showClear;
    if (!this.questionBase.isReadOnly && showClear) {
      return (
        <ActionButton
          classes={this.question.linkClearButtonCssClasses}
          click={() => this.question.doClearClick()}
          selected={this.question.isSelected}
          text={editorLocalization.getString("pe.clear")}
        ></ActionButton>
      );
    }
    else {
      return null;
    }
  }
  protected renderElement(): JSX.Element {
    return (
      <>
        <ActionButton
          classes={this.question.linkSetButtonCssClasses}
          click={() => this.question.doLinkClick()}
          selected={this.question.isSelected}
          disabled={this.question.isReadOnly}
          text={this.question.linkValueText}
          title={this.question.tooltip}
        ></ActionButton>
        {this.renderClear()}
      </>
    );
  }
}

ReactQuestionFactory.Instance.registerQuestion("linkvalue", (props) => {
  return React.createElement(SurveyQuestionLinkValue, props);
});

// packages/survey-creator-angular/src/questions/question-link-value.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, QuestionAngular } from "survey-angular-ui";
import { editorLocalization, QuestionLinkValueModel } from "survey-creator-core";

@Component({
  selector: "svc-link-value",
  templateUrl: "./question-link-value.component.html",
  styles: [":host { display: none; }"]
})
export class LinkValueQuestionComponent extends QuestionAngular<QuestionLinkValueModel> {
  get clearCaption() {
    return editorLocalization.getString("pe.clear");
  }
}

AngularComponentFactory.Instance.registerComponent("linkvalue-question", LinkValueQuestionComponent);

<ng-template #template>
  <svc-action-button [text]="model.linkValueText" [click]="model.doLinkClick" [selected]="model.isSelected"  [disabled]="model.isReadOnly" [classes]="model.linkSetButtonCssClasses" [title]="model.tooltip">
  </svc-action-button>
  <ng-container *ngIf="!model.isReadOnly && model.showClear">
    <svc-action-button
      [text]="clearCaption" (click)="model.doClearClick" [selected]="model.isSelected" [disabled]="false" [classes]="model.linkClearButtonCssClasses">
    </svc-action-button>
  </ng-container>
</ng-template>
