// packages/survey-creator-vue/src/side-bar/PropertyGridPlaceholder.vue
<template>
  <div class="svc-property-grid-placeholder">
    <div class="svc-property-grid-placeholder__header">
      <span class="svc-property-grid-placeholder__title">{{
        editorLocalization.getString("ed.propertyGridPlaceholderTitle")
      }}</span>
      <span class="svc-property-grid-placeholder__description">{{
        editorLocalization.getString("ed.propertyGridPlaceholderDescription")
      }}</span>
    </div>
    <div class="svc-property-grid-placeholder__content">
      <div class="svc-property-grid-placeholder__gap"></div>
      <div class="svc-property-grid-placeholder__image"></div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { editorLocalization as al } from "survey-creator-core";
const editorLocalization = al;
</script>

// packages/survey-creator-angular/src/tab-control/property-grid-placeholder.component.ts
import { Component, Input } from "@angular/core";
import { Action, CssClassBuilder } from "survey-core";
import { BaseAngular, AngularComponentFactory, EmbeddedViewContentComponent } from "survey-angular-ui";
import { editorLocalization } from "survey-creator-core";

@Component({
  selector: "svc-property-grid-placeholder",
  templateUrl: "./property-grid-placeholder.component.html",
  styles: [":host { display: none; }"]
})
export class PropertyGridPlaceholderComponent extends EmbeddedViewContentComponent {
  editorLocalization = editorLocalization;
}
AngularComponentFactory.Instance.registerComponent("svc-property-grid-placeholder", PropertyGridPlaceholderComponent);

<ng-template #template>
  <div class="svc-property-grid-placeholder">
    <div class="svc-property-grid-placeholder__header">
      <span
        class="svc-property-grid-placeholder__title">{{editorLocalization.getString("ed.propertyGridPlaceholderTitle")}}</span>
      <span
        class="svc-property-grid-placeholder__description">{{editorLocalization.getString("ed.propertyGridPlaceholderDescription")}}</span>
    </div>
    <div class="svc-property-grid-placeholder__content">
      <div class="svc-property-grid-placeholder__gap"></div>
      <div class="svc-property-grid-placeholder__image"></div>
    </div>
  </div>
</ng-template>
