// packages/survey-creator-angular/src/questions/logic-operator.component.ts
import { Component } from "@angular/core";
import { AngularComponentFactory, QuestionAngular } from "survey-angular-ui";
import { DropdownListModel, QuestionDropdownModel, RendererFactory } from "survey-core";
import { initLogicOperator } from "survey-creator-core";

@Component({
  selector: "svc-logic-operator",
  templateUrl: "./logic-operator.component.html",
  styles: [":host { display: none; }"]
})
export class LogicOperatorComponent extends QuestionAngular<QuestionDropdownModel> {
  private dropdownListModel?: DropdownListModel;
  get dropdownModel(): DropdownListModel | undefined {
    return this.dropdownListModel;
  }
  click(event: any) {
    this.dropdownListModel?.onClick(event);
  }
  clear(event: any) {
    this.dropdownListModel?.onClear(event);
  }
  keyup(event: any) {
    this.dropdownListModel?.keyHandler(event);
  }
  override ngOnInit(): void {
    super.ngOnInit();
    this.dropdownListModel = this.model.dropdownListModel || new DropdownListModel(this.model);
    initLogicOperator(this.model);
  }
}
AngularComponentFactory.Instance.registerComponent("sv-logic-operator", LogicOperatorComponent);

RendererFactory.Instance.registerRenderer("dropdown", "logicoperator", "sv-logic-operator");
<ng-template #template>
  <div [class]="model.cssClasses.selectWrapper">
    <ng-container *ngIf="!model.isReadOnly">
      <div [class]="model.getControlClass()"  (click)="click($event)" (keyup)="keyup($event)"
        [attr.id]="model.inputId" 
        [attr.required]="model.isRequired" 
        [attr.tabindex]= "model.isInputReadOnly ? undefined : 0"
        [attr.disabled]="model.isInputReadOnly"
        [attr.role]="model.ariaRole"
        [attr.aria-required]="model.ariaRequired" 
        [attr.aria-label]="model.ariaLabel" 
        [attr.aria-invalid]="model.ariaInvalid" 
        [attr.aria-describedby]= "model.ariaDescribedBy" 
      >
        <div [class]="model.cssClasses.controlValue">
          <sv-ng-string *ngIf="model.selectedItemLocText" [model]="model.selectedItemLocText"></sv-ng-string>
          <div>{{model.readOnlyText}}</div>
        </div>
        <div *ngIf="model.allowClear && model.cssClasses.cleanButtonIconId" [class]="model.cssClasses.cleanButton" (click)="clear" [visible]="!model.isEmpty()">
          <svg [class]="model.cssClasses.cleanButtonSvg" [iconName]="model.cssClasses.cleanButtonIconId" [size]="'auto'"
            [title]="model.clearCaption" [size]="24" sv-ng-svg-icon></svg>
        </div>
      </div>
        <sv-ng-popup [popupModel]="model.popupModel"></sv-ng-popup>
    </ng-container>
    <div disabled *ngIf="model.isReadOnly" [class]="model.getControlClass()" [attr.id]="model.inputId">
      <sv-ng-string *ngIf="model.selectedItemLocText" [model]="model.selectedItemLocText"></sv-ng-string>
      <div>{{model.readOnlyText}}</div>
    </div>
  </div>
</ng-template>

// packages/survey-creator-vue/src/questions/LogicOperator.vue
<template>
  <div :class="question.cssClasses.selectWrapper">
    <template v-if="!question.isReadOnly">
      <div
        :class="question.getControlClass()"
        @click="click"
        @keyup="keyup"
        :id="question.inputId"
        :required="question.isRequired"
        :tabindex="question.isInputReadOnly ? undefined : 0"
        :disabled="question.isInputReadOnly"
        :role="question.ariaRole"
        :aria-required="question.ariaRequired"
        :aria-label="question.ariaLabel"
        :aria-invalid="question.ariaInvalid"
        :aria-describedby="question.ariaDescribedBy"
      >
        <div :class="question.cssClasses.controlValue">
          <survey-string
            v-if="question.selectedItemLocText"
            :locString="question.selectedItemLocText"
          ></survey-string>
          <div>{{ question.readOnlyText }}</div>
        </div>
        <div
          v-if="question.allowClear && question.cssClasses.cleanButtonIconId"
          :class="question.cssClasses.cleanButton"
          @click="clear"
          v-show="!question.isEmpty()"
        >
          <sv-svg-icon
            :class="question.cssClasses.cleanButtonSvg"
            :iconName="question.cssClasses.cleanButtonIconId"
            :size="'auto'"
            :title="question.clearCaption"
          ></sv-svg-icon>
        </div>
      </div>
      <sv-popup :model="question.popupModel"></sv-popup>
    </template>
    <div
      disabled
      v-if="question.isReadOnly"
      :class="question.getControlClass()"
      :id="question.inputId"
    >
      <survey-string
        v-if="question.selectedItemLocText"
        :locString="question.selectedItemLocText"
      ></survey-string>
      <div>{{ question.readOnlyText }}</div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { DropdownListModel, type QuestionDropdownModel } from "survey-core";
import { initLogicOperator } from "survey-creator-core";
import { useQuestion } from "survey-vue3-ui";
import { computed, ref } from "vue";
const props = defineProps<{ question: QuestionDropdownModel }>();
const root = ref<HTMLElement>();
const dropdownModel = computed(() => {
  return (
    props.question.dropdownListModel ?? new DropdownListModel(props.question)
  );
});
useQuestion(props, root, (newValue) => {
  initLogicOperator(newValue);
});
const click = (event: Event) => {
  dropdownModel.value?.onClick(event);
};
const clear = (event: Event) => {
  dropdownModel.value?.onClear(event);
};
const keyup = (event: Event) => {
  dropdownModel.value?.keyHandler(event);
};
</script>
<script lang="ts">
import { RendererFactory } from "survey-core";
RendererFactory.Instance.registerRenderer(
  "dropdown",
  "logicoperator",
  "sv-logic-operator"
);
</script>
