// packages/survey-creator-angular/src/tabs/container/container-tab.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { TabContainerViewModel } from "survey-creator-core";

@Component({
  selector: "svc-tab-container",
  templateUrl: "./container-tab.component.html",
  styles: [":host { display: none; }"]
})
export class ContainerTabComponent extends BaseAngular<TabContainerViewModel> {
  @Input() model!: TabContainerViewModel;
  protected getModel(): TabContainerViewModel {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-tab-container", ContainerTabComponent);


<ng-template #template>
  <svc-component-container [model]="model.containerModel"></svc-component-container>
</ng-template>

// packages/survey-creator-vue/src/tabs/ContainerTab.vue
<template>
  <SvComponent :is="'svc-component-container'" :model="model.containerModel" />
</template>

<script lang="ts" setup>
import { SvComponent, useBase } from "survey-vue3-ui";
import type { TabContainerViewModel } from "survey-creator-core";

const props = defineProps<{ model: TabContainerViewModel }>();
useBase(() => props.model);
</script>
