// packages/survey-creator-angular/src/toolbox/toolbox.component.ts
import { Component, Input } from "@angular/core";
import { SurveyCreatorModel, QuestionToolbox } from "survey-creator-core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-toolbox",
  templateUrl: "./toolbox.component.html",
  styles: [":host { display: none; }"]
})
export class ToolboxComponent extends BaseAngular<QuestionToolbox> {
  @Input() model!: SurveyCreatorModel;
  public get toolbox() {
    return this.model.toolbox;
  }
  protected getModel(): QuestionToolbox {
    return this.toolbox;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-toolbox", ToolboxComponent);

<ng-template #template>
  <div class="svc-toolbox">
    <div class="svc-toolbox__container">
      <ng-container *ngIf="!(toolbox.categories.length == 1 || !toolbox.showCategoryTitles)">
        <svc-toolbox-category *ngFor="let category of toolbox.categories" [category]="category" [toolbox]="toolbox"></svc-toolbox-category>
      </ng-container>
      <ng-container *ngIf="toolbox.categories.length == 1 || !toolbox.showCategoryTitles">
        <div class="svc-toolbox__category">
          <svc-toolbox-tool *ngFor="let item of toolbox.visibleActions" [creator]="model" [item]="item" [parentModel]="toolbox" [isCompact]="toolbox.isCompact"></svc-toolbox-tool>
        </div>
      </ng-container>
    </div>
  </div>
</ng-template>

// packages/survey-creator-vue/src/toolbox/Toolbox.vue
<template>
  <div class="svc-toolbox">
    <div class="svc-toolbox__container">
      <template
        v-if="!(toolbox.categories.length == 1 || !toolbox.showCategoryTitles)"
      >
        <SvComponent
          :is="'svc-toolbox-category'"
          v-for="(category, index) in toolbox.categories"
          :category="category"
          :key="index"
          :toolbox="toolbox"
        ></SvComponent>
      </template>

      <template
        v-if="toolbox.categories.length == 1 || !toolbox.showCategoryTitles"
      >
        <div class="svc-toolbox__category">
          <SvComponent
            :is="'svc-toolbox-tool'"
            v-for="(item, index) in toolbox.visibleActions"
            :creator="model"
            :key="index"
            :item="item"
            :parentModel="toolbox"
            :isCompact="toolbox.isCompact"
          ></SvComponent>
        </div>
      </template>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import type { SurveyCreatorModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { computed } from "vue";
const props = defineProps<{ model: SurveyCreatorModel }>();
const toolbox = computed(() => {
  return props.model.toolbox;
});
useBase(() => toolbox.value);
</script>
