// packages/survey-creator-angular/src/toolbox/toolbox-item.component.ts
import { Component, Input } from "@angular/core";
import { ToolboxToolViewModel, SurveyCreatorModel, IQuestionToolboxItem, QuestionToolboxItem } from "survey-creator-core";
import { BaseAngular, AngularComponentFactory } from "survey-angular-ui";

@Component({
  selector: "svc-toolbox-item",
  templateUrl: "./toolbox-item.component.html",
  styles: [":host { display: none; }"]
})
export class ToolboxItemComponent extends BaseAngular<ToolboxToolViewModel> {
  @Input() creator!: SurveyCreatorModel;
  @Input() model!: QuestionToolboxItem;
  @Input() isCompact: boolean = false;
  @Input() viewModel!: ToolboxToolViewModel;
  protected getModel(): ToolboxToolViewModel {
    return this.viewModel;
  }
  public get item() {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-toolbox-item", ToolboxItemComponent);

<ng-template #template>
  <div role="button" [attr.aria-label]="this.item.tooltip" [class]="this.item.renderedCss"
    (click)="viewModel.click($event)" [key2click]>
    <span class="svc-toolbox__item-container">
      <svg *ngIf="item.iconName" [iconName]="item.iconName" [size]="'auto'" class="svc-toolbox__item-icon" [title]="this.item.tooltip"
        sv-ng-svg-icon></svg>
    </span>
    <span *ngIf="!isCompact" class="svc-toolbox__item-title">{{item.title}}</span>
    </div>
  <span *ngIf="isCompact" class="svc-toolbox__item-banner" (click)="viewModel.click($event)">
    <svg *ngIf="item.iconName" [iconName]="item.iconName" [size]="'auto'" class="svc-toolbox__item-icon"
      sv-ng-svg-icon></svg>
    <span>{{item.title}}</span>
    </span>
</ng-template>

// packages/survey-creator-vue/src/toolbox/ToolboxItem.vue
<template>
  <div
    class="svc-toolbox__item"
    role="button"
    :aria-label="item.tooltip"
    :title="item.tooltip"
    :class="item.renderedCss"
    @click="viewModel.click($event)"
    v-key2click
  >
    <span class="svc-toolbox__item-container">
      <SvComponent
        :title="item.tooltip || item.title"
        :is="'sv-svg-icon'"
        v-if="item.iconName"
        :iconName="item.iconName"
        :size="'auto'"
        class="svc-toolbox__item-icon"
      ></SvComponent>
    </span>
    <span v-if="!isCompact" class="svc-toolbox__item-title">
      {{ item.title }}
    </span>
  </div>
  <span v-if="isCompact" class="svc-toolbox__item-banner" @click="viewModel.click($event)">
      <SvComponent
        :title="itemp.tooltip || item.title"
        :is="'sv-svg-icon'"
        :iconName="item.iconName"
        :size="24"
        class="svc-toolbox__item-icon"
      ></SvComponent>
      <span>{{ item.title }}</span>
  </span>
</template>
<script lang="ts" setup>
import { key2ClickDirective as vKey2click } from "survey-vue3-ui";
import { SvComponent } from "survey-vue3-ui";
import type {
  SurveyCreatorModel,
  IQuestionToolboxItem,
  ToolboxToolViewModel,
  QuestionToolboxItem,
} from "survey-creator-core";
defineProps<{
  creator: SurveyCreatorModel;
  item: QuestionToolboxItem;
  isCompact: boolean;
  viewModel: ToolboxToolViewModel;
}>();
</script>
