// packages/survey-creator-angular/src/toolbox/toolbox-tool.component.ts
import { Component, Input } from "@angular/core";
import { CreatorModelComponent } from "../creator-model.component";
import { SurveyCreatorModel, ToolboxToolViewModel, QuestionToolboxItem } from "survey-creator-core";
import { Action, ActionContainer } from "survey-core";

@Component({
  selector: "svc-toolbox-tool",
  templateUrl: "./toolbox-tool.component.html",
  styles: [":host { display: none; }"]
})
export class ToolboxToolComponent extends CreatorModelComponent<Action> {
  @Input() creator!: SurveyCreatorModel;
  @Input() item!: Action;
  @Input() parentModel!: ActionContainer;
  @Input() isCompact: boolean = false;
  public model!: ToolboxToolViewModel;
  createModel() {
    this.model = new ToolboxToolViewModel(<any>this.item, this.creator, this.parentModel);
  }
  protected getPropertiesToTrack(): string[] {
    return ["creator", "item"];
  }
  protected getModel(): Action {
    return this.item;
  }
  public get itemCssClasses() {
    return (this.item as QuestionToolboxItem).css;
  }
  protected override getPropertiesToUpdateSync(): string[] {
    return ["mode"];
  }
  override ngOnDestroy(): void {
    super.ngOnDestroy();
    this.model.dispose();
  }
}

<ng-template #template>
    <div [class.sv-action--hidden]="!item.isVisible" [class]="itemCssClasses">
        <div class="svc-toolbox__category-separator" *ngIf="item.needSeparator && !creator.toolbox.showCategoryTitles">
        </div>
        <div class="sv-action__content" (pointerdown)="model.onPointerDown($event)"
            (mouseover)="model.onMouseOver(item, $event)"
        (mouseleave)="model.onMouseLeave(item, $event)">
            <ng-template [component]="{ name: item.component || 'svc-toolbox-item', default: 'svc-toolbox-item', 
            data: { model: item, viewModel: model, creator: creator, isCompact: isCompact } }"></ng-template>
        </div>
    </div>
</ng-template>

// packages/survey-creator-vue/src/toolbox/ToolboxTool.vue
<template>
  <div
    :class="item.css"
  >
    <div
      class="svc-toolbox__category-separator"
      v-if="item.needSeparator && !creator.toolbox.showCategoryTitles"
    ></div>
    <div class="sv-action__content"
      @pointerdown="model?.onPointerDown"
      @mousemove="(e) => { model?.onMouseOver(item, e); }"
      @mouseleave="(e) => { model?.onMouseLeave(item, e); }"
    >
      <component
        :viewModel="model"
        :is="item.itemComponent"
        :item="item"
        :creator="creator"
        :isCompact="isCompact"
      ></component>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { QuestionToolboxItem, ToolboxToolViewModel, type SurveyCreatorModel } from "survey-creator-core";
import type { Action, ActionContainer } from "survey-core";
import { useCreatorModel } from "@/creator-model";
import { computed } from "vue";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{
  creator: SurveyCreatorModel;
  item: QuestionToolboxItem;
  parentModel: ActionContainer;
  isCompact: boolean;
}>();
const model = useCreatorModel(
  () => new ToolboxToolViewModel(props.item as any, props.creator, props.parentModel),
  [() => props.creator, () => props.item],
  (model) => {
    model.dispose();
  }
);
useBase(() => props.item);
</script>
