// packages/survey-creator-angular/src/toolbox/toolbox-item-group.component.ts
import { Component, Input } from "@angular/core";
import { ToolboxToolViewModel, SurveyCreatorModel, IQuestionToolboxItem, QuestionToolboxItem } from "survey-creator-core";
import { BaseAngular, AngularComponentFactory } from "survey-angular-ui";

@Component({
  selector: "svc-toolbox-item-group",
  templateUrl: "./toolbox-item-group.component.html",
  styles: [":host { display: none; }"]
})
export class ToolboxItemGroupComponent extends BaseAngular<ToolboxToolViewModel> {
  @Input() creator!: SurveyCreatorModel;
  @Input() model!: QuestionToolboxItem;
  @Input() isCompact: boolean = false;
  @Input() viewModel!: ToolboxToolViewModel;
  protected getModel(): ToolboxToolViewModel {
    return this.viewModel;
  }
  public get item() {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-toolbox-item-group", ToolboxItemGroupComponent);

<ng-template #template>
  <svc-toolbox-item [model]="item" [viewModel]="viewModel" [creator]="creator" [isCompact]="isCompact"></svc-toolbox-item>
  <div class="svc-toolbox__item-submenu-button" (mouseover)="viewModel.onMouseOver(item, $event)"
    (mouseleave)="viewModel.onMouseLeave(item, $event)">
    <svg [iconName]="item.subitemsButtonIcon" [size]="'auto'" sv-ng-svg-icon></svg>
    <sv-ng-popup [popupModel]="model.popupModel" [getArea]="model.getArea"></sv-ng-popup>
  </div>
</ng-template>

// packages/survey-creator-vue/src/toolbox/ToolboxItemGroup.vue
<template>
  <SvComponent
    :is="'svc-toolbox-item'"
    :viewModel="viewModel"
    :item="item"
    :creator="creator"
    :isCompact="isCompact"
  ></SvComponent>
  <div class="svc-toolbox__item-submenu-button" @mouseover="hover" @mouseleave="leave">
    <SvComponent :is="'sv-svg-icon'" :iconName="item.subitemsButtonIcon" :size="'auto'"></SvComponent>
    <SvComponent
      :is="'sv-popup'"
      :model="item.popupModel"
      :getArea="item.getArea"
    ></SvComponent>
  </div>
</template>
<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import type {
  SurveyCreatorModel,
  IQuestionToolboxItem,
  ToolboxToolViewModel,
  QuestionToolboxItem,
} from "survey-creator-core";
const props = defineProps<{
  creator: SurveyCreatorModel;
  item: QuestionToolboxItem;
  isCompact: boolean;
  viewModel: ToolboxToolViewModel;
}>();
const hover = (event: MouseEvent) => {
  props.viewModel.onMouseOver(props.item as QuestionToolboxItem, event);
};
const leave = (event: MouseEvent) => {
  props.viewModel.onMouseLeave(props.item as QuestionToolboxItem, event);
};
</script>
