// packages/survey-creator-angular/src/toolbox/toolbox-list.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { ListModel } from "survey-core";
import { CreatorBase } from "survey-creator-core";

@Component({
  selector: "svc-toolbox-list ",
  templateUrl: "./toolbox-list.component.html",
  styles: [":host { display: none; }"]
})
export class ToolboxListComponent extends BaseAngular<ListModel> {
  @Input() model!: ListModel;
  @Input() creator!: CreatorBase;

  getModel() {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-toolbox-list", ToolboxListComponent);
<ng-template #template>
  <div [class]="model.cssClasses.root">
    <ng-container *ngFor="let item of model.renderedActions">
      <svc-toolbox-tool [item]="item" [creator]="toolbox.creator" [parentModel]="model"
        [isCompact]="false"></svc-toolbox-tool>
    </ng-container>
  </div>
</ng-template>

// packages/survey-creator-vue/src/toolbox/ToolboxList.vue
<template>
  <div :class="model.cssClasses.root">
    <template v-for="(item, index) in model.renderedActions" :key="index">
      <SvComponent
        :is="'svc-toolbox-tool'"
        :creator="creator"
        :item="item"
        :parentModel="model"
        :isCompact="false"
      ></SvComponent>
    </template>
  </div>
</template>
<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import type { ListModel } from "survey-core";
import type { CreatorBase } from "survey-creator-core";
defineProps<{
  model: ListModel;
  creator: CreatorBase;
}>();
</script>
