// packages/survey-creator-react/src/tabs/ContainerTab.tsx
import * as React from "react";
import { Base } from "survey-core";
import { ReactElementFactory, SurveyElementBase } from "survey-react-ui";
import { TabContainerViewModel } from "survey-creator-core";
import { ComponentContainer } from "../components/ComponentContainer";

interface ITabContainerComponentProps {
  data: TabContainerViewModel;
}

export class TabContainerComponent extends SurveyElementBase<
  ITabContainerComponentProps,
  any
> {
  constructor(props) {
    super(props);
  }
  protected getStateElement(): Base {
    return this.model;
  }
  private get model(): TabContainerViewModel {
    return this.props.data;
  }
  renderElement(): React.JSX.Element {
    return <ComponentContainer model={this.model.containerModel} />;
  }
}

ReactElementFactory.Instance.registerElement(
  "svc-tab-container",
  (props: ITabContainerComponentProps) => {
    return React.createElement(TabContainerComponent, props);
  }
);

// packages/survey-creator-angular/src/tabs/container/container-tab.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { TabContainerViewModel } from "survey-creator-core";

@Component({
  selector: "svc-tab-container",
  templateUrl: "./container-tab.component.html",
  styles: [":host { display: none; }"]
})
export class ContainerTabComponent extends BaseAngular<TabContainerViewModel> {
  @Input() model!: TabContainerViewModel;
  protected getModel(): TabContainerViewModel {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-tab-container", ContainerTabComponent);


<ng-template #template>
  <svc-component-container [model]="model.containerModel"></svc-component-container>
</ng-template>
