// packages/survey-creator-angular/src/tabs/translation/translation.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { Translation } from "survey-creator-core";

@Component({
  selector: "svc-tab-translation",
  templateUrl: "./translation.component.html",
  styles: [":host { display: none; }"]
})
export class TranslationTabComponent extends BaseAngular<Translation> {
  @Input() model!: Translation;

  protected getModel(): Translation {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-tab-translation", TranslationTabComponent);


<ng-template #template>
  <div class="svc-creator-tab__content svc-translation-tab" [class]="model.isEmpty ? 'svc-translation-tab--empty' : ''">
    <svc-surface-placeholder *ngIf="model.isEmpty" [name]="'translation'"
      [placeholderTitleText]="model.placeholderTitleText"
      [placeholderDescriptionText]="model.placeholderDescriptionText">
    </svc-surface-placeholder>
    <ng-container *ngIf="!model.isEmpty">
      <div *ngIf="stringsModel" class="st-content">
        <div class="svc-flex-column st-strings-wrapper">
          <div class="svc-flex-row st-strings-header">
            <ng-container *ngFor="let s of [stringsModel.stringsHeaderSurvey]; trackBy: trackStringsSurveyBy">
              <survey-content [model]="s"></survey-content>
            </ng-container>
          </div>
          <div class="svc-flex-row svc-plugin-tab__content st-strings">
            <ng-container *ngFor="let s of [stringsModel.stringsSurvey]; trackBy: trackStringsSurveyBy">
              <survey-content [model]="s"></survey-content>
            </ng-container>
          </div>
        </div>
      </div>
      <div *ngIf="sideBySideModel" class="st-side-by-side"
        [class]="sideBySideModel.targetSurvey ? '' : 'st-side-by-side--no-target'">
        <div class="st-side-by-side__source" #sourceScrollContainer>
          <ng-container *ngFor="let s of [sideBySideModel.sourceSurvey]; trackBy: trackStringsSurveyBy">
            <survey-content [model]="s"></survey-content>
          </ng-container>
        </div>
        <div *ngIf="sideBySideModel.targetSurvey" class="st-side-by-side__target" #targetScrollContainer>
          <ng-container *ngFor="let s of [sideBySideModel.targetSurvey]; trackBy: trackStringsSurveyBy">
            <survey-content [model]="s"></survey-content>
          </ng-container>
        </div>
      </div>
    </ng-container>
  </div>
</ng-template>

// packages/survey-creator-vue/src/tabs/translation/Translation.vue
<template>
  <div class="svc-creator-tab__content svc-translation-tab" :class="model.isEmpty ? 'svc-translation-tab--empty' : ''">
    <SurfacePlaceholder v-if="model.isEmpty" :name="'translation'" :placeholderTitleText="model.placeholderTitleText" :placeholderDescriptionText="model.placeholderDescriptionText" />
    <div v-if="!model.isEmpty && stringsModel" class="st-content">
      <div class="svc-flex-column st-strings-wrapper">
        <div class="svc-flex-row st-strings-header">
          <SurveyComponent :key="stringsModel.stringsHeaderSurvey?.elementIdPrefix" :model="stringsModel.stringsHeaderSurvey"></SurveyComponent>
        </div>
        <div class="svc-flex-row svc-plugin-tab__content st-strings">
          <SurveyComponent :key="stringsModel.stringsSurvey?.elementIdPrefix" :model="stringsModel.stringsSurvey"></SurveyComponent>
        </div>
      </div>
    </div>
    <div v-if="!model.isEmpty && sideBySideModel" class="st-side-by-side"
      :class="sideBySideModel.targetSurvey ? '' : 'st-side-by-side--no-target'">
      <div class="st-side-by-side__source" :key="sideBySideModel.sourceSurvey?.elementIdPrefix" :ref="setSourceScrollElement">
        <SurveyComponent :model="sideBySideModel.sourceSurvey"></SurveyComponent>
      </div>
      <div v-if="sideBySideModel.targetSurvey" class="st-side-by-side__target" :key="sideBySideModel.targetSurvey?.elementIdPrefix" :ref="setTargetScrollElement">
        <SurveyComponent :model="sideBySideModel.targetSurvey"></SurveyComponent>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import type { TranslationBase, TranslationSideBySide } from "survey-creator-core";
import { computed } from "vue";
import { useBase, SurveyComponent } from "survey-vue3-ui";
import SurfacePlaceholder from "../../components/SurfacePlaceholder.vue";
const props = defineProps<{ model: TranslationBase }>();
useBase(() => props.model);
const sideBySideModel = computed<TranslationSideBySide | undefined>(() =>
  props.model.isSideBySideForms ? (props.model as TranslationSideBySide) : undefined
);
// The strings-grid model: the tab model itself in the default mode and in the side-by-side grid view.
const stringsModel = computed<TranslationBase | undefined>(() =>
  sideBySideModel.value ? undefined : props.model
);
const setSourceScrollElement = (el: unknown) => {
  sideBySideModel.value?.setSourceScrollElement(el as HTMLElement);
};
const setTargetScrollElement = (el: unknown) => {
  sideBySideModel.value?.setTargetScrollElement(el as HTMLElement);
};
</script>
