// packages/survey-creator-angular/src/tabs/preview/test.component.ts
import { TestSurveyTabViewModel } from "survey-creator-core";
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-tab-test",
  templateUrl: "./test.component.html",
  styles: [":host { display: none; }"]
})
export class TestTabComponent extends BaseAngular<TestSurveyTabViewModel> {
  @Input() model!: TestSurveyTabViewModel;
  protected getModel(): TestSurveyTabViewModel {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-tab-test", TestTabComponent);

<ng-template #template>
  <div class="svc-creator-tab__content svc-test-tab__content"
    [class.svc-creator-tab__content--with-toolbar]="model.isPageToolbarVisible">
    <div *ngIf="model.survey.isEmpty" class="svc-test-tab--empty">
      <svc-surface-placeholder [name]="'preview'" [placeholderTitleText]="model.placeholderTitleText"
        [placeholderDescriptionText]="model.placeholderDescriptionText">
      </svc-surface-placeholder>
    </div>
    <div *ngIf="!model.survey.isEmpty" class="svc-plugin-tab__content">
      <survey-simulator [model]="model.simulator"></survey-simulator>
      <ng-container *ngIf="model.showResults">
        <survey-results [survey]="model.survey"></survey-results>
      </ng-container>
    </div>
    <div *ngIf="model.isPageToolbarVisible" class="svc-plugin-tab__content-actions svc-test-tab__content-actions">
      <sv-action-bar [model]="model.pages"></sv-action-bar>
    </div>
  </div>
</ng-template>

// packages/survey-creator-vue/src/tabs/preview/Test.vue
<template>
  <div
    class="svc-creator-tab__content svc-test-tab__content"
    :class="{
      'svc-creator-tab__content--with-toolbar': model.isPageToolbarVisible,
    }"
  >
    <div v-if="model.survey.isEmpty" class="svc-test-tab--empty">
      <SurfacePlaceholder :name="'preview'" :placeholderTitleText="model.placeholderTitleText" :placeholderDescriptionText="model.placeholderDescriptionText" />
    </div>
    <div v-if="!model.survey.isEmpty" class="svc-plugin-tab__content" @scroll="model.onScroll()">
      <SvComponent
        :is="'survey-simulator'"
        :model="model.simulator"
      ></SvComponent>
      <template v-if="model.showResults">
        <SvComponent
          :is="'survey-results'"
          :survey="model.survey"
        ></SvComponent>
      </template>
    </div>
    <div
      v-if="model.isPageToolbarVisible"
      class="svc-plugin-tab__content-actions svc-test-tab__content-actions"
    >
      <SvComponent :is="'sv-action-bar'" :model="model.pages"></SvComponent>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import type { TestSurveyTabViewModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import SurfacePlaceholder from "../../components/SurfacePlaceholder.vue";
const props = defineProps<{ model: TestSurveyTabViewModel }>();
useBase(() => props.model);
</script>
