// packages/survey-creator-angular/src/tabs/preview/test-again.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "survey-angular-ui";
import { Action } from "survey-core";

@Component({
  selector: "survey-test-again",
  templateUrl: "./test-again.component.html",
  styles: [":host { display: none; }"]
})
export class TestAgainActionComponent extends BaseAngular<Action> {
  @Input() model!: Action;
  protected getModel(): Action {
    return this.model;
  }
}
<ng-template #template>
  <div role="button" class="svc-preview__test-again svc-btn" (click)="model.action()" [surveyKey2Click]>
    <span class="svc-text svc-text--normal svc-text--bold">
      {{model.title}}
    </span>
  </div>
</ng-template>

// packages/survey-creator-vue/src/tabs/preview/TestAgain.vue
<template>
  <div
    role="button"
    class="svc-preview__test-again svc-btn"
    @click="model.action()"
    v-key2click
  >
    <span class="svc-text svc-text--normal svc-text--bold">
      {{ model.title }}
    </span>
  </div>
</template>
<script lang="ts" setup>
import type { Action } from "survey-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ model: Action }>();
useBase(() => props.model);
</script>
