// packages/survey-creator-angular/src/components/collab-bar.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-collab-bar",
  templateUrl: "./collab-bar.component.html",
  styles: [":host { display: none; }"]
})
export class CollabBarComponent extends BaseAngular {
  @Input() model: any;

  getModel() {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-collab-bar", CollabBarComponent);

<ng-template #template>
  <div class="svc-collab-bar">
    <div class="svc-collab-bar__left">
      <sv-action-bar [model]="model.actions"></sv-action-bar>
      <!-- The connection plate is markup, not an action: an action-bar item is
           always a button, and a status is not clickable. -->
      <div *ngIf="model.statusVisible" [class]="model.getStatusCss()" role="status">
        <svg [iconName]="model.statusIconName" [size]="16" sv-ng-svg-icon></svg>
        <span class="svc-collab-bar__status-text">{{ model.statusText }}</span>
      </div>
    </div>
    <div class="svc-collab-bar__right">
      <sv-action-bar [model]="model.participantActions"></sv-action-bar>
      <sv-action-bar [model]="model.toolActions"></sv-action-bar>
    </div>
    <!-- The Version History window is the bar's own. position:fixed, so
         rendering it here keeps it inside the themed root without affecting
         layout - the creator needs no floating-window host. -->
    <svc-floating-panel *ngIf="model.historyPanel" [model]="model.historyPanel"></svc-floating-panel>
  </div>
</ng-template>

// packages/survey-creator-vue/src/components/CollabBar.vue
<template>
  <div class="svc-collab-bar">
    <div class="svc-collab-bar__left">
      <SvComponent :is="'sv-action-bar'" :model="model.actions" />
      <!-- The connection plate is markup, not an action: an action-bar item is
           always a button, and a status is not clickable. -->
      <div v-if="model.statusVisible" :class="model.getStatusCss()" role="status">
        <SvComponent :is="'sv-svg-icon'" :iconName="model.statusIconName" :size="16" />
        <span class="svc-collab-bar__status-text">{{ model.statusText }}</span>
      </div>
    </div>
    <div class="svc-collab-bar__right">
      <SvComponent :is="'sv-action-bar'" :model="model.participantActions" />
      <SvComponent :is="'sv-action-bar'" :model="model.toolActions" />
    </div>
    <!-- The Version History window is the bar's own. position:fixed, so
         rendering it here keeps it inside the themed root without affecting
         layout - the creator needs no floating-window host. -->
    <SvComponent
      :is="'svc-floating-panel'"
      v-if="model.historyPanel"
      :model="model.historyPanel"
    />
  </div>
</template>
<script lang="ts" setup>
import { SvComponent, useBase } from "survey-vue3-ui";
import type { CollabBarModel } from "survey-creator-core/collaboration";
const props = defineProps<{ model: CollabBarModel }>();
useBase(() => props.model);
</script>
