// packages/survey-creator-react/src/components/Scroll.tsx
import * as React from "react";
import { Base, settings } from "survey-core";
import { ScrollViewModel } from "survey-creator-core";
import { ReactElementFactory, SurveyActionBar, SurveyElementBase, SvgIcon } from "survey-react-ui";

interface IScrollComponentProps {
  children: React.ReactNode;
}
export class ScrollComponent extends React.Component<IScrollComponentProps, any> {
  private model: ScrollViewModel;
  private rootRef: React.RefObject<HTMLDivElement>;
  constructor(props: any) {
    super(props);
    this.rootRef = React.createRef();
    this.model = new ScrollViewModel();
  }
  componentDidMount() {
    const container = this.rootRef.current;
    if (!container) return;
    this.model.setRootElement(container);
  }
  componentWillUnmount() {
    this.model.unsubscribeRootElement();
    this.model.setRootElement(undefined);
  }

  render(): JSX.Element {
    return <div ref={this.rootRef} className="svc-scroll__wrapper">
      <div className="svc-scroll__scroller sv-drag-target-skipped" onScroll={() => this.model.onScrollContainer()}>
        <div className="svc-scroll__container">
          {this.props.children}
        </div>
      </div>
      <div className="svc-scroll__scrollbar" onScroll={() => this.model.onScrollScrollbar()}>
        <div className="svc-scroll__scrollbar-sizer">
        </div>
      </div>
    </div>;
  }
}

ReactElementFactory.Instance.registerElement("svc-scroll", (props) => {
  return React.createElement(
    ScrollComponent,
    props as IScrollComponentProps
  );
});

// packages/survey-creator-vue/src/components/Scroll.vue
<template>
  <div ref="root" class="svc-scroll__wrapper">
      <div class="svc-scroll__scroller sv-drag-target-skipped" @scroll="() => model.onScrollContainer()">
        <div class="svc-scroll__container">
          <slot />
        </div>
      </div>
      <div class="svc-scroll__scrollbar" @scroll="() => model.onScrollScrollbar()">
        <div class="svc-scroll__scrollbar-sizer">
        </div>
      </div>
    </div>
</template>
<script lang="ts" setup>
import { ScrollViewModel } from "survey-creator-core";
import { onMounted, onUnmounted, ref } from "vue";

const model = new ScrollViewModel();
const root = ref<HTMLDivElement>();
onMounted(() => {
  model.setRootElement(root.value as HTMLDivElement);
});
onUnmounted(() => {
  model.setRootElement(undefined as any);
  model.unsubscribeRootElement();
});
</script>
