// packages/survey-creator-angular/src/components/scroll.component.ts
import { ScrollViewModel } from "survey-creator-core";
import { Component, ElementRef, OnDestroy, ViewChild, AfterViewInit, ViewContainerRef } from "@angular/core";
import { AngularComponentFactory, EmbeddedViewContentComponent } from "survey-angular-ui";

@Component({
  selector: "svc-scroll",
  templateUrl: "./scroll.component.html",
  styles: [":host { display: none; }"]
})
export class ScrollComponent extends EmbeddedViewContentComponent implements AfterViewInit, OnDestroy {
  public model!: ScrollViewModel;
  @ViewChild("container") container!: ElementRef<HTMLElement>
  constructor(viewContainerRef?: ViewContainerRef) {
    super(viewContainerRef);
    this.model = new ScrollViewModel();
  }
  ngAfterViewInit() {
    this.model.setRootElement(this.container?.nativeElement as HTMLDivElement);
  }
  ngOnDestroy(): void {
    this.model.setRootElement(undefined as any);
    this.model.unsubscribeRootElement();
  }
}
AngularComponentFactory.Instance.registerComponent("svc-scroll", ScrollComponent);
<ng-template #template>
    <div class="svc-scroll__wrapper" #container>
        <div class="svc-scroll__scroller sv-drag-target-skipped" (scroll)="model.onScrollContainer()">
            <div class="svc-scroll__container">
                <ng-content></ng-content>
            </div>
        </div>
        <div class="svc-scroll__scrollbar" (scroll)="model.onScrollScrollbar()">
            <div class="svc-scroll__scrollbar-sizer">
            </div>
        </div>
    </div>
</ng-template>

// packages/survey-creator-vue/src/components/Scroll.vue
<template>
  <div ref="root" class="svc-scroll__wrapper">
      <div class="svc-scroll__scroller sv-drag-target-skipped" @scroll="() => model.onScrollContainer()">
        <div class="svc-scroll__container">
          <slot />
        </div>
      </div>
      <div class="svc-scroll__scrollbar" @scroll="() => model.onScrollScrollbar()">
        <div class="svc-scroll__scrollbar-sizer">
        </div>
      </div>
    </div>
</template>
<script lang="ts" setup>
import { ScrollViewModel } from "survey-creator-core";
import { onMounted, onUnmounted, ref } from "vue";

const model = new ScrollViewModel();
const root = ref<HTMLDivElement>();
onMounted(() => {
  model.setRootElement(root.value as HTMLDivElement);
});
onUnmounted(() => {
  model.setRootElement(undefined as any);
  model.unsubscribeRootElement();
});
</script>
