// packages/survey-creator-angular/src/components/surface-placeholder.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, EmbeddedViewContentComponent } from "survey-angular-ui";
import { editorLocalization } from "survey-creator-core";

@Component({
  selector: "svc-surface-placeholder",
  templateUrl: "./surface-placeholder.component.html",
  styles: [":host { display: none; }"]
})
export class SurfacePlaceholderComponent extends EmbeddedViewContentComponent {
  @Input() name!: string;
  @Input() placeholderTitleText!: string;
  @Input() placeholderDescriptionText!: string;
}
AngularComponentFactory.Instance.registerComponent("svc-surface-placeholder", SurfacePlaceholderComponent);

<ng-template #template>
  <div class="svc-surface-placeholder">
    <div class="svc-surface-placeholder__image" [class]="'svc-surface-placeholder__image--' + name"></div>
    <div class="svc-surface-placeholder__text">
      <div class="svc-surface-placeholder__title">{{placeholderTitleText}}</div>
      <div class="svc-surface-placeholder__description">{{placeholderDescriptionText}}</div>
    </div>
  </div>
</ng-template>

// packages/survey-creator-vue/src/components/SurfacePlaceholder.vue
<template>
  <div class="svc-surface-placeholder">
    <div class="svc-surface-placeholder__image" :class="'svc-surface-placeholder__image--' + name"></div>
    <div class="svc-surface-placeholder__text">
      <div class="svc-surface-placeholder__title">{{placeholderTitleText}}</div>
      <div class="svc-surface-placeholder__description">{{placeholderDescriptionText}}</div>
    </div>
  </div>
</template>

<script lang="ts" setup>
const props = defineProps<{
  name: string;
  placeholderTitleText: string;
  placeholderDescriptionText: string;
}>();
</script>
