// packages/survey-creator-react/src/components/SurfacePlaceholder.tsx
import * as React from "react";
import { ReactElementFactory } from "survey-react-ui";

interface ISurfacePlaceholderProps {
  name: string;
  placeholderTitleText: string;
  placeholderDescriptionText: string;
}

export class SurfacePlaceholder extends React.Component<ISurfacePlaceholderProps, any> {
  constructor(props: ISurfacePlaceholderProps) {
    super(props);
  }
  render(): React.JSX.Element {
    return (
      <div className="svc-surface-placeholder" >
        <div className={"svc-surface-placeholder__image svc-surface-placeholder__image--" + this.props.name}></div >
        <div className="svc-surface-placeholder__text">
          <div className="svc-surface-placeholder__title">{this.props.placeholderTitleText}</div>
          <div className="svc-surface-placeholder__description">{this.props.placeholderDescriptionText}</div>
        </div>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-surface-placeholder",
  (props: ISurfacePlaceholderProps) => {
    return React.createElement(SurfacePlaceholder, props);
  }
);

// packages/survey-creator-vue/src/components/SurfacePlaceholder.vue
<template>
  <div class="svc-surface-placeholder">
    <div class="svc-surface-placeholder__image" :class="'svc-surface-placeholder__image--' + name"></div>
    <div class="svc-surface-placeholder__text">
      <div class="svc-surface-placeholder__title">{{placeholderTitleText}}</div>
      <div class="svc-surface-placeholder__description">{{placeholderDescriptionText}}</div>
    </div>
  </div>
</template>

<script lang="ts" setup>
const props = defineProps<{
  name: string;
  placeholderTitleText: string;
  placeholderDescriptionText: string;
}>();
</script>
