// packages/survey-creator-react/src/Switcher.tsx
import * as React from "react";
import { Switcher } from "survey-creator-core";
import { Base } from "survey-core";
import { ReactElementFactory, attachKey2click, SurveyElementBase } from "survey-react-ui";

interface ISwitcherComponentProps {
  item: Switcher;
}

export class SwitcherComponent extends SurveyElementBase<ISwitcherComponentProps, any> {
  get item(): Switcher {
    return this.props.item;
  }

  protected getStateElement(): Base {
    return this.item;
  }

  renderElement() {
    const tooltip = this.item.tooltip || this.item.title;
    const title = this.item.hasTitle ? <span className="svc-switcher__title">{this.item.title}</span> : null;
    const button = attachKey2click(
      <button
        className={this.item.getActionBarItemCss()}
        type="button"
        disabled={this.item.disabled}
        onClick={(args) => this.item.action(this.item, this.item.getIsTrusted(args))}
        title={tooltip}
        aria-checked={this.item.ariaChecked}
        aria-expanded={this.item.ariaExpanded}
        role={this.item.ariaRole}
      >
        <div className={this.item.getSwitcherIconCss()}>
          <div className="svc-switcher__icon-thumb"></div>
        </div>
        {title}
      </button>, this.item, { processEsc: false });

    return button;
  }
}

export default SwitcherComponent;

ReactElementFactory.Instance.registerElement("svc-switcher", (props) => {
  return React.createElement(SwitcherComponent, props);
});

// packages/survey-creator-vue/src/components/Switcher.vue
<template>
  <button
    class="svc-switcher"
    :class="item.getActionBarItemCss()"
    type="button"
    v-on:click="
      (args: any) => {
        item.action(item, !!args.pointerType);
      }
    "
    v-on:keyup="
      (evt) => {
        evt.stopPropagation();
      }
    "
    v-bind:disabled="item.disabled"
    v-bind:title="item.tooltip || item.title"
    v-bind:aria-checked="item.ariaChecked"
    v-bind:aria-expanded="item.ariaExpanded"
    v-bind:role="item.ariaRole"
    v-key2click="{ processEsc: false, disableTabStop: item.disableTabStop }"
  >
    <div :class="item.getSwitcherIconCss()">
      <div class="svc-switcher__icon-thumb"></div>
    </div>
    <span v-if="item.hasTitle" class="svc-switcher__title">{{ item.title }}</span>
  </button>
</template>
<script lang="ts">
export default {
  inheritAttrs: false,
};
</script>
<script lang="ts" setup>
import { useBase } from "@/base";
import type { Switcher } from "survey-creator-core";
const props = defineProps<{ item: Switcher }>();
useBase(() => props.item);
</script>
