// packages/survey-creator-react/src/tabs/JsonErrorItem.tsx
import * as React from "react";
import { ItemValue } from "survey-core";
import { ReactElementFactory, SurveyElementBase, SvgIcon, attachKey2click } from "survey-react-ui";

class ItemTemplateComponent extends SurveyElementBase<{ item: ItemValue }, any> {
  render() {
    const item = this.props.item;
    return (
      <>
        <SvgIcon iconName={item.iconName} iconSize={item.iconSize} className={"svc-json-error__icon"} ></SvgIcon>
        <div className="svc-json-error__container">
          <div className="svc-json-error__title">
            <span key={2}>{this.renderLocString(item.locTitle, undefined, "locString")}</span>
          </div>
          {this.renderFixButton()}
        </div>
      </>
    );
  }
  renderFixButton() {
    if (!this.props.item.data.showFixButton) return null;
    const item = this.props.item;
    return (attachKey2click(<button type="button" onClick={(event) => { event.stopPropagation(); item.data.fixError(); }} title={item.data.fixButtonTitle} className={"svc-json-error__fix-button"}>
      <SvgIcon iconName={item.data.fixButtonIcon} size={"auto"}></SvgIcon>
    </button>));
  }
}

ReactElementFactory.Instance.registerElement(
  "json-error-item",
  (props) => {
    return React.createElement(ItemTemplateComponent, props);
  }
);

// packages/survey-creator-angular/src/tabs/json/json-error-item.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { Action } from "survey-core";

@Component({
  selector: "svc-json-error-item",
  templateUrl: "./json-error-item.component.html",
  styles: [":host { display: none }"]
})
export class JsonErrorItemComponent extends BaseAngular<Action> {
  @Input() model!: Action;
  protected override getModel(): Action {
    return this.model;
  }

  fixError(event: Event) {
    event.stopPropagation();
    this.model.data.fixError();
  }
}

AngularComponentFactory.Instance.registerComponent("json-error-item", JsonErrorItemComponent);
<ng-template #template>
    <svg [iconName]="model.iconName" [size]="model.iconSize" [css]="'svc-json-error__icon'" sv-ng-svg-icon></svg>
    <div class="svc-json-error__container">
        <div class="svc-json-error__title">
            <sv-ng-string [model]="model.locTitle"></sv-ng-string>
        </div>
        <button type="button" *ngIf="model.data.showFixButton" (click)="fixError($event)" [key2click]
            [attr.title]="model.data.fixButtonTitle" [attr.aria-label]="model.data.fixButtonTitle"
            class="svc-json-error__fix-button">
            <svg [iconName]="model.data.fixButtonIcon" [size]="'auto'" sv-ng-svg-icon></svg>
        </button>
    </div>
</ng-template>
