// packages/survey-creator-angular/src/adorners/question-image.component.ts
import { AfterViewInit, Component, ElementRef, Input, ViewChild } from "@angular/core";
import { AngularComponentFactory, EmbeddedViewContentComponent } from "survey-angular-ui";
import { QuestionImageAdornerViewModel } from "survey-creator-core";
import { QuestionDesignerComponent } from "../question.component";

@Component({
  selector: "svc-image-question",
  templateUrl: "../question.component.html",
  styles: [":host { display: none; }"]
})
export class QuestionImageDesignerComponent extends QuestionDesignerComponent {
  protected override createModel(): void {
    if (this.componentData) {
      this.adorner = new QuestionImageAdornerViewModel(this.creator, this.model, <any>null);
    }
  }
  public override adornerComponent = "svc-image-question-adorner";
  public override get placeholderComponent(): string {
    return "file-question";
  }
  public override get placeholderComponentData() {
    return { model: (<QuestionImageAdornerViewModel>this.adorner).filePresentationModel };
  }
  public override get showPlaceholderComponent(): boolean {
    return !!this.placeholderComponentData;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-image-question", QuestionImageDesignerComponent);

@Component({
  selector: "svc-image-question-adorner",
  templateUrl: "./question-image.component.html",
  styles: [":host { display: none; }"]
})
export class QuestionImageAdornerDesignerComponent extends EmbeddedViewContentComponent {
  @Input() adorner!: QuestionImageAdornerViewModel;
  @Input() question!: any;
}

AngularComponentFactory.Instance.registerComponent("svc-image-question-adorner", QuestionImageAdornerDesignerComponent);


<ng-template #template>
  <div class="svc-image-question-controls" *ngIf="!adorner.isUploading && !adorner.isEmptyElement">
    <ng-container *ngIf="adorner.allowEdit">
      <input type="file" aria-hidden="true" tabindex="-1" [accept]="adorner.acceptedTypes"
        class="svc-choose-file-input" />
      <span class="svc-context-button" [key2click] [attr.title]="undefined" [attr.aria-label]="undefined">
        <svg [iconName]="'icon-file'" [size]="'auto'" (click)="adorner.chooseFile(adorner)" sv-ng-svg-icon></svg>
      </span>
    </ng-container>
  </div>
  <div class="svc-image-question__loading-placeholder" *ngIf="adorner.isUploading && !adorner.isEmptyElement">
    <div class="svc-image-question__loading">
      <sv-ng-loading-indicator></sv-ng-loading-indicator>
    </div>
  </div>
</ng-template>

// packages/survey-creator-react/src/adorners/QuestionImage.tsx
import {
  QuestionImageAdornerViewModel,
  QuestionAdornerViewModel
} from "survey-creator-core";
import * as React from "react";
import { attachKey2click, LoadingIndicatorComponent, ReactElementFactory, ReactQuestionFactory, SvgIcon } from "survey-react-ui";
import {
  QuestionAdornerComponent,
  QuestionAdornerComponentProps
} from "./Question";
import { Base } from "survey-core";

export class QuestionImageAdornerComponent extends QuestionAdornerComponent {
  protected createQuestionViewModel(props: any): QuestionAdornerViewModel {
    return new QuestionImageAdornerViewModel(
      props.componentData,
      props.question as any,
      null);
  }
  public get imageModel(): QuestionImageAdornerViewModel {
    return this.model as QuestionImageAdornerViewModel;
  }
  protected renderHeader(): React.JSX.Element {
    return (<React.Fragment>
      <input
        type="file"
        aria-hidden="true"
        tabIndex={-1}
        accept={this.imageModel.acceptedTypes}
        className="svc-choose-file-input"
        style={{
          position: "absolute",
          opacity: 0,
          width: "1px",
          height: "1px",
          overflow: "hidden"
        }}
      />

      {super.renderHeader()}
    </React.Fragment>);
  }
  renderLoadingPlaceholder(): React.JSX.Element {
    return (<div className="svc-image-question__loading-placeholder">
      <div className="svc-image-question__loading">
        <LoadingIndicatorComponent></LoadingIndicatorComponent>
      </div>
    </div>);
  }
  renderChooseButton(): React.JSX.Element {
    return (<div className="svc-image-question-controls">
      {this.model.allowEdit ? attachKey2click(<span
        className="svc-context-button"
        onClick={() => this.imageModel.chooseFile(this.imageModel)}
      >
        <SvgIcon size={"auto"} iconName={"icon-choosefile"}></SvgIcon>
      </span>) : null}
    </div>);
  }
  renderElementPlaceholder(): React.JSX.Element {
    return this.imageModel.isUploading ? this.renderLoadingPlaceholder() : this.renderChooseButton();
  }
  protected getStateElements(): Array<Base> {
    return [this.model, this.imageModel.filePresentationModel];
  }

  protected renderElementContent(): React.JSX.Element {
    if (this.imageModel.isEmptyElement) {
      const fileQuestion = ReactQuestionFactory.Instance.createQuestion("file", {
        creator: this.imageModel.question.survey,
        isDisplayMode: false,
        question: this.imageModel.filePresentationModel
      });
      return (<>
        {fileQuestion}
      </>);
    } else {
      return (
        <>
          {this.props.element}
          {this.renderElementPlaceholder()}
        </>
      );
    }
  }
}

ReactElementFactory.Instance.registerElement(
  "svc-image-question",
  (props: QuestionAdornerComponentProps) => {
    return React.createElement(QuestionImageAdornerComponent, props);
  }
);
