// packages/survey-creator-vue/src/adorners/CellQuestionDropdown.vue
<template>
  <div class="svc-question__adorner">
    <div class="svc-question__content svc-question__content--in-popup">
      <SvComponent
        :name="componentName"
        v-bind="componentData"
      ></SvComponent>
      <div class="svc-question__dropdown-choices">
        <div
          v-for="item in element.visibleChoices"
          :key="item.value"
          class="svc-question__dropdown-choice"
        >
          <SvComponent
            :name="getItemValueComponentName(item)"
            v-bind="getItemValueComponentData(item)"
          ></SvComponent>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import type { ItemValue, QuestionDropdownModel } from "survey-core";
import { useBase } from "survey-vue3-ui";
import { computed } from "vue";

const props = defineProps<{
  componentName: string;
  componentData: any;
}>();

const element = computed<QuestionDropdownModel>(
  () => props.componentData.element
);
const defaultItemComponentName = "survey-radiogroup-item";
const getItemValueComponentName = (item: ItemValue) => {
  return (
    element.value.getItemValueWrapperComponentName(item) ||
    defaultItemComponentName
  );
};
const getItemValueComponentData = (item: ItemValue) => {
  return {
    componentName: defaultItemComponentName,
    componentData: {
      question: element.value,
      item,
      data: element.value.getItemValueWrapperComponentData(item),
    },
  };
};
useBase(() => element.value);
</script>

// packages/survey-creator-angular/src/adorners/cell-question-dropdown.component.ts
import { Component } from "@angular/core";
import { ItemValue, QuestionDropdownModel } from "survey-core";
import { AngularComponentFactory } from "survey-angular-ui";
import { CellQuestionComponent } from "./cell-question.component";

@Component({
  selector: "svc-cell-dropdown-question",
  templateUrl: "./cell-question-dropdown.component.html",
  styles: [":host { display: none; }"]
})
export class CellQuestionDropdownComponent extends CellQuestionComponent<QuestionDropdownModel> {
  public getItemValueComponentName(item: ItemValue): string {
    return this.model.getItemValueWrapperComponentName(item) || "sv-ng-selectbase-item";
  }
  public getItemValueComponentData(item: ItemValue): any {
    return {
      componentName: "sv-ng-selectbase-item",
      componentData: {
        question: this.model,
        model: item,
        inputType: "radio",
        data: this.model.getItemValueWrapperComponentData(item)
      }
    };
  }
}
AngularComponentFactory.Instance.registerComponent("svc-cell-dropdown-question", CellQuestionDropdownComponent);
<ng-template #template>
  <div class="svc-question__adorner">
    <div class="svc-question__content svc-question__content--selected-no-border">
      <ng-template [component]="{ name: componentName, data: componentData }"></ng-template>
      <div class="svc-question__dropdown-choices">
          <div *ngFor="let item of model.visibleChoices"class="svc-question__dropdown-choice">
            <ng-template [component]="{ name: getItemValueComponentName(item), data: getItemValueComponentData(item) }"></ng-template>
          </div>
    </div>

    </div>
  </div>
</ng-template>
