// packages/survey-creator-vue/src/adorners/ImageItemValue.vue
<template>
  <div
    @pointerdown="adorner.onPointerDown($event)"
    :class="adorner.getRootCss()"
    :data-sv-drop-target-item-value="adorner.isDraggable ? item.value : null"
    ref="root"
  >
    <div
      class="svc-image-item-value-wrapper__ghost"
      :style="newItemStyle"
    ></div>

    <div class="svc-image-item-value-wrapper__content">
      <input
        type="file"
        aria-hidden="true"
        tabindex="-1"
        :accept="adorner.acceptedTypes"
        class="svc-choose-file-input"
      />

      <template v-if="!adorner.isNew && !adorner.isUploading">
        <div v-if="!adorner.isNew" class="svc-image-item-value__item">
          <component :is="componentName" v-bind="componentData"></component>
        </div>
        <span
          v-if="adorner.isDraggable && adorner.canRenderControls"
          class="svc-context-button svc-image-item-value-controls__drag-area-indicator"
          @pointerdown="adorner.onPointerDown($event)"
          :title="undefined"
          :aria-label="undefined"
        >
          <sv-svg-icon
            :iconName="'icon-drag-area-indicator'"
            :size="24"
          ></sv-svg-icon>
        </span>
        <div v-if="adorner.canRenderControls" class="svc-context-container svc-image-item-value-controls">
          <span
            class="svc-context-button"
            @click="adorner.chooseFile(adorner)"
            v-key2click
            :title="undefined"
            :aria-label="undefined"
          >
            <sv-svg-icon role="button" :iconName="'icon-file'" :size="24" :title="adorner.selectFileTitle"></sv-svg-icon>
          </span>
          <span
            class="svc-context-button svc-context-button--danger"
            @click="adorner.remove(adorner)"
            v-key2click
            :title="undefined"
            :aria-label="undefined"
          >
            <sv-svg-icon role="button" :iconName="'icon-delete'" :size="24" :title="adorner.removeFileTitle"></sv-svg-icon>
          </span>
        </div>
      </template>

      <template v-if="adorner.isNew || adorner.isUploading">
        <div
          class="svc-image-item-value__item"
          @dragover="adorner.onDragOver($event)"
          @dragleave="adorner.onDragLeave($event)"
          @drop="adorner.onDrop($event)"
        >
          <div class="sd-imagepicker__item sd-imagepicker__item--inline">
            <label class="sd-imagepicker__label">
              <div :style="newItemStyle" class="sd-imagepicker__image">
                <div
                  class="svc-image-item-value__loading"
                  v-if="adorner.isUploading"
                >
                  <sv-loading-indicator></sv-loading-indicator>
                </div>
              </div>
            </label>
          </div>
        </div>

        <div
          class="svc-image-item-value-controls"
          @pointerdown="(event) => event.stopPropagation()"
        >
          <span
            class="svc-context-button svc-image-item-value-controls__add"
            v-if="adorner.allowAdd && !adorner.isUploading"
            v-key2click
            @click="adorner.chooseNewFile(adorner)"
            :title="undefined"
            :aria-label="undefined"
          >
            <sv-svg-icon :iconName="'icon-add-lg'" :size="24" :title="adorner.addFileTitle"></sv-svg-icon>
          </span>
        </div>
      </template>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { useCreatorModel } from "@/creator-model";
import type { ImageItemValue, QuestionImagePickerModel } from "survey-core";
import {
  SurveyCreatorModel,
  ImageItemValueWrapperViewModel,
} from "survey-creator-core";
import { computed, onMounted, ref } from "vue";

const props = defineProps<{
  componentName: string;
  componentData: {
    data: {
      creator: SurveyCreatorModel;
    };
    question: QuestionImagePickerModel;
    item: ImageItemValue;
  };
}>();
const creator = computed(() => props.componentData.data.creator);
const question = computed(() => props.componentData.question);
const item = computed(() => props.componentData.item);
const root = ref<HTMLDivElement>();
const adorner = useCreatorModel(
  () =>
    new ImageItemValueWrapperViewModel(
      creator.value,
      question.value,
      item.value,
      null as any,
      null as any
    ),
  [() => creator.value, () => question.value, () => item.value],
  (value) => {
    value.dispose();
  }
);

const newItemStyle = computed(() => {
  const needStyle = !adorner.value.getIsNewItemSingle();
  return {
    width: needStyle ? question.value.renderedImageWidth + "px" : undefined,
    height: needStyle ? question.value.renderedImageHeight + "px" : undefined,
  };
});

onMounted(() => {
  if (root.value) {
    adorner.value.itemsRoot = root.value;
  }
});
</script>

// packages/survey-creator-angular/src/adorners/image-item-value.component.ts

import { Component, ElementRef, Input, ViewChild } from "@angular/core";
import { AngularComponentFactory } from "survey-angular-ui";
import { ImageItemValue, QuestionImagePickerModel } from "survey-core";
import { SurveyCreatorModel, ImageItemValueWrapperViewModel } from "survey-creator-core";
import { CreatorModelComponent } from "../creator-model.component";

@Component({
  selector: "svc-image-item-value",
  templateUrl: "./image-item-value.component.html",
  styles: [":host { display: none; }"]
})
export class ImageItemValueDesignerComponent extends CreatorModelComponent<ImageItemValueWrapperViewModel> {
  @Input() componentName!: string;
  @Input() componentData!: any;
  @ViewChild("container", { read: ElementRef }) container!: ElementRef;
  public adorner!: ImageItemValueWrapperViewModel;
  private get creator(): SurveyCreatorModel {
    return this.componentData.data.creator;
  }
  public get question(): QuestionImagePickerModel {
    return this.componentData.question;
  }
  public get item(): ImageItemValue {
    return this.componentData.model;
  }
  protected createModel(): void {
    if (this.componentData) {
      this.adorner = new ImageItemValueWrapperViewModel(this.creator, this.question, this.item, <any>null, <any>null);
    }
  }
  protected getPropertiesToTrack(): string[] {
    return ["creator", "question", "item"];
  }
  protected getModel(): ImageItemValueWrapperViewModel {
    return this.adorner;
  }

  get showDragDropGhostOnTop(): boolean {
    return this.adorner.ghostPosition === "top";
  }
  get showDragDropGhostOnBottom(): boolean {
    return this.adorner.ghostPosition === "bottom";
  }
  public blockEvent(event: MouseEvent): void {
    event.stopPropagation();
  }

  getNewItemStyle(): any {
    const needStyle = !this.adorner.getIsNewItemSingle();
    return { width: needStyle ? this.question.renderedImageWidth + "px" : undefined, height: needStyle ? this.question.renderedImageHeight + "px" : undefined };
  }
  public ngAfterViewInit() {
    this.adorner.itemsRoot = this.container.nativeElement;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-image-item-value", ImageItemValueDesignerComponent);

<ng-template #template>
  <div (pointerdown)="adorner.onPointerDown($event)" [class]="adorner.getRootCss()"
    [attr.data-sv-drop-target-item-value]="adorner.isDraggable ? this.item.value : null" #container>
    <div class="svc-image-item-value-wrapper__ghost" [style]="getNewItemStyle()"></div>

    <div class="svc-image-item-value-wrapper__content">
      <input type="file" aria-hidden="true" tabindex="-1" [accept]="adorner.acceptedTypes"
        class="svc-choose-file-input" />

      <ng-container *ngIf="!adorner.isNew && !adorner.isUploading">
        <div *ngIf="!adorner.isNew" class="svc-image-item-value__item">
          <ng-template [component]="{ name: componentName, data: componentData }"></ng-template>
        </div>
        <span *ngIf="adorner.isDraggable && adorner.canRenderControls"
          class="svc-context-button svc-image-item-value-controls__drag-area-indicator"
          (pointerdown)="adorner.onPointerDown($event)" [attr.title]="undefined" [attr.aria-label]="undefined">
          <svg [iconName]="'icon-drag-24x24'" [size]="24" sv-ng-svg-icon></svg>
        </span>
        <div *ngIf="adorner.canRenderControls" class="svc-context-container svc-image-item-value-controls">
          <ng-container *ngIf="adorner.allowRemove && !adorner.isUploading">
            <span class="svc-context-button" (click)="adorner.chooseFile(adorner)" [key2click] [attr.title]="undefined"
              [attr.aria-label]="undefined">
              <svg role="button" [iconName]="'icon-choosefile'" [size]="24" [title]="adorner.selectFileTitle" sv-ng-svg-icon></svg>
            </span>
            <span class="svc-context-button svc-context-button--danger" (click)="adorner.remove(adorner)" [key2click]
              [attr.title]="undefined" [attr.aria-label]="undefined">
              <svg role="button" [iconName]="'icon-delete'" [size]="24" [title]="adorner.removeFileTitle" sv-ng-svg-icon></svg>
            </span>
          </ng-container>
        </div>
      </ng-container>

      <ng-container *ngIf="adorner.isNew || adorner.isUploading">
        <div class="svc-image-item-value__item"
          data-bind="event: { dragover: dragover, drop: drop, dragleave: dragleave }">
          <div class="sd-imagepicker__item sd-imagepicker__item--inline">
            <label class="sd-imagepicker__label">
              <div [style]="getNewItemStyle()" class="sd-imagepicker__image">
                <div class="svc-image-item-value__loading" *ngIf="adorner.isUploading">
                  <sv-ng-loading-indicator></sv-ng-loading-indicator>
                </div>
              </div>
            </label>
          </div>
        </div>

        <div class="svc-image-item-value-controls" data-bind="event: { pointerdown: blockEvent }">
          <span class="svc-context-button svc-image-item-value-controls__add"
            *ngIf="adorner.allowAdd && !adorner.isUploading" [key2click] (click)="adorner.chooseNewFile(adorner)"
            [attr.title]="undefined" [attr.aria-label]="undefined">
            <svg [iconName]="'icon-add-lg'" [size]="48" sv-ng-svg-icon [title]="adorner.addFileTitle"></svg>
          </span>
        </div>
      </ng-container>
    </div>
  </div>
</ng-template>
