// packages/survey-creator-vue/src/adorners/MatrixCell.vue
<template>
  <div
    tabindex="-1"
    class="svc-matrix-cell"
    @click="adorner?.selectContext(adorner, $event)"
    @mouseover="adorner?.hover($event, $event.currentTarget)"
    @mouseleave="adorner?.hover($event, $event.currentTarget)"
  >
    <div
      class="svc-matrix-cell--selected"
      :class="{ 'svc-visible': adorner?.isSelected }"
    ></div>
    <slot></slot>
    <div
      v-if="adorner?.isSupportCellEditor"
      class="svc-matrix-cell__question-controls"
    >
      <span
        class="svc-matrix-cell__question-controls-button"
        @click="adorner.editQuestion(adorner, $event)"
        v-key2click
      >
        <sv-svg-icon :iconName="'icon-edit'" :size="24"></sv-svg-icon>
      </span>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { CreatorBase, MatrixCellWrapperViewModel } from "survey-creator-core";
import type { QuestionSelectBase } from "survey-core";
import { computed } from "vue";
import { useCreatorModel } from "@/creator-model";

const props = defineProps<{
  componentData: any;
}>();
const creator = computed<CreatorBase>(() => props.componentData.creator);
const row = computed(() => props.componentData.row);
const column = computed(() => props.componentData.column);
const element = computed<QuestionSelectBase>(() => props.componentData.element);
const question = computed<QuestionSelectBase>(
  () => props.componentData.question
);
const adorner = useCreatorModel(
  () =>
    props.componentData
      ? new MatrixCellWrapperViewModel(
          creator.value,
          element.value,
          question.value,
          row.value,
          column.value || element.value.cell?.column
        )
      : undefined,
  [
    () => creator.value,
    () => row.value,
    () => column.value,
    () => question.value,
  ]
);
</script>

// packages/survey-creator-angular/src/adorners/matrix-cell.component.ts
import { ChangeDetectorRef, Component, Input, TemplateRef, ViewContainerRef } from "@angular/core";
import { AngularComponentFactory, BaseAngular, EmbeddedViewContentComponent } from "survey-angular-ui";
import { ItemValue, PageModel, PanelModel, Question, QuestionSelectBase, SurveyModel } from "survey-core";
import { CreatorBase, ItemValueWrapperViewModel, MatrixCellWrapperViewModel, QuestionAdornerViewModel } from "survey-creator-core";
import { CreatorModelComponent } from "../creator-model.component";

@Component({
  selector: "svc-matrix-cell",
  templateUrl: "./matrix-cell.component.html",
  styles: [":host { display: none; }"]
})
export class MatrixCellComponent extends CreatorModelComponent<MatrixCellWrapperViewModel> {
  @Input() componentName!: string;
  @Input() componentData!: any;
  @Input() contentTempl!: TemplateRef<any>;
  public adorner!: MatrixCellWrapperViewModel;
  private get creator(): CreatorBase {
    return this.componentData.creator;
  }
  public get question(): QuestionSelectBase {
    return this.componentData.question;
  }
  public get isSupportCellEditor(): boolean {
    return this.componentData.isSupportCellEditor;
  }
  public get column() {
    return this.componentData.column;
  }

  public get row() {
    return this.componentData.row;
  }
  protected createModel(): void {
    if (this.componentData) {
      this.adorner = new MatrixCellWrapperViewModel(this.creator, null, this.question, this.row, this.column);
    }
  }
  protected getPropertiesToTrack(): string[] {
    return ["creator", "row", "column", "question"];
  }
  protected getModel(): MatrixCellWrapperViewModel {
    return this.adorner;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-matrix-cell", MatrixCellComponent);

<ng-template #template>
  <div tabindex="-1" class="svc-matrix-cell" (click)="adorner.selectContext(adorner, $event)"
    (mouseover)="adorner.hover($event, $event.currentTarget)"
    (mouseleave)="adorner.hover($event, $event.currentTarget)">
    <div class="svc-matrix-cell--selected" [class.svc-visible]="adorner.isSelected"></div>
    <ng-container *ngTemplateOutlet="contentTempl"></ng-container>
    <div *ngIf="isSupportCellEditor" class="svc-matrix-cell__question-controls">
      <span class="svc-matrix-cell__question-controls-button" (click)="adorner.editQuestion(adorner)" [key2click]>
        <svg [iconName]="'icon-edit'" [size]="24" [size]="24" sv-ng-svg-icon></svg>
      </span>
    </div>
  </div>
</ng-template>
