// packages/survey-creator-react/src/adorners/TranslationDropdownQuestion.tsx
import * as React from "react";
import { Base, ItemValue, QuestionSelectBase } from "survey-core";
import { TranslationDropdownViewModel, translationDropdownComponentName } from "survey-creator-core";
import { ReactElementFactory } from "survey-react-ui";
import { QuestionAdornerComponentProps } from "./Question";
import { CreatorModelElement } from "../ModelElement";

// The flattened choice list of a dropdown/tagbox question in the translation side-by-side
// panes. Chrome-free: no designer adorner, no itemvalue wrappers - the choice texts render
// through the survey's string renderer (editable in the target pane, plain in the source one).
export class TranslationDropdownQuestionComponent extends CreatorModelElement<
  QuestionAdornerComponentProps,
  any
> {
  model: TranslationDropdownViewModel;
  protected createModel(props: any): void {
    if (!!this.model) {
      this.model.dispose();
    }
    this.model = new TranslationDropdownViewModel(
      props.question as QuestionSelectBase,
      props.componentData ? props.componentData.translation : undefined
    );
  }
  protected getUpdatedModelProps(): string[] {
    return ["question", "componentData"];
  }
  protected getStateElement(): Base {
    return this.model;
  }
  componentWillUnmount(): void {
    super.componentWillUnmount();
    this.model.dispose();
  }
  renderElement(): React.JSX.Element {
    const question = this.props.question as QuestionSelectBase;
    const textStyle = (this.props.question as any).textStyle;
    return (
      <React.Fragment>
        {this.props.element}
        <div className="st-dropdown-choices--wrapper">
          <div className="svc-question__dropdown-choices">
            {this.model.getRenderedItems().map(
              (item: ItemValue, index: number) => (
                <div className={this.model.getChoiceCss()} key={`translation_choice_${index}`}>
                  {ReactElementFactory.Instance.createElement(this.model.itemComponent, {
                    question: question,
                    cssClasses: question.cssClasses,
                    isDisplayMode: true,
                    item: item,
                    textStyle: textStyle,
                    index: index,
                    isChecked: false
                  })}
                </div>
              )
            )}
          </div>
          {this.model.needToCollapse ?
            ReactElementFactory.Instance.createElement("sv-action-bar-item", { item: this.model.collapseAction }) : null}
        </div>
      </React.Fragment>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  translationDropdownComponentName,
  (props: QuestionAdornerComponentProps) => {
    return React.createElement(TranslationDropdownQuestionComponent, props);
  }
);

// packages/survey-creator-angular/src/adorners/translation-dropdown-question.component.ts
import { Component, Input, TemplateRef } from "@angular/core";
import { CreatorModelComponent } from "../creator-model.component";
import { AngularComponentFactory } from "survey-angular-ui";
import { TranslationDropdownViewModel } from "survey-creator-core";
import { QuestionSelectBase } from "survey-core";

// The flattened choice list of a dropdown/tagbox question in the translation side-by-side
// panes. Chrome-free: no designer adorner and no itemvalue wrappers - the choice texts render
// through the survey's string renderer (editable in the target pane, plain in the source one).
@Component({
  selector: "svc-translation-dropdown-question",
  templateUrl: "./translation-dropdown-question.component.html",
  styles: [":host { display: none; }"]
})
export class TranslationDropdownQuestionComponent extends CreatorModelComponent<TranslationDropdownViewModel> {
  @Input() componentName!: string;
  @Input() componentData!: any;
  @Input() contentTempl!: TemplateRef<any>;
  public adorner!: TranslationDropdownViewModel;

  public get question(): QuestionSelectBase {
    return this.componentData.model;
  }
  protected createModel(): void {
    if (this.componentData) {
      if (!!this.adorner) {
        this.adorner.dispose();
      }
      this.adorner = new TranslationDropdownViewModel(
        this.componentData.model,
        this.componentData.data ? this.componentData.data.translation : undefined
      );
    }
  }
  protected getPropertiesToTrack(): string[] {
    return ["componentData"];
  }
  protected getModel(): TranslationDropdownViewModel {
    return this.adorner;
  }
  override ngOnDestroy(): void {
    super.ngOnDestroy();
    if (!!this.adorner) {
      this.adorner.dispose();
    }
  }
}

AngularComponentFactory.Instance.registerComponent("svc-translation-dropdown-question", TranslationDropdownQuestionComponent);

<ng-template #template>
  <ng-container *ngTemplateOutlet="contentTempl"></ng-container>
  <div class="st-dropdown-choices--wrapper">
    <div class="svc-question__dropdown-choices">
      <div *ngFor="let item of adorner.getRenderedItems()" [class]="adorner.getChoiceCss()">
        <ng-template
          [component]="{ name: 'sv-ng-selectbase-item', data: { question: question, model: item, inputType: adorner.itemInputType } }">
        </ng-template>
      </div>
    </div>
    <ng-container *ngIf="adorner.needToCollapse">
      <ng-template [component]="{ name: 'sv-action-bar-item', data: { model: adorner.collapseAction } }"></ng-template>
    </ng-container>
  </div>
</ng-template>
