// packages/survey-creator-angular/src/tabs/translation/translate-from-action.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { Action } from "survey-core";

@Component({
  selector: "svc-translate-from-action",
  templateUrl: "./translate-from-action.component.html",
  styles: [":host { display: none; }"]
})
export class TranslateFromAction extends BaseAngular<Action> {
  @Input() model!: Action;

  protected getModel(): Action {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-translate-from-action", TranslateFromAction);


<ng-template #template>
    <div [class]="model.data.containerCss">
        <span [class]="model.data.additionalTitleCss">{{model.data.additionalTitle}}</span>
        <sv-action-bar-item-dropdown [model]="model"></sv-action-bar-item-dropdown>
    </div>
</ng-template>

// packages/survey-creator-react/src/tabs/translation/TranslateFromAction.tsx
import React from "react";
import { Action, Base } from "survey-core";
import { SurveyElementBase, SvgIcon, attachKey2click, ReactElementFactory } from "survey-react-ui";

export class TranslateFromAction extends SurveyElementBase<{ item: Action }, any> {
  get item(): Action {
    return this.props.item;
  }
  protected getStateElement(): Base {
    return this.item;
  }

  renderElement() {
    const item = this.item;
    return (
      <div className={item.data.containerCss}>
        <span className={item.data.additionalTitleCss}>{item.data.additionalTitle}</span>
        { ReactElementFactory.Instance.createElement("sv-action-bar-item-dropdown", { item: this.item })}
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-translate-from-action", (props) => {
  return React.createElement(TranslateFromAction, props);
});
