// packages/survey-creator-vue/src/tabs/translation/Translation.vue
<template>
  <div class="svc-creator-tab__content svc-translation-tab" :class="model.isEmpty ? 'svc-translation-tab--empty' : ''">
    <SurfacePlaceholder v-if="model.isEmpty" :name="'translation'" :placeholderTitleText="model.placeholderTitleText" :placeholderDescriptionText="model.placeholderDescriptionText" />
    <div v-if="!model.isEmpty && stringsModel" class="st-content">
      <div class="svc-flex-column st-strings-wrapper">
        <div class="svc-flex-row st-strings-header">
          <SurveyComponent :key="stringsModel.stringsHeaderSurvey?.elementIdPrefix" :model="stringsModel.stringsHeaderSurvey"></SurveyComponent>
        </div>
        <div class="svc-flex-row svc-plugin-tab__content st-strings">
          <SurveyComponent :key="stringsModel.stringsSurvey?.elementIdPrefix" :model="stringsModel.stringsSurvey"></SurveyComponent>
        </div>
      </div>
    </div>
    <div v-if="!model.isEmpty && sideBySideModel" class="st-side-by-side"
      :class="sideBySideModel.targetSurvey ? '' : 'st-side-by-side--no-target'">
      <div class="st-side-by-side__source" :key="sideBySideModel.sourceSurvey?.elementIdPrefix" :ref="setSourceScrollElement">
        <SurveyComponent :model="sideBySideModel.sourceSurvey"></SurveyComponent>
      </div>
      <div v-if="sideBySideModel.targetSurvey" class="st-side-by-side__target" :key="sideBySideModel.targetSurvey?.elementIdPrefix" :ref="setTargetScrollElement">
        <SurveyComponent :model="sideBySideModel.targetSurvey"></SurveyComponent>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import type { TranslationBase, TranslationSideBySide } from "survey-creator-core";
import { computed } from "vue";
import { useBase, SurveyComponent } from "survey-vue3-ui";
import SurfacePlaceholder from "../../components/SurfacePlaceholder.vue";
const props = defineProps<{ model: TranslationBase }>();
useBase(() => props.model);
const sideBySideModel = computed<TranslationSideBySide | undefined>(() =>
  props.model.isSideBySideForms ? (props.model as TranslationSideBySide) : undefined
);
// The strings-grid model: the tab model itself in the default mode and in the side-by-side grid view.
const stringsModel = computed<TranslationBase | undefined>(() =>
  sideBySideModel.value ? undefined : props.model
);
const setSourceScrollElement = (el: unknown) => {
  sideBySideModel.value?.setSourceScrollElement(el as HTMLElement);
};
const setTargetScrollElement = (el: unknown) => {
  sideBySideModel.value?.setTargetScrollElement(el as HTMLElement);
};
</script>

// packages/survey-creator-react/src/tabs/translation/Translation.tsx
import * as React from "react";
import { Base } from "survey-core";
import {
  ReactElementFactory,
  SurveyElementBase,
  Survey
} from "survey-react-ui";
import { TranslationBase, TranslationSideBySide } from "survey-creator-core";
import { SurfacePlaceholder } from "../../components/SurfacePlaceholder";

export class TabTranslationComponent extends SurveyElementBase<any, any> {
  private get model(): TranslationBase {
    return this.props.data || this.props.model;
  }
  protected getStateElement(): Base {
    return this.model;
  }
  renderElement(): React.JSX.Element {
    if (!this.model) return null;
    return (
      <div className={"svc-creator-tab__content svc-translation-tab" + (this.model.isEmpty ? " svc-translation-tab--empty" : "")}>
        {this.renderElementContent()}
      </div>
    );
  }
  renderElementContent(): React.JSX.Element {
    if (this.model.isEmpty) {
      return <SurfacePlaceholder name={"translation"} placeholderTitleText={this.model.placeholderTitleText} placeholderDescriptionText={this.model.placeholderDescriptionText} />;
    }
    if (this.model.isSideBySideForms) {
      return this.renderSideBySideContent(this.model as TranslationSideBySide);
    }
    // The side-by-side grid view reuses the default strings-grid markup.
    return this.renderStringsContent(this.model);
  }
  renderStringsContent(model: TranslationBase): React.JSX.Element {
    return (
      <div className="st-content">
        <div className="svc-flex-column st-strings-wrapper">
          <div className="svc-flex-row st-strings-header">
            <Survey key={model.stringsHeaderSurvey?.elementIdPrefix} model={model.stringsHeaderSurvey}></Survey>
          </div>
          <div className="svc-flex-row svc-plugin-tab__content st-strings">
            <Survey key={model.stringsSurvey?.elementIdPrefix} model={model.stringsSurvey}></Survey>
          </div>
        </div>
      </div>
    );
  }
  renderSideBySideContent(model: TranslationSideBySide): React.JSX.Element {
    return (
      <div className="st-side-by-side">
        <div key={model.sourceSurvey?.elementIdPrefix} className="st-side-by-side__source"
          ref={(el) => { model.setSourceScrollElement(el); }}>
          <Survey model={model.sourceSurvey}></Survey>
        </div>
        <div key={model.targetSurvey?.elementIdPrefix} className="st-side-by-side__target"
          ref={(el) => { model.setTargetScrollElement(el); }}>
          <Survey model={model.targetSurvey}></Survey>
        </div>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-tab-translation", (props) => {
  return React.createElement(TabTranslationComponent, props);
});
