// packages/survey-creator-angular/src/add-question.component.ts
import { Component, Input } from "@angular/core";
import { ActionBarItemComponent, AngularComponentFactory } from "survey-angular-ui";
import { CreatorModelComponent } from "./creator-model.component";
import { Base } from "survey-core";

@Component(
  {
    selector: "svc-add-new-question-btn",
    templateUrl: "./add-question.component.html",
    styles: [":host { display: none; }"]
  }
)
export class AddQuestionButtonComponent extends CreatorModelComponent<Base> {
  protected override getPropertiesToTrack(): string[] {
    return [];
  }
  protected override createModel(): void {
  }
  protected override getModel(): Base {
    return this.model.data;
  }
  @Input() model!: any;
  @Input() buttonClass?: string = "svc-btn";
  @Input() renderPopup?: boolean = true;
  public get adorner() {
    return this.model.data;
  }
  public addNewQuestion(event: any) {
    event.stopPropagation();
    this.adorner.addNewQuestion(this.adorner, event);
  }
}
AngularComponentFactory.Instance.registerComponent("svc-add-new-question-btn", AddQuestionButtonComponent);
<ng-template #template>
  <div
    *ngIf="adorner.showAddQuestionButton"
    [class]="'svc-element__add-new-question ' + buttonClass"
    (mouseover)="
      adorner.hoverStopper && adorner.hoverStopper($event, $event.currentTarget)
    "
  >
    <button [key2click] (click)="addNewQuestion($event)">
      <svg
        class="svc-panel__add-new-question-icon"
        [iconName]="'icon-add_24x24'"
        [size]="'auto'"
        sv-ng-svg-icon
      ></svg>
      <span class="svc-add-new-item-button__text">
        {{ adorner.addNewQuestionText }}
      </span>
    </button>
    <ng-template
      *ngIf="renderPopup"
      [component]="{
        name: 'svc-add-question-type-selector',
        data: {
          questionTypeSelectorModel: adorner.questionTypeSelectorModel,
          renderPopup: renderPopup
        }
      }"
    >
    </ng-template>
  </div>
  <ng-template
    *ngIf="!renderPopup"
    [component]="{
      name: 'svc-add-question-type-selector',
      data: {
        questionTypeSelectorModel: adorner.questionTypeSelectorModel,
        renderPopup: renderPopup
      }
    }"
  >
  </ng-template>
</ng-template>

// packages/survey-creator-vue/src/tabs/designer/AddQuestion.vue
<template>
  <div
    :class="rootCss"
    v-on:click="
      (e) => {
        item.data.addNewQuestion(item, e);
        e.stopPropagation();
      }
    "
    v-key2click
    v-on:mouseover="(e) => item.data.hoverStopper && item.data.hoverStopper(e, e.currentTarget)"
    role="button"
  >
    <SvComponent
      :is="'sv-svg-icon'"
      class="svc-panel__add-new-question-icon"
      :iconName="'icon-add_24x24'"
      :size="'auto'"
    ></SvComponent>
    <span class="svc-add-new-item-button__text">
      {{ item.data.addNewQuestionText }}
    </span>
    <SvComponent
      :is="'svc-add-question-type-selector'"
      v-if="needRenderPopup" 
      :questionTypeSelectorModel="item.data.questionTypeSelectorModel" :renderPopup="needRenderPopup"
    ></SvComponent>
  </div>
  <SvComponent
    :is="'svc-add-question-type-selector'"
    v-if="!needRenderPopup" :questionTypeSelectorModel="item.data.questionTypeSelectorModel" :renderPopup="needRenderPopup"
  ></SvComponent>
</template>
<script lang="ts" setup>
import { computed } from "vue";
import type { Action } from "survey-core";
import type {} from "survey-creator-core";
import { key2ClickDirective as vKey2click } from "survey-vue3-ui";
import { SvComponent } from "survey-vue3-ui";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ item: Action, buttonClass?: string, renderPopup?: any}>();
useBase(() => props.item.data);
const rootCss = computed(() => 'svc-element__add-new-question ' + (props.buttonClass || 'svc-btn'));
const needRenderPopup = computed(() => props.renderPopup === undefined || props.renderPopup !== false);
</script>
