// packages/survey-creator-angular/src/add-question-type-selector.component.ts
import { Component, Input } from "@angular/core";
import { ActionBarItemComponent, AngularComponentFactory } from "survey-angular-ui";
import { CreatorModelComponent } from "./creator-model.component";
import { Base } from "survey-core";

@Component(
  {
    selector: "svc-add-question-type-selector",
    templateUrl: "./add-question-type-selector.component.html",
    styles: [":host { display: none; }"]
  }
)
export class AddQuestionTypeSelectorComponent extends CreatorModelComponent<Base> {
  protected override getPropertiesToTrack(): string[] {
    return [];
  }
  protected override createModel(): void {
  }
  protected override getModel(): Base {
    return this.questionTypeSelectorModel;
  }
  @Input() questionTypeSelectorModel!: any;
  @Input() renderPopup?: boolean = true;
  public selectQuestionType(event: any) {
    event.stopPropagation();
    this.questionTypeSelectorModel.action();
  }
}
AngularComponentFactory.Instance.registerComponent("svc-add-question-type-selector", AddQuestionTypeSelectorComponent);
<ng-template #template>
  <span class="svc-question-type-selector">
    <button type="button" [key2click] (click)="selectQuestionType($event)"
      [attr.title]="questionTypeSelectorModel.title" [attr.aria-label]="questionTypeSelectorModel.title"
      class="svc-question-type-selector__button">
      <svg class="svc-question-type-selector__icon" [iconName]="questionTypeSelectorModel.iconName" [size]="'auto'"
        sv-ng-svg-icon></svg>
    </button>
    <sv-ng-popup *ngIf="renderPopup" [popupModel]="questionTypeSelectorModel.popupModel"></sv-ng-popup>
  </span>
</ng-template>

// packages/survey-creator-vue/src/tabs/designer/AddQuestionTypeSelector.vue
<template>
  <span class="svc-question-type-selector">
    <button
      class="svc-question-type-selector__button"
      v-on:click="
        (e) => {
          questionTypeSelectorModel.action();
          e.stopPropagation();
        }
      "
      :title="questionTypeSelectorModel.title"
      v-key2click
      :aria-label="questionTypeSelectorModel.title"
    >
      <SvComponent
        :is="'sv-svg-icon'"
        class="svc-question-type-selector__icon"
        v-bind="{
          iconName: questionTypeSelectorModel.iconName,
          size: 'auto',
          title: questionTypeSelectorModel.title,
        }"
      ></SvComponent>
    </button>
    <SvComponent
      v-if="renderPopup"
      :is="'sv-popup'"
      :model="questionTypeSelectorModel.popupModel"
    ></SvComponent>
  </span>
</template>
<script lang="ts" setup>
import { key2ClickDirective as vKey2click } from "survey-vue3-ui";
import { useBase } from "survey-vue3-ui";
import { SvComponent } from "survey-vue3-ui";
const props = defineProps<{
  questionTypeSelectorModel: any;
  renderPopup: any;
}>();
useBase(() => props.questionTypeSelectorModel);
</script>
