// packages/survey-creator-react/src/components/tabs/Designer.tsx
import React from "react";
import { Base, SurveyModel, PageModel } from "survey-core";
import {
  ReactElementFactory,
  SurveyElementBase,
  SurveyHeader
} from "survey-react-ui";
import { CreatorBase, TabDesignerViewModel } from "@survey/creator";
import { CreatorSurveyPageComponent } from "../Page";
import { SurveyPageNavigator } from "../page-navigator/PageNavigator";
import { SurveyNavigation } from "../Navigation";

interface ITabDesignerComponentProps {
  data: TabDesignerViewModel<SurveyModel>;
}

export class TabDesignerComponent extends SurveyElementBase<
  ITabDesignerComponentProps,
  any
> {
  private get model(): TabDesignerViewModel<SurveyModel> {
    return this.props.data;
  }
  protected get creator(): CreatorBase<SurveyModel> {
    return this.model.creator;
  }
  protected getStateElement(): Base {
    return this.model;
  }
  protected renderPages(): JSX.Element[] {
    const surveyPages: JSX.Element[] = this.creator.survey.pages.map((page: PageModel) => {
      return (
        <div
          className={"svc-page"}
          data-svc-drop-target-element-name={page.name}
          key={page.id}
        >
          <CreatorSurveyPageComponent
            survey={this.creator.survey}
            page={page}
            creator={this.creator}
          ></CreatorSurveyPageComponent>
        </div>
      );
    });

    if (this.model.showNewPage) {
      surveyPages.push(
        <div
          className={"svc-page"}
          data-svc-drop-target-element-name={"newGhostPage"}
          key={this.model.newPage.id}
        >
          <CreatorSurveyPageComponent
            survey={this.creator.survey}
            page={this.model.newPage}
            creator={this.creator}
          ></CreatorSurveyPageComponent>
        </div>
      );
    }
    return surveyPages;
  }
  renderElement(): JSX.Element {
    const survey: SurveyModel = this.creator.survey;
    const designerTabClassName = "svc-tab-designer " + survey.css.root;

    return (
      <React.Fragment>
        <div className="svc-flex-column">
          {ReactElementFactory.Instance.createElement('svc-toolbox', { creator: this.creator })}
        </div>
        <div className={"svc-tab-designer " + survey.css.root}>
          <div className={survey.css.container}>
            <div
              onClick={() => this.creator.selectElement(survey)}
            >
              <SurveyHeader survey={survey}></SurveyHeader>
            </div>
            <SurveyNavigation
              survey={survey}
              location="top"
            />
            {this.renderPages()}
            <SurveyNavigation
              survey={survey}
              location="bottom"
              css={survey.css}
            />
          </div>
        </div>
        <SurveyPageNavigator
          creator={this.creator}
          pages={this.creator.pagesController.pages}
        ></SurveyPageNavigator>
          {ReactElementFactory.Instance.createElement('svc-property-grid', { model: this.creator })}
      </React.Fragment>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-tab-designer", (props) => {
  return React.createElement(
    TabDesignerComponent,
    props as ITabDesignerComponentProps
  );
});

// packages/survey-creator-vue/src/tabs/designer/Designer.vue
<template>
  <div class="svc-flex-column">
    <svc-adaptive-toolbox
      v-if="model.isToolboxVisible"
      :creator="model.creator"
    ></svc-adaptive-toolbox>
  </div>
  <div
    class="svc-tab-designer"
    :class="model.getRootCss()"
    @click="model.clickDesigner"
  >
    <div class="svc-tab-designer_content">
      <template v-if="model.showPlaceholder">
        <div
          v-if="
            model.creator.showHeaderInEmptySurvey &&
            model.creator.allowEditSurveyTitle
          "
          class="svc-designer-header"
        >
          <survey-header :survey="model.creator.survey"></survey-header>
        </div>
        <div
          class="svc-designer__placeholder-container"
          :data-sv-drop-target-survey-element="'newGhostPage'"
        >
          <span class="svc-designer-placeholder-text svc-text svc-text--normal">
            {{ model.placeholderText }}
          </span>
          <svc-page
            class="svc-designer-placeholder-page"
            :survey="model.creator.survey"
            :creator="model.creator"
            :page="model.newPage"
          >
          </svc-page>
        </div>
      </template>

      <template v-if="!model.showPlaceholder">
        <div
          :class="model.designerCss"
          data-bind="css: designerCss, style:{maxWidth: survey.renderedWidth}"
        >
          <div
            v-if="model.creator.allowEditSurveyTitle"
            class="svc-designer-header"
          >
            <survey-header :survey="model.creator.survey"></survey-header>
          </div>

          <!-- ko if: survey.isShowProgressBarOnTop -->
          <!-- ko component: { name: survey.getProgressTypeComponent(), params: { model: survey } } -->
          <!-- /ko -->
          <!-- /ko -->

          <template v-if="model.creator.pageEditMode !== 'bypage'">
            <div
              v-for="page in pages"
              :key="page.id"
              class="svc-page"
              :data-sv-drop-target-survey-element="
                page != model.newPage ? page.name : 'newGhostPage'
              "
              :data-sv-drop-target-page="page.name"
            >
              <svc-page
                :survey="model.creator.survey"
                :creator="model.creator"
                :page="page"
              ></svc-page>
            </div>
          </template>
          <div
            v-if="
              model.pagesController.page2Display &&
              model.creator.pageEditMode === 'bypage'
            "
            class="svc-page"
            :data-sv-drop-target-survey-element="'newGhostPage'"
            :data-sv-drop-target-page="model.pagesController.page2Display.name"
          >
            <svc-page
              :page="model.pagesController.page2Display"
              :creator="model.creator"
            ></svc-page>
          </div>
          <!-- ko if: survey.isShowProgressBarOnBottom -->
          <!-- ko component: { name: survey.getProgressTypeComponent(), params: { model: survey } } -->
          <!-- /ko -->
          <!-- /ko -->
        </div>
        <div
          v-if="model.creator.showPageNavigator"
          class="svc-tab-designer__page-navigator"
        >
          <svc-page-navigator
            :pagesController="model.pagesController"
            :pageEditMode="model.creator.pageEditMode"
          >
          </svc-page-navigator>
        </div>
      </template>
    </div>
  </div>
</template>
<script lang="ts" setup>
import type { TabDesignerViewModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { computed } from "vue";
const props = defineProps<{ model: TabDesignerViewModel }>();
useBase(() => props.model);
const pages = computed(() => {
  const model = props.model;
  return model.creator.survey.pages.concat(
    model.showNewPage ? [model.newPage] : []
  );
});
</script>
