// packages/survey-creator-angular/src/adorners/image-item-drag-action.component.ts
import { AfterViewInit, Component, ElementRef, Input, ViewChild } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { Action } from "survey-core";

@Component({
  selector: "svc-image-item-drag-action",
  templateUrl: "./image-item-drag-action.component.html",
  styles: [":host { display: none; }"]
})
export class ImageItemDragActionComponent extends BaseAngular {
  @Input() model!: Action;
  getModel() {
    return this.model as Action;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-image-item-drag-action", ImageItemDragActionComponent);
<ng-template #template>
    <span [class]="model.getActionBarItemCss()"
        (pointerdown)="model.data.model.onPointerDown($event)">
        <svg [iconName]="model.iconName" [size]="'auto'" [class]="model.cssClasses.itemIcon" sv-ng-svg-icon></svg>
    </span>
</ng-template>

// packages/survey-creator-vue/src/adorners/ImageItemDragAction.vue
<template>
  <span :class="item.getActionBarItemCss()" @pointerdown="item.data.model.onPointerDown($event)">
    <SvComponent :is="'sv-svg-icon'" :iconName="item.iconName" :size="item.iconSize"  :class="item.cssClasses.itemIcon"></SvComponent>
  </span>
</template>
<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import type { Action } from "survey-core";
defineProps<{
  item: Action
}>();
</script>
