// packages/survey-creator-angular/src/adorners/item-value.component.ts

import { ChangeDetectorRef, Component, Input, ViewContainerRef } from "@angular/core";
import { AngularComponentFactory, BaseAngular, EmbeddedViewContentComponent } from "survey-angular-ui";
import { ItemValue, PageModel, PanelModel, Question, QuestionSelectBase, SurveyModel } from "survey-core";
import { CreatorBase, ItemValueWrapperViewModel, QuestionAdornerViewModel } from "survey-creator-core";
import { CreatorModelComponent } from "../creator-model.component";

@Component({
  selector: "svc-item-value",
  templateUrl: "./item-value.component.html",
  styles: [":host { display: none; }"]
})
export class ItemValueDesignerComponent extends CreatorModelComponent<ItemValueWrapperViewModel> {
  @Input() componentName!: string;
  @Input() componentData!: any;
  public adorner!: ItemValueWrapperViewModel;
  private get creator(): CreatorBase {
    return this.componentData.data.creator;
  }
  public get question(): QuestionSelectBase {
    return this.componentData.question;
  }
  public get item(): ItemValue {
    return this.componentData.model;
  }
  protected createModel(): void {
    if (this.componentData) {
      this.adorner = new ItemValueWrapperViewModel(this.creator, this.question, this.item);
    }
  }
  protected getPropertiesToTrack(): string[] {
    return ["componentName", "componentData"];
  }
  protected getModel(): ItemValueWrapperViewModel {
    return this.adorner;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-item-value", ItemValueDesignerComponent);

<ng-template #template>
  <div class="svc-item-value-wrapper" (pointerdown)="adorner.onPointerDown($event)"
    [attr.data-sv-drop-target-item-value]="adorner.isDraggable ? item.value : null"
    [ngClass]="{'svc-item-value--new': adorner.isNew, 'svc-item-value--dragging': adorner.isDragging, 'vc-item-value--ghost': adorner.isDragDropGhost, 'svc-item-value--movedown': adorner.isDragDropMoveDown, 'svc-item-value--moveup': adorner.isDragDropMoveUp}">
    <div class="svc-item-value__ghost"></div>
    <div class="svc-item-value-controls">
      <span *ngIf="adorner.isDraggable" class="svc-item-value-controls__button svc-item-value-controls__drag">
        <svg class="svc-item-value-controls__drag-icon" [iconName]="'icon-drag-area-indicator'" [size]="24"
          [attr.title]="adorner.dragTooltip" [attr.aria-label]="adorner.dragTooltip" sv-ng-svg-icon></svg>
      </span>
      <svg *ngIf="adorner.allowAdd" class="svc-item-value-controls__button svc-item-value-controls__add" [key2click]
        (click)="adorner.add(adorner)" [iconName]="'icon-add_16x16'" [size]="16" [attr.title]="undefined"
        [attr.aria-label]="undefined" sv-ng-svg-icon></svg>
      <svg *ngIf="adorner.allowRemove" class="svc-item-value-controls__button svc-item-value-controls__remove"
        [key2click] (click)="adorner.remove(adorner)" [iconName]="'icon-remove_16x16'" [size]="16"
        [attr.title]="undefined" [attr.aria-label]="undefined" sv-ng-svg-icon></svg>
    </div>

    <div class="svc-item-value__item" (click)="adorner.select(adorner, $event)">
      <ng-template [component]="{ name: componentName, data: componentData }"></ng-template>
    </div>
  </div>
</ng-template>

// packages/survey-creator-vue/src/adorners/ItemValue.vue
<template>
  <div
    class="svc-item-value-wrapper"
    @pointerdown="adorner.onPointerDown($event)"
    :data-sv-drop-target-item-value="adorner.isDraggable ? item.value : null"
    :class="{
      'svc-item-value--new': adorner.isNew,
      'svc-item-value--dragging': adorner.isDragging,
      'svc-item-value--ghost': adorner.isDragDropGhost,
      'svc-item-value--movedown': adorner.isDragDropMoveDown,
      'svc-item-value--moveup': adorner.isDragDropMoveUp,
    }"
  >
    <div class="svc-item-value__ghost"></div>
    <div class="svc-item-value-controls">
      <span
        v-if="adorner.isDraggable"
        class="svc-item-value-controls__button svc-item-value-controls__drag"
      >
        <sv-svg-icon
          class="svc-item-value-controls__drag-icon"
          :iconName="'icon-drag-area-indicator'"
          :size="24"
          :title="adorner.dragTooltip"
        ></sv-svg-icon>
      </span>
      <span
        v-if="adorner.allowAdd"
        class="svc-item-value-controls__button svc-item-value-controls__add"
        v-key2click
        @click="adorner.add(adorner)"
        :aria-label="undefined"
        ><sv-svg-icon
          :iconName="'icon-add_16x16'"
          :size="16"
          :title="undefined"
        ></sv-svg-icon
      ></span>
      <span
        v-if="adorner.allowRemove"
        class="svc-item-value-controls__button svc-item-value-controls__remove"
        v-key2click
        @click="adorner.remove(adorner)"
        @blur="adorner.onFocusOut($event)"
        :aria-label="undefined"
        ><sv-svg-icon
          :iconName="'icon-remove_16x16'"
          :size="16"
          :title="undefined"
        ></sv-svg-icon
      ></span>
    </div>
    <div class="svc-item-value__item" @click="adorner.select(adorner, $event)">
      <component :is="componentName" v-bind="componentData"></component>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { useCreatorModel } from "@/creator-model";
import type { ItemValue, QuestionSelectBase } from "survey-core";
import {
  ItemValueWrapperViewModel,
  type CreatorBase,
} from "survey-creator-core";
import { computed } from "vue";

const props = defineProps<{
  componentName: string;
  componentData: {
    data: {
      creator: CreatorBase;
    };
    question: QuestionSelectBase;
    item: ItemValue;
  };
}>();
const creator = computed(() => props.componentData.data.creator);
const question = computed(() => props.componentData.question);
const item = computed(() => props.componentData.item);
const adorner = useCreatorModel(
  () =>
    new ItemValueWrapperViewModel(creator.value, question.value, item.value),
  [() => creator.value, () => question.value, () => item.value],
  (value) => {
    value.dispose();
  }
);
</script>
