// packages/survey-creator-angular/src/panel.component.ts
import { Component } from "@angular/core";
import { AngularComponentFactory } from "survey-angular-ui";
import { PanelAdornerViewModel } from "survey-creator-core";
import { QuestionDesignerComponent } from "./question.component";

@Component({
  selector: "svc-panel",
  templateUrl: "./panel.component.html",
  styles: [":host { display: none; }"]
})
export class PanelDesignerComponent extends QuestionDesignerComponent<PanelAdornerViewModel> {
  protected override createModel(): void {
    if (this.componentData) {
      this.adorner = new PanelAdornerViewModel(this.creator, this.model, <any>null);
    }
  }
}

AngularComponentFactory.Instance.registerComponent("svc-panel", PanelDesignerComponent);

<ng-template #template>
  <div *ngIf="adorner" class="svc-question__adorner" [class]="adorner.rootCss()" (dblclick)="adorner.dblclick($event)"
    (mouseover)="adorner.hover($event, $event.currentTarget)" (mouseleave)="adorner.hover($event, $event.currentTarget)"
    [attr.data-sv-drop-target-survey-element]="adorner.element.name || null" #container>

    <div [class]="adorner.css()" [key2click]="{ disableTabStop: true }"
      (click)="adorner.element.isInteractiveDesignElement ? adorner.select(adorner, $event) : null">
      <div class="svc-question__drop-indicator svc-question__drop-indicator--left"></div>
      <div class="svc-question__drop-indicator svc-question__drop-indicator--right"></div>
      <div class="svc-question__drop-indicator svc-question__drop-indicator--top"></div>
      <div class="svc-question__drop-indicator svc-question__drop-indicator--bottom"></div>
      <div *ngIf="adorner.allowDragging && adorner.element.isInteractiveDesignElement" class="svc-question__drag-area"
        (pointerdown)="adorner.onPointerDown($event)">
        <svg class="svc-question__drag-element" [iconName]="'icon-drag-area-indicator_24x16'" [size]="24"
          sv-ng-svg-icon></svg>
        <div class="svc-question__top-actions">
          <sv-action-bar [model]="adorner.topActionContainer" [handleClick]="false"></sv-action-bar>
        </div>
      </div>
      <div *ngIf="!model.hasTitle" [class]="adorner.cssCollapsedHiddenHeader"></div>
      <div [class]="adorner.cssCollapsedHiddenTitle">
        <sv-ng-string *ngIf="!!model.title" [model]="model.locTitle"></sv-ng-string>
        <span *ngIf="!model.title" class="svc-fake-title">{{model.name}}</span>
      </div>
      </div>
      <ng-template [component]="{ name: componentName, data: componentData }"></ng-template>

      <div *ngIf="adorner.isEmptyElement" class="svc-panel__placeholder_frame-wrapper">
        <div class="svc-panel__placeholder_frame">
          <div class="svc-panel__placeholder">{{ adorner.placeholderText }}</div>
          <div *ngIf="adorner.showAddQuestionButton" class="svc-panel__add-new-question svc-action-button" [key2click]
            (click)="addNewQuestion($event)">
            <svg class="svc-panel__add-new-question-icon" [iconName]="('icon-add_24x24')" [size]="24"
              sv-ng-svg-icon></svg>
            <span class="svc-text svc-text--normal svc-text--bold">
              {{ adorner.addNewQuestionText }}
            </span>
          </div>
        </div>
      </div>

      <ng-template *ngIf="adornerComponent && adorner.element.isInteractiveDesignElement"
        [component]="{ name: adornerComponent, data: { adorner: adorner, question: model } }">
      </ng-template>

      <div *ngIf="!adorner.isEmptyElement && adorner.showAddQuestionButton"
        class="svc-panel__add-new-question-container">
        <div class="svc-panel__question-type-selector-popup"> <sv-ng-popup
            [popupModel]="adorner.questionTypeSelectorModel.popupModel"></sv-ng-popup>
        </div>

        <div class="svc-panel__add-new-question-wrapper">
          <ng-template
            [component]="{ name: 'svc-add-new-question-btn', data: { model: { data: adorner }, buttonClass: 'svc-action-button', renderPopup: false } }">
          </ng-template>
        </div>
      </div>

      <div *ngIf="adorner.element.isInteractiveDesignElement" class="svc-question__content-actions"
        (focusin)="adorner.select(adorner, $event)">
        <sv-action-bar [model]="adorner.actionContainer" [handleClick]="false"></sv-action-bar>
      </div>
    </div>
  </div>
</ng-template>

// packages/survey-creator-vue/src/adorners/Panel.vue
<template>
  <div
    v-if="adorner"
    class="svc-question__adorner"
    :class="adorner.rootCss()"
    @dblclick="(e) => adorner.dblclick(e)"
    @mouseover="adorner.hover($event, $event.currentTarget)"
    @mouseleave="adorner.hover($event, $event.currentTarget)"
    :data-sv-drop-target-survey-element="adorner.element.name || null"
    ref="root"
  >
    <div
      v-if="adorner.showHiddenTitle"
      :class="adorner.cssCollapsedHiddenHeader"
    >
      <div :class="adorner.cssCollapsedHiddenTitle">
        <SvComponent
          v-if="!!adorner.element.hasTitle"
          :is="'survey-string'"
          :locString="adorner.element.locTitle"
        />
        <span v-else class="svc-fake-title">{{ adorner.element.name }}</span>
      </div>
    </div>
    <div
      :class="adorner.css()"
      v-key2click="{ disableTabStop: true }"
      @click="
        adorner.element.isInteractiveDesignElement
          ? adorner.select(adorner, $event)
          : null
      "
    >
      <div
        class="svc-question__drop-indicator svc-question__drop-indicator--left"
      ></div>
      <div
        class="svc-question__drop-indicator svc-question__drop-indicator--right"
      ></div>
      <div
        class="svc-question__drop-indicator svc-question__drop-indicator--top"
      ></div>
      <div
        class="svc-question__drop-indicator svc-question__drop-indicator--bottom"
      ></div>
      <div
        v-if="
          adorner.allowDragging && adorner.element.isInteractiveDesignElement
        "
        class="svc-question__drag-area"
        @pointerdown="adorner.onPointerDown($event)"
      >
        <SvComponent
          :is="'sv-svg-icon'"
          class="svc-question__drag-element"
          :iconName="'icon-drag-area-indicator_24x16'"
          :size="24"
        ></SvComponent>
        <div class="svc-question__top-actions">
          <SvComponent
            :is="'sv-action-bar'"
            :model="adorner.topActionContainer"
            :handleClick="false"
          ></SvComponent>
        </div>
      </div>
      <SvComponent :is="componentName" v-bind="componentData"></SvComponent>
      <div
        v-if="adorner.isEmptyElement"
        class="svc-panel__placeholder_frame-wrapper"
      >
        <div class="svc-panel__placeholder_frame">
          <div class="svc-panel__placeholder">
            {{ adorner.placeholderText }}
          </div>
          <div
            v-if="adorner.showAddQuestionButton"
            class="svc-panel__add-new-question svc-action-button"
            v-key2click
            @click="addNewQuestion"
          >
            <SvComponent
              :is="'sv-svg-icon'"
              class="svc-panel__add-new-question-icon"
              :iconName="'icon-add_24x24'"
              :size="24"
            ></SvComponent>
            <span class="svc-add-new-item__text">
              {{ adorner.addNewQuestionText }}
            </span>
          </div>
        </div>
      </div>
      <div
        v-if="!adorner.isEmptyElement && adorner.showAddQuestionButton"
        class="svc-panel__add-new-question-container"
      >
        <div class="svc-panel__question-type-selector-popup">
          <SvComponent
            :is="'sv-popup'"
            :model="adorner.questionTypeSelectorModel.popupModel"
          ></SvComponent>
        </div>
        <div class="svc-panel__add-new-question-wrapper">
          <SvComponent
            :is="'svc-add-new-question-btn'"
            :item="{ data: adorner }"
            :buttonClass="'svc-action-button'"
            :renderPopup="false"
          ></SvComponent>
        </div>
      </div>

      <div
        v-if="adorner.element.isInteractiveDesignElement"
        class="svc-question__content-actions"
        @focusin="adorner.select(adorner, $event)"
      >
        <SvComponent
          :is="'sv-action-bar'"
          :model="adorner.actionContainer"
          :handleClick="false"
        ></SvComponent>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { key2ClickDirective as vKey2click } from "survey-vue3-ui";
import { SvComponent } from "survey-vue3-ui";
import { useCreatorModel } from "@/creator-model";
import type { Question } from "survey-core";
import {
  QuestionAdornerViewModel,
  type SurveyCreatorModel,
} from "survey-creator-core";
const props = defineProps<{
  componentName: string;
  componentData: any;
}>();
const adorner = useCreatorModel(
  () =>
    new QuestionAdornerViewModel(
      props.componentData.data as SurveyCreatorModel,
      props.componentData.element as Question,
      null as any
    ),
  [() => props.componentData.data, () => props.componentData.element],
  (value) => {
    value.dispose();
  }
);
const addNewQuestion = (event: Event) => {
  event.stopPropagation();
  adorner.value.addNewQuestion();
};
const selectQuestionType = (event: any) => {
  event.stopPropagation();
  adorner.value.questionTypeSelectorModel?.action(
    adorner.value.questionTypeSelectorModel,
    event
  );
};
// svc-panel
</script>
