// packages/survey-creator-react/src/adorners/QuestionBanner.tsx
import { QuestionBannerParams } from "survey-creator-core";
import * as React from "react";
import { ReactElementFactory } from "survey-react-ui";
import { ActionButton } from "../ActionButton";

export class QuestionBanner extends React.Component<QuestionBannerParams, any> {
  render(): React.JSX.Element {
    return (
      <div className="svc-carry-forward-panel-wrapper"><div className="svc-carry-forward-panel">
        <span>{this.props.text}{" "}</span>
        <span className="svc-carry-forward-panel__link">
          <ActionButton click={() => this.props.onClick()} text={this.props.actionText}></ActionButton>
        </span>
      </div></div>);
  }
}

ReactElementFactory.Instance.registerElement(
  "svc-question-banner",
  (props: QuestionBannerParams) => {
    return React.createElement(QuestionBanner, props);
  }
);

// packages/survey-creator-vue/src/adorners/QuestionBanner.vue
<template>
  <div class="svc-carry-forward-panel-wrapper">
    <div class="svc-carry-forward-panel">
      <span>{{ model.text }}{{ " " }}</span>
      <span class="svc-carry-forward-panel__link">
        <svc-action-button
          :text="model.actionText"
          :click="model.onClick.bind(model)"
        >
        </svc-action-button>
      </span>
    </div>
  </div>
</template>
<script lang="ts" setup>
import type { QuestionBannerParams } from "survey-creator-core";
defineProps<{ model: QuestionBannerParams }>();
</script>
