// packages/survey-creator-react/src/adorners/TranslationDropdownQuestion.tsx
import * as React from "react";
import { Base, ItemValue, QuestionSelectBase } from "survey-core";
import { TranslationDropdownViewModel, translationDropdownComponentName } from "survey-creator-core";
import { ReactElementFactory } from "survey-react-ui";
import { QuestionAdornerComponentProps } from "./Question";
import { CreatorModelElement } from "../ModelElement";

// The flattened choice list of a dropdown/tagbox question in the translation side-by-side
// panes. Chrome-free: no designer adorner, no itemvalue wrappers - the choice texts render
// through the survey's string renderer (editable in the target pane, plain in the source one).
export class TranslationDropdownQuestionComponent extends CreatorModelElement<
  QuestionAdornerComponentProps,
  any
> {
  model: TranslationDropdownViewModel;
  protected createModel(props: any): void {
    if (!!this.model) {
      this.model.dispose();
    }
    this.model = new TranslationDropdownViewModel(
      props.question as QuestionSelectBase,
      props.componentData ? props.componentData.translation : undefined
    );
  }
  protected getUpdatedModelProps(): string[] {
    return ["question", "componentData"];
  }
  protected getStateElement(): Base {
    return this.model;
  }
  componentWillUnmount(): void {
    super.componentWillUnmount();
    this.model.dispose();
  }
  renderElement(): React.JSX.Element {
    const question = this.props.question as QuestionSelectBase;
    const textStyle = (this.props.question as any).textStyle;
    return (
      <React.Fragment>
        {this.props.element}
        <div className="st-dropdown-choices--wrapper">
          <div className="svc-question__dropdown-choices">
            {this.model.getRenderedItems().map(
              (item: ItemValue, index: number) => (
                <div className={this.model.getChoiceCss()} key={`translation_choice_${index}`}>
                  {ReactElementFactory.Instance.createElement(this.model.itemComponent, {
                    question: question,
                    cssClasses: question.cssClasses,
                    isDisplayMode: true,
                    item: item,
                    textStyle: textStyle,
                    index: index,
                    isChecked: false
                  })}
                </div>
              )
            )}
          </div>
          {this.model.needToCollapse ?
            ReactElementFactory.Instance.createElement("sv-action-bar-item", { item: this.model.collapseAction }) : null}
        </div>
      </React.Fragment>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  translationDropdownComponentName,
  (props: QuestionAdornerComponentProps) => {
    return React.createElement(TranslationDropdownQuestionComponent, props);
  }
);

// packages/survey-creator-vue/src/adorners/TranslationDropdownQuestion.vue
<template>
  <slot></slot>
  <div class="st-dropdown-choices--wrapper" v-if="model">
    <div class="svc-question__dropdown-choices">
      <div
        v-for="(item, index) in model.getRenderedItems()"
        :key="'translation_choice_' + index"
        :class="model.getChoiceCss()"
      >
        <SvComponent :is="model.itemComponent" :question="question" :item="item"></SvComponent>
      </div>
    </div>
    <SvComponent
      :is="'sv-action-bar-item'"
      v-if="model.needToCollapse"
      :item="model.collapseAction">
    </SvComponent>
  </div>
</template>
<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import { useCreatorModel } from "@/creator-model";
import type { QuestionSelectBase } from "survey-core";
import { TranslationDropdownViewModel } from "survey-creator-core";
import { computed } from "vue";

const props = defineProps<{
  componentData: { question: QuestionSelectBase; data: any };
  componentName: string;
}>();
const question = computed(() => props.componentData.question);
const model = useCreatorModel(
  () =>
    new TranslationDropdownViewModel(
      props.componentData.question,
      props.componentData.data ? props.componentData.data.translation : undefined
    ),
  [() => props.componentData.question, () => props.componentData.data],
  (value) => value?.dispose()
);
</script>
