// packages/survey-creator-angular/src/questions/question-embedded-survey.component.ts
import { Component, ElementRef, ViewChild } from "@angular/core";
import { AngularComponentFactory, QuestionAngular } from "survey-angular-ui";
import { QuestionEmbeddedSurveyModel } from "survey-creator-core";

@Component({
  selector: "svc-embeddedsurvey-question",
  templateUrl: "./question-embedded-survey.component.html",
  styles: [":host { display: none; }"]
})
export class EmbeddedSurveyQuestionComponent extends QuestionAngular<QuestionEmbeddedSurveyModel> {
  @ViewChild("container") container!: ElementRef<HTMLDivElement>;
  public get survey() {
    return this.model.embeddedSurvey;
  }
  public override ngAfterViewInit(): void {
    super.ngAfterViewInit();
    this.survey.rootElement = this.container.nativeElement;
  }
  protected override onModelChanged(): void {
    super.onModelChanged();
    if (!!this.model) {
      this.model.onEmbeddedSurveyValueChanged = () => {
        this.detectChanges();
      };
    }
  }
}

AngularComponentFactory.Instance.registerComponent("embeddedsurvey-question", EmbeddedSurveyQuestionComponent);
<ng-template #template>
  <div #container style="display: contents">
    <ng-container *ngIf="!!model && !!survey && survey.currentPage">
      <page [model]="survey.currentPage" [survey]="survey"></page>
    </ng-container>
  </div>
</ng-template>

// packages/survey-creator-react/src/QuestionEmbeddedSurvey.tsx
import * as React from "react";
import { ReactQuestionFactory, SurveyPage, ISurveyCreator, SurveyQuestionElementBase, SurveyModel } from "survey-react-ui";
import { QuestionEmbeddedSurveyModel, SurveyCreatorModel } from "survey-creator-core";

export class SurveyElementEmbeddedSurvey extends SurveyQuestionElementBase {
  private rootRef: React.RefObject<HTMLDivElement> = React.createRef();
  protected get embeddedSurvey(): SurveyModel {
    const element = (this.props.element || this.props.question) as QuestionEmbeddedSurveyModel;
    if (!element) return null;
    const survey = element.embeddedSurvey;
    if (!survey || !survey.currentPage) return null;
    return survey;
  }
  protected get creator(): ISurveyCreator {
    return this.props.creator;
  }
  componentDidMount() {
    super.componentDidMount();
    if (this.embeddedSurvey) {
      this.embeddedSurvey.rootElement = this.rootRef.current;
    }
  }
  public render(): React.JSX.Element {
    const survey = this.embeddedSurvey;
    if (!survey) return null;
    return <div style={{ display: "contents" }} ref={this.rootRef}>
      <SurveyPage
        survey={survey}
        page={survey.currentPage}
        css={survey.css}
        creator={this.creator}
      />
    </div>;

  }
}

ReactQuestionFactory.Instance.registerQuestion("embeddedsurvey", (props) => {
  return React.createElement(SurveyElementEmbeddedSurvey, props);
});
