// packages/survey-creator-angular/src/components/switcher.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-switcher",
  templateUrl: "./switcher.component.html",
  styles: [":host { display: none; }"]
})
export class SwitcherComponent extends BaseAngular {
  @Input() model: any;

  getModel() {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-switcher", SwitcherComponent);


<ng-template #template>
  <button class="svc-switcher" type="button" (click)="model.action(model, model.getIsTrusted($event))"
    [key2click]="{ processEsc: false, disableTabStop: model.disableTabStop }" [class]="model.getActionBarItemCss()"
    [disabled]="model.disabled" [attr.title]="model.tooltip || model.title" [attr.aria-checked]="model.ariaChecked"
    [attr.aria-expanded]="model.ariaExpanded" [attr.role]="model.ariaRole">
    <div [class]="model.getSwitcherIconCss()">
      <div class="svc-switcher__icon-thumb"></div>
    </div>
    <span *ngIf="model.hasTitle" class="svc-switcher__title">{{ model.title }}</span>
  </button>
  <ng-template>

// packages/survey-creator-react/src/Switcher.tsx
import * as React from "react";
import { Switcher } from "survey-creator-core";
import { Base } from "survey-core";
import { ReactElementFactory, attachKey2click, SurveyElementBase } from "survey-react-ui";

interface ISwitcherComponentProps {
  item: Switcher;
}

export class SwitcherComponent extends SurveyElementBase<ISwitcherComponentProps, any> {
  get item(): Switcher {
    return this.props.item;
  }

  protected getStateElement(): Base {
    return this.item;
  }

  renderElement() {
    const tooltip = this.item.tooltip || this.item.title;
    const title = this.item.hasTitle ? <span className="svc-switcher__title">{this.item.title}</span> : null;
    const button = attachKey2click(
      <button
        className={this.item.getActionBarItemCss()}
        type="button"
        disabled={this.item.disabled}
        onClick={(args) => this.item.action(this.item, this.item.getIsTrusted(args))}
        title={tooltip}
        aria-checked={this.item.ariaChecked}
        aria-expanded={this.item.ariaExpanded}
        role={this.item.ariaRole}
      >
        <div className={this.item.getSwitcherIconCss()}>
          <div className="svc-switcher__icon-thumb"></div>
        </div>
        {title}
      </button>, this.item, { processEsc: false });

    return button;
  }
}

export default SwitcherComponent;

ReactElementFactory.Instance.registerElement("svc-switcher", (props) => {
  return React.createElement(SwitcherComponent, props);
});
