// packages/survey-creator-vue/src/custom-questions/ColorItem.vue
<template>
  <span class="spg-color-editor__color-swatch" :style="getStyle()"></span>
  <SvComponent :is="'survey-string'" :locString="item.locTitle"></SvComponent>
</template>
<script setup lang="ts">
import { SvComponent } from "survey-vue3-ui";
import type { ItemValue, ListModel } from "survey-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ model: ListModel; item: ItemValue }>();
useBase(() => props.item);
const getStyle = () => {
  return { backgroundColor: props.item.value };
};
</script>

// packages/survey-creator-angular/src/custom-questions/color-item.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { ItemValue } from "survey-core";

@Component({
  selector: "svc-color-item",
  templateUrl: "./color-item.component.html",
  styles: [":host { display: none }"]
})
export class ColorItemComponent extends BaseAngular<ItemValue> {
  @Input() model!: ItemValue
  protected override getModel(): ItemValue {
    return this.model;
  }

  getStyle() {
    return { backgroundColor: this.model.value };
  }
}

AngularComponentFactory.Instance.registerComponent("color-item", ColorItemComponent);
<ng-template #template>
  <span class="spg-color-editor__color-swatch" [style]="getStyle()"></span>
  <sv-ng-string [model]="model.locTitle"></sv-ng-string>
</ng-template>
