// packages/survey-creator-vue/src/custom-questions/FileEditorButton.vue
<template>
    <div>
        <label
            :class="item.getActionBarItemCss()"
            :for="question.inputId"
            :aria-label="question.chooseButtonCaption"
            @click="question.chooseFiles"
            v-key2click
        >
        <SvComponent
            :is="'sv-svg-icon'"
            :class="item.cssClasses.itemIcon"
            :iconName="item.iconName"
            :size="'auto'"
            :title="item.title"
        ></SvComponent>
        <span class="sv-visuallyhidden">{{ question.chooseButtonCaption }}</span>
        </label>
        <input
          type="file"
          :disabled="item.disabled"
          :class="question.cssClasses.fileInput"
          :id="question.inputId"
          :aria-required="question.ariaRequired"
          :aria-label="question.ariaLabel"
          :aria-invalid="question.ariaInvalid"
          :aria-describedby="question.ariaDescribedBy"
          :multiple="false"
          :title="question.inputTitle"
          :tabindex="-1"
          :accept="question.acceptedTypes"
          @change="question.onFileInputChange"
        />
    </div>
</template>
<script lang="ts" setup>
import { key2ClickDirective as vKey2click } from "survey-vue3-ui";
import { SvComponent } from "survey-vue3-ui";
import type { QuestionFileEditorModel } from "survey-creator-core";
import type { Action } from "survey-core";
import { computed } from "vue";
const props = defineProps<{ item: Action }>();
const question = computed<QuestionFileEditorModel>(() => {
  return props.item.data.question as QuestionFileEditorModel;
});
</script>

// packages/survey-creator-angular/src/custom-questions/file-editor-button.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { Action } from "survey-core";
import { QuestionFileEditorModel } from "survey-creator-core";

@Component({
  selector: "sv-ng-file-editor-button",
  templateUrl: "./file-editor-button.component.html",
  styles: ["{ :host { display: none; } }"]
})
export class FileEditorButtonComponent extends BaseAngular {
  @Input() model!: Action;
  get question() {
    return this.model.data.question as QuestionFileEditorModel;
  }
  getModel() {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-fileedit-button", FileEditorButtonComponent);
<ng-template #template>
  <div>
    <label [class]="model.getActionBarItemCss()" [attr.for]="question.inputId" [attr.aria-label]="question.chooseButtonCaption"
      (click)="question.chooseFiles($event)" [key2click]>
      <svg [iconName]="model.iconName" size="'auto'" [title]="model.title" [class]="model.cssClasses.itemIcon" sv-ng-svg-icon></svg>
      <span class="sv-visuallyhidden">{{ question.chooseButtonCaption }}</span>
    </label>
    <input type="file" [disabled]="model.disabled" [class]="question.cssClasses.fileInput" [attr.id]="question.inputId"
        [attr.aria-required]="question.ariaRequired" [attr.aria-label]="question.ariaLabel"
        [attr.aria-invalid]="question.ariaInvalid" [attr.aria-describedby]="question.ariaDescribedBy" [attr.multiple]="false"
        [title]="question.inputTitle" [accept]="question.acceptedTypes" (change)="question.onFileInputChange($event)" tabindex="-1">
  </div>
</ng-template>
