// packages/survey-creator-vue/src/custom-questions/SpinEditor.vue
<template>
  <div :class="question.cssClasses.root" @keydown="question.onKeyDown">
    <input
      role="spinbutton"
      autocomplete="off"
      :disabled="question.isInputReadOnly"
      :id="question.inputId"
      :placeholder="question.renderedPlaceholder"
      :aria-required="question.a11y_input_ariaRequired"
      :aria-label="question.a11y_input_ariaLabel"
      :aria-labelledby="question.a11y_input_ariaLabelledBy"
      :aria-describedby="question.a11y_input_ariaDescribedBy"
      :aria-invalid="question.a11y_input_ariaInvalid"
      :aria-errormessage="question.a11y_input_ariaErrormessage"
      @change="question.onChange"
      @keydown="question.onInputKeyDown"
      @keyup="question.onKeyUp"
      @blur="question.onBlur"
      @focus="question.onFocus"
      @beforeinput="question.onBeforeInput"
      :value="question.renderedValue"
      :class="question.cssClasses.control"
    />
    <span :class="question.cssClasses.buttonsContainer">
      <button
        :aria-hidden="'true'"
        :disabled="question.isInputReadOnly"
        :class="question.cssClasses.arrowButton"
        @click="question.onDownButtonClick"
        @mousedown="question.onDownButtonMouseDown"
        @mouseup="question.onButtonMouseUp"
        @mouseleave="question.onButtonMouseLeave"
        @blur="question.onBlur"
        @focus="question.onFocus"
        tabindex="-1"
      >
        <SvComponent
          :is="'sv-svg-icon'"
          :iconName="question.cssClasses.decreaseButtonIcon"
          :size="'auto'"
        ></SvComponent>
      </button>
      <button
        :aria-hidden="'true'"
        :disabled="question.isInputReadOnly"
        :class="question.cssClasses.arrowButton"
        @click="question.onUpButtonClick"
        @mousedown="question.onUpButtonMouseDown"
        @mouseup="question.onButtonMouseUp"
        @mouseleave="question.onButtonMouseLeave"
        @blur="question.onBlur"
        @focus="question.onFocus"
        tabindex="-1"
      >
        <SvComponent
          :is="'sv-svg-icon'"
          :iconName="question.cssClasses.increaseButtonIcon"
          :size="'auto'"
        ></SvComponent>
      </button>
    </span>
  </div>
</template>
<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import type { QuestionSpinEditorModel } from "survey-creator-core";
import { useQuestion } from "survey-vue3-ui";
import { ref } from "vue";
const props = defineProps<{ question: QuestionSpinEditorModel }>();
useQuestion(props, ref<HTMLElement>());
</script>

// packages/survey-creator-angular/src/custom-questions/spin-editor.component.ts
import { Component } from "@angular/core";
import { AngularComponentFactory, QuestionAngular } from "survey-angular-ui";
import { QuestionSpinEditorModel } from "survey-creator-core";

@Component({
  templateUrl: "./spin-editor.component.html"
})
export class QuestionSpinEditorComponent extends QuestionAngular<QuestionSpinEditorModel> {
}
AngularComponentFactory.Instance.registerComponent("spinedit-question", QuestionSpinEditorComponent);
<div [class]="model.cssClasses.root" (keydown)="model.onKeyDown($event)">
  <input autocomplete="off" role="spinbutton" [disabled]="model.isInputReadOnly" [attr.id]="model.inputId"
    [attr.aria-required]="model.a11y_input_ariaRequired" [attr.aria-label]="model.a11y_input_ariaLabel"
    [attr.aria-labelledby]="model.a11y_input_ariaLabelledBy" [attr.aria-describedby]="model.a11y_input_ariaDescribedBy"
    [attr.aria-invalid]="model.a11y_input_ariaInvalid" [attr.aria-errormessage]="model.a11y_input_ariaErrormessage"
    (change)="model.onChange($event)" (keydown)="model.onInputKeyDown($event)" (keyup)="model.onKeyUp($event)"
    (blur)="model.onBlur($event)" (focus)="model.onFocus($event)" (beforeinput)="model.onBeforeInput($event)"
    [value]="model.renderedValue" [class]="model.cssClasses.control" />
  <span [class]="model.cssClasses.buttonsContainer">
    <button [disabled]="model.isInputReadOnly" [attr.aria-hidden]="'true'" [class]="model.cssClasses.arrowButton"
      (click)="model.onDownButtonClick()" (mousedown)="model.onDownButtonMouseDown()"
      (mouseup)="model.onButtonMouseUp()" (mouseleave)="model.onButtonMouseLeave()" (blur)="model.onBlur($event)"
      (focus)="model.onFocus($event)" tabindex="-1">
      <svg [iconName]="model.cssClasses.decreaseButtonIcon" [size]="'auto'" sv-ng-svg-icon></svg>
    </button>
    <button [disabled]="model.isInputReadOnly" [attr.aria-hidden]="'true'" [class]="model.cssClasses.arrowButton"
      (click)="model.onUpButtonClick()" (mousedown)="model.onUpButtonMouseDown()" (mouseup)="model.onButtonMouseUp()"
      (mouseleave)="model.onButtonMouseLeave()" (blur)="model.onBlur($event)" (focus)="model.onFocus($event)"
      tabindex="-1">
      <svg [iconName]="model.cssClasses.increaseButtonIcon" [size]="'auto'" sv-ng-svg-icon></svg>
    </button>
  </span>
</div>
