// packages/survey-creator-vue/src/custom-questions/SpinEditorButton.vue
<template>
    <button
    :class="itemAction.getActionBarItemCss()"
    :aria-hidden="'true'"
    :disabled="itemAction.disabled"
    @click="item.action"
    @mousedown="item.data.onMouseDown"
    @mouseup="question.onButtonMouseUp"
    @mouseleave="question.onButtonMouseLeave"
    @blur="question.onBlur"
    @focus="question.onFocus"
    tabindex="-1"
    >
    <SvComponent
        :is="'sv-svg-icon'"
        :class="itemAction.cssClasses.itemIcon"
        :iconName="item.iconName"
        :size="'auto'"
    ></SvComponent>
    </button>
</template>
<script lang="ts" setup>
import type { Action } from 'survey-core';
import type { ISpinEditorButton } from 'survey-creator-core';
import { useBase, SvComponent } from 'survey-vue3-ui';
import { computed } from 'vue';

const props = defineProps<{ item: ISpinEditorButton }>()
const itemAction = computed(() => props.item as Action)
useBase(() => itemAction.value);
const question = computed(() => props.item.data.question)
</script>

// packages/survey-creator-angular/src/custom-questions/spin-editor-button.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { Action } from "survey-core";
import { ISpinEditorButton } from "survey-creator-core";

@Component({
  selector: "sv-ng-spin-edit-button",
  templateUrl: "./spin-editor-button.component.html",
  styles: ["{ :host { display: none; } }"]
})
export class SpinEditorButtonComponent extends BaseAngular {
  @Input() model!: ISpinEditorButton;
  get modelAction(): Action {
    return this.model as Action;
  }
  get question() {
    return this.model.data.question;
  }
  getModel() {
    return this.modelAction;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-spinedit-button", SpinEditorButtonComponent);
<ng-template #template>
    <button [disabled]="modelAction.disabled" [attr.aria-hidden]="'true'" [class]="modelAction.getActionBarItemCss()"
        (click)="question.onDownButtonClick()" (mousedown)="model.data.onMouseDown()"
        (mouseup)="question.onButtonMouseUp()" (mouseleave)="question.onButtonMouseLeave()" (blur)="question.onBlur($event)"
        (focus)="question.onFocus($event)" tabindex="-1">
        <svg [class]="modelAction.cssClasses.itemIcon" [iconName]="modelAction.iconName" [size]="'auto'" sv-ng-svg-icon></svg>
    </button>
</ng-template>
