// packages/survey-creator-react/src/Notifier.tsx
import React from "react";
import { Base, SurveyModel } from "survey-core";
import { SurveyElementBase, } from "survey-react-ui";
import { CreatorBase, Notifier } from "survey-creator-core";

export interface NotifierComponentProps {
  creator: CreatorBase;
  notifier: Notifier;
}

export class NotifierComponent extends SurveyElementBase<NotifierComponentProps, any> {
  get notifier() {
    return this.props.notifier;
  }
  protected getStateElement(): Base {
    return this.notifier;
  }
  renderElement(): JSX.Element {
    if (!this.notifier.active) {
      return null;
    }
    return (
      <div className={this.notifier.css}>
        <span>{this.notifier.message}</span>
      </div>
    );
  }
}

// packages/survey-creator-angular/src/notifier.component.ts
import { Component, Input } from "@angular/core";
import { Notifier } from "survey-creator-core";
import { BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-notifier",
  templateUrl: "./notifier.component.html",
  styles: [":host { display: none; }"]
})
export class NotifierComponent extends BaseAngular<Notifier> {
  @Input() notifier!: Notifier;
  getModel(): Notifier {
    return this.notifier;
  }
}
<ng-template #template>
  <div [surveyVisible]="notifier.active" [class]="notifier.css">
    <span>{{notifier.message}}</span>
  </div>
</ng-template>
