// packages/survey-creator-vue/src/tabs/designer/PageAddQuestion.vue
<template>
  <div
    :class="rootCss"
    v-on:click="
      (e) => {
        item.data.addNewQuestion(item, e);
        e.stopPropagation();
      }
    "
    v-key2click
    v-on:mouseover="(e) => item.data.hoverStopper && item.data.hoverStopper(e, e.currentTarget)"
  >
    <span class="svc-text svc-text--normal svc-text--bold">
      {{ item.data.addNewQuestionText }}
    </span>
    <button v-if="needRenderPopup"
      type="button"
      v-on:click="
        (e) => {
          item.data.questionTypeSelectorModel.action();
          e.stopPropagation();
        }
      "
      :title="item.title"
      v-key2click
      :aria-label="item.title"
      class="svc-element__question-type-selector"
    >
      <sv-svg-icon
        class="svc-element__question-type-selector-icon"
        v-bind="{
          iconName: item.data.questionTypeSelectorModel.iconName,
          size: 24,
          title: item.data.questionTypeSelectorModel.title,
        }"
      ></sv-svg-icon>
      <sv-popup v-if="needRenderPopup"
        :model="item.data.questionTypeSelectorModel.popupModel"
      ></sv-popup>
    </button>
  </div>
  <button v-if="!needRenderPopup"
    type="button"
    v-on:click="
      (e) => {
        item.data.questionTypeSelectorModel.action();
        e.stopPropagation();
      }
    "
    :title="item.title"
    v-key2click
    :aria-label="item.title"
    class="svc-element__question-type-selector"
  >
    <sv-svg-icon
      class="svc-element__question-type-selector-icon"
      v-bind="{
        iconName: item.data.questionTypeSelectorModel.iconName,
        size: 24,
        title: item.data.questionTypeSelectorModel.title,
      }"
    ></sv-svg-icon>
    <sv-popup v-if="needRenderPopup"
      :model="item.data.questionTypeSelectorModel.popupModel"
    ></sv-popup>
  </button>
</template>
<script lang="ts" setup>
import { computed } from "vue";
import type { Action } from "survey-core";
import type {} from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ item: Action, buttonClass: string, renderPopup: any}>();
useBase(() => props.item.data);
const rootCss = computed(() => 'svc-element__add-new-question ' + (props.buttonClass || 'svc-btn'));
const needRenderPopup = computed(() => props.renderPopup === undefined || props.renderPopup !== false);
</script>

// packages/survey-creator-angular/src/page-add-question.component.ts
import { Component } from "@angular/core";
import { ActionBarItemComponent, AngularComponentFactory } from "survey-angular-ui";

@Component(
  {
    selector: "svc-add-new-question-btn",
    templateUrl: "./page-add-question.component.html",
    styles: [":host { display: none; }"]
  }
)
export class AddQuestionButtonComponent extends ActionBarItemComponent {
  public get adorner() {
    return this.model.data;
  }
  public addNewQuestion(event: any) {
    event.stopPropagation();
    this.adorner.addNewQuestion(this.adorner, event);
  }
  public selectQuestionType(event: any) {
    event.stopPropagation();
    this.adorner.questionTypeSelectorModel.action();
  }
}
AngularComponentFactory.Instance.registerComponent("svc-add-new-question-btn", AddQuestionButtonComponent);
<ng-template #template>
  <div *ngIf="adorner.showAddQuestionButton" [class]="'svc-element__add-new-question ' + buttonClass" [key2click]
    (click)="addNewQuestion($event)"
    (mouseover)="adorner.hoverStopper && adorner.hoverStopper($event, $event.currentTarget)"
    data-bind="clickBubble: false">
    <span class="svc-text svc-text--normal svc-text--bold">
      {{ adorner.addNewQuestionText }}
    </span>
    <button *ngIf="renderPopup" type="button" [key2click] (click)="selectQuestionType($event)"
      [attr.title]="adorner.questionTypeSelectorModel.title" [attr.aria-label]="adorner.questionTypeSelectorModel.title"
      class="svc-element__question-type-selector">
      <svg class="svc-element__question-type-selector-icon" [iconName]="adorner.questionTypeSelectorModel.iconName"
        [size]="24" sv-ng-svg-icon></svg>
      <sv-ng-popup *ngIf="renderPopup" [popupModel]="adorner.questionTypeSelectorModel.popupModel"></sv-ng-popup>
    </button>
  </div>
  <button *ngIf="!renderPopup" type="button" [key2click] (click)="selectQuestionType($event)"
    [attr.title]="adorner.questionTypeSelectorModel.title" [attr.aria-label]="adorner.questionTypeSelectorModel.title"
    class="svc-element__question-type-selector">
    <svg class="svc-element__question-type-selector-icon" [iconName]="adorner.questionTypeSelectorModel.iconName"
      [size]="24" sv-ng-svg-icon></svg>
    <sv-ng-popup *ngIf="renderPopup" [popupModel]="adorner.questionTypeSelectorModel.popupModel"></sv-ng-popup>
  </button>
</ng-template>
