// packages/survey-creator-react/src/adorners/QuestionCarryForward.tsx
import { QuestionCarryForwardParams } from "survey-creator-core";
import React from "react";
import { ReactElementFactory } from "survey-react-ui";
import { ActionButton } from "../ActionButton";

export class QuestionCarrayForwardBanner extends React.Component<QuestionCarryForwardParams, any> {
  render(): JSX.Element {
    return (
      <div className="svc-carry-forward-panel-wrapper"><div className="svc-carry-forward-panel">
        <span>{this.props.text}{" "}</span>
        <span className="svc-carry-forward-panel__link">
          <ActionButton click={() => this.props.onClick()} text={this.props.question.name}></ActionButton>
        </span>
      </div></div>);
  }
}

ReactElementFactory.Instance.registerElement(
  "svc-question-carryforward",
  (props: QuestionCarryForwardParams) => {
    return React.createElement(QuestionCarrayForwardBanner, props);
  }
);

// packages/survey-creator-angular/src/question-carryforward.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular, EmbeddedViewContentComponent } from "survey-angular-ui";
import { QuestionCarryForwardParams } from "survey-creator-core";

@Component({
  selector: "svc-question-carryforward",
  templateUrl: "./question-carryforward.component.html",
  styles: [":host { display: none }"]
})
export class QuestionCarryForwardComponent extends EmbeddedViewContentComponent {
  @Input() model!: QuestionCarryForwardParams;
}

AngularComponentFactory.Instance.registerComponent("svc-question-carryforward", QuestionCarryForwardComponent);


<ng-template #template>
  <div class="svc-carry-forward-panel-wrapper">
    <div class="svc-carry-forward-panel">
    <span>{{model.text}} </span>
    <span class="svc-carry-forward-panel__link">
      <svc-action-button [text]="model.question.name" [click]="model.onClick.bind(model)">
      </svc-action-button>
    </span>
    </div>
  </div>
<ng-template>
