// packages/survey-creator-vue/src/adorners/Question.vue
<template>
  <div class="svc-question__adorner" :class="model.rootCss()" v-on:mouseover="e => model.hover(e, e.currentTarget)" v-on:mouseleave="e => model.hover(e, e.currentTarget)"
  :data-sv-drop-target-survey-element="model.element.name || null" data-bind="css: rootCss(), attr: { 'data-sv-drop-target-survey-element': element.name || null }, event: { mouseover: function(m, e) { hover(e, $element); }, mouseleave: function(m, e) { hover(e, $element); } }">
    <div v-on:click="e => { model.select(model, e); e.stopPropagation(); }" :class="model.css()" data-bind="click: koSelect, key2click, clickBubble: false, css: css()">
      <div v-if="model.allowDragging" class="svc-question__drag-area" v-on:pointerdown="e => model.onPointerDown(e)" data-bind="event: {pointerdown: (model, event)=>{onPointerDown(event)}}">
        <sv-svg-icon class="svc-question__drag-element" v-bind="{ css: 'svc-question__drag-element', iconName: 'icon-drag-area-indicator_24x16', size: 24 }"></sv-svg-icon>
      </div>

      <sv-template-renderer :componentName="model.templateData.name" :componentData="model.templateData.data"></sv-template-renderer>
      <div v-if="model.isEmptyElement && !model.placeholderComponentData" class="svc-panel__placeholder_frame">
        <div class="svc-panel__placeholder" data-bind="text: placeholderText">{{model.placeholderText}}</div>
      </div>
      <!-- ko if: koIsEmptyElement() && !!$data.placeholderComponentData -->
      <!-- ko let: { question: placeholderComponentData.data }  -->
      <!-- ko component: { name: 'sv-template-renderer', params: { componentData: null, templateData: placeholderComponentData } } -->
      <!-- /ko -->
      <!-- /ko -->
      <!-- /ko -->

      <!-- ko if: adornerComponent -->
      <!-- ko component: { name: adornerComponent, params: { model: $data } } -->
      <!-- /ko -->
      <!-- /ko -->
      <component
        v-if="!!model.adornerComponent"
        :is="model.adornerComponent"
        :model="model"
      />

      <!-- ko if: isUsingCarryForward -->
      <!-- ko component: { name: 'svc-question-carryforward', params: $data } -->
      <!-- /ko -->
      <!-- /ko -->
      <div class="svc-question__content-actions">
        <sv-action-bar :model="model.actionContainer" :handleClick="false"></sv-action-bar>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { useCreatorModel } from "@/creator-model";
import type { SurveyModel, Question } from "survey-core";
import type { CreatorBase } from "survey-creator-core";
import { QuestionAdornerViewModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{
  componentName: string;
  componentData: any;
}>();
// useBase(() => new PageAdorner(props.creator, props.page));
const model = useCreatorModel(() => new QuestionAdornerViewModel(
      props.componentData.data as CreatorBase,
      props.componentData.element as Question,
      { name: props.componentName, data: props.componentData }
    ), [() => props.componentName, () => props.componentData]);
</script>

// packages/survey-creator-angular/src/question.component.ts
import { ChangeDetectorRef, Component, Input, ViewContainerRef, ViewEncapsulation } from "@angular/core";
import { AngularComponentFactory, BaseAngular, EmbeddedViewContentComponent } from "survey-angular-ui";
import { PageModel, PanelModel, Question, SurveyModel } from "survey-core";
import { CreatorBase, QuestionAdornerViewModel } from "survey-creator-core";
import { CreatorModelComponent } from "./creator-model.component";

@Component({
  selector: "svc-question",
  templateUrl: "./question.component.html",
  styles: [":host { display: none; }"]
})
export class QuestionDesignerComponent extends CreatorModelComponent<QuestionAdornerViewModel> {
  @Input() componentName!: string;
  @Input() componentData!: any;
  public adorner!: QuestionAdornerViewModel;
  protected get creator(): CreatorBase {
    return this.componentData.data;
  }
  public get model(): Question | PanelModel {
    return this.componentData.model;
  }
  protected createModel(): void {
    if (this.componentData) {
      this.adorner = new QuestionAdornerViewModel(this.creator, this.model, <any>null);
    }
  }
  protected getPropertiesToTrack(): string[] {
    return ["model", "creator"];
  }
  protected getModel(): QuestionAdornerViewModel {
    return this.adorner;
  }
  public get placeholderComponent(): string {
    return "";
  }
  public get placeholderComponentData(): any {
    return null;
  }
  public get showPlaceholderComponent(): boolean {
    return false;
  }
  public selectQuestionType(event: any) {
    event.stopPropagation();
    this.adorner.questionTypeSelectorModel?.action(this.adorner.questionTypeSelectorModel, event);
  }
  public addNewQuestion(event: any) {
    event.stopPropagation();
    this.adorner.addNewQuestion();
  }
  adornerComponent = "";
}

AngularComponentFactory.Instance.registerComponent("svc-question", QuestionDesignerComponent);


<ng-template #template>
  <div *ngIf="model && adorner" class="svc-question__adorner" [class]="adorner.rootCss()"
    (mouseover)="adorner.hover($event, $event.target)" (mouseleave)="adorner.hover($event, $event.target)"
    [attr.data-sv-drop-target-survey-element]="adorner.element.name || null"
    data-bind="css: rootCss(), attr: { 'data-sv-drop-target-survey-element': element.name || null }, event: { mouseover: function(m, e) { hover(e, $element); }, mouseleave: function(m, e) { hover(e, $element); } }">

    <div *ngIf="adorner.element.isInteractiveDesignElement" class="svc-question__content" [class]="adorner.css()"
      [key2click] (click)="adorner.select(adorner, $event)"
      data-bind="click: koSelect, key2click, clickBubble: false, css: css()">
      <div *ngIf="adorner.allowDragging" class="svc-question__drag-area"
        data-bind="event: {pointerdown: (model, event)=>{onPointerDown(event)}}">
        <svg class="svc-question__drag-element" [iconName]="'icon-drag-area-indicator_24x16'" [size]="24"
          sv-ng-svg-icon></svg>
      </div>

      <ng-template [component]="{ name: 'sv-template-renderer', data: { model: model } }"></ng-template>

      <div *ngIf="adorner.isEmptyElement" class="svc-panel__placeholder_frame">
        <div class="svc-panel__placeholder" data-bind="text: placeholderText"></div>
        <div *ngIf="adorner.element.isPanel && adorner.showAddQuestionButton"
          class="svc-panel__add-new-question svc-action-button" [key2click] (click)="adorner.addNewQuestion()"
          data-bind="click: addNewQuestion, key2click, clickBubble: false">
          <span class="svc-text svc-text--normal svc-text--bold" data-bind="text: $data.addNewQuestionText">
            {{ adorner.addNewQuestionText }}
          </span>
        </div>
      </div>

      <!-- ko if: adornerComponent -->
      <!-- ko component: { name: adornerComponent, params: { model: $data } } -->
      <!-- /ko -->
      <!-- /ko -->

      <div *ngIf="!adorner.isEmptyElement && model.isPanel && adorner.showAddQuestionButton"
        class="svc-panel__add-new-question-container">
        <div class="svc-panel__add-new-question svc-action-button" [key2click] (click)="adorner.addNewQuestion()"
          data-bind="click: addNewQuestion, key2click, clickBubble: false">
          <span class="svc-text svc-text--normal svc-text--bold" data-bind="text: $data.addNewQuestionText">
            {{ adorner.addNewQuestionText }}
          </span>
        </div>
        <!-- ko with: questionTypeSelectorModel -->
        <button type="button" [attr.title]="adorner.addNewQuestionText" [key2click]
          (click)="adorner.questionTypeSelectorModel.action(adorner.questionTypeSelectorModel, $event)"
          data-bind="click: action, key2click, clickBubble: false, attr: { title: $data.addNewQuestionText }"
          class="svc-panel__question-type-selector">
          <svg class="svc-panel__question-type-selector-icon" [iconName]="adorner.questionTypeSelectorModel.iconName"
            [size]="24" sv-ng-svg-icon></svg>
          <!-- <sv-popup params="model: popupModel"></sv-popup> -->
        </button>
        <!-- /ko -->
      </div>

      <div class="svc-question__content-actions">
        <sv-action-bar [model]="adorner.actionContainer"></sv-action-bar>
      </div>
    </div>

    <ng-container *ngIf="!adorner.element.isInteractiveDesignElement">
      <ng-template [component]="{ name: 'sv-template-renderer', data: { model: model } }"></ng-template>

      <div *ngIf="adorner.isEmptyElement" class="svc-panel__placeholder_frame">
        <div class="svc-panel__placeholder" data-bind="text: placeholderText"></div>
        <div *ngIf="adorner.showAddQuestionButton" class="svc-panel__add-new-question svc-action-button" [key2click]
          (click)="adorner.addNewQuestion()" data-bind="click: addNewQuestion, key2click, clickBubble: false">
          <span class="svc-text svc-text--normal svc-text--bold" data-bind="text: $data.addNewQuestionText">
            {{ adorner.addNewQuestionText }}
          </span>
        </div>
      </div>

      <div *ngIf="!adorner.isEmptyElement" class="svc-panel__add-new-question-container">
        <div class="svc-panel__add-new-question svc-action-button" [key2click] (click)="adorner.addNewQuestion()"
          data-bind="click: addNewQuestion, key2click, clickBubble: false">
          <span class="svc-text svc-text--normal svc-text--bold" data-bind="text: $data.addNewQuestionText">
            {{ adorner.addNewQuestionText }}
          </span>
        </div>
        <!-- ko with: questionTypeSelectorModel -->
        <button type="button" [key2click]
          (click)="adorner.questionTypeSelectorModel.action(adorner.questionTypeSelectorModel, $event)"
          data-bind="click: action, key2click, clickBubble: false, attr: { title: $data.addNewQuestionText }"
          class="svc-panel__question-type-selector">
          <svg class="svc-panel__question-type-selector-icon" [iconName]="adorner.questionTypeSelectorModel.iconName"
            [size]="24" sv-ng-svg-icon></svg>
          <!-- <sv-popup params="model: popupModel"></sv-popup> -->
        </button>
        <!-- /ko -->
      </div>

    </ng-container>
  </div>
</ng-template>
