// packages/survey-creator-vue/src/adorners/QuestionBanner.vue
<template>
  <div class="svc-carry-forward-panel-wrapper">
    <div class="svc-carry-forward-panel">
      <span>{{ model.text }}{{ " " }}</span>
      <span class="svc-carry-forward-panel__link">
        <svc-action-button
          :text="model.actionText"
          :click="model.onClick.bind(model)"
        >
        </svc-action-button>
      </span>
    </div>
  </div>
</template>
<script lang="ts" setup>
import type { QuestionBannerParams } from "survey-creator-core";
defineProps<{ model: QuestionBannerParams }>();
</script>

// packages/survey-creator-angular/src/question-banner.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular, EmbeddedViewContentComponent } from "survey-angular-ui";
import { QuestionBannerParams } from "survey-creator-core";

@Component({
  selector: "svc-question-banner",
  templateUrl: "./question-banner.component.html",
  styles: [":host { display: none }"]
})
export class QuestionBannerComponent extends EmbeddedViewContentComponent {
  @Input() model!: QuestionBannerParams;
}

AngularComponentFactory.Instance.registerComponent("svc-question-banner", QuestionBannerComponent);


<ng-template #template>
  <div class="svc-carry-forward-panel-wrapper">
    <div class="svc-carry-forward-panel">
    <span>{{model.text}} </span>
    <span class="svc-carry-forward-panel__link">
      <svc-action-button [text]="model.actionText" [click]="model.onClick.bind(model)">
      </svc-action-button>
    </span>
    </div>
  </div>
  <ng-template>
