// packages/survey-creator-vue/src/tabs/designer/Row.vue
<template>
  <div :class="model.cssClasses">
    <div class="svc-row__drop-indicator svc-row__drop-indicator--top"></div>
    <div class="svc-row__drop-indicator svc-row__drop-indicator--bottom"></div>
    <slot></slot>
  </div>
</template>
<script lang="ts" setup>
import { useCreatorModel } from "@/creator-model";
import type { QuestionRowModel } from "survey-core";
import { SurveyCreatorModel, RowViewModel } from "survey-creator-core";
import { computed } from "vue";

const props = defineProps<{
  componentData: { creator: SurveyCreatorModel; row: QuestionRowModel };
}>();

const creator = computed(() => props.componentData.creator);
const row = computed(() => props.componentData.row);

const model = useCreatorModel(
  () => new RowViewModel(creator.value, row.value, undefined as any),
  [() => creator.value, () => row.value],
  (value) => {
    value.dispose();
  }
);
</script>

// packages/survey-creator-angular/src/row.component.ts
import { Component, Input } from "@angular/core";
import { QuestionRowModel } from "survey-core";
import { SurveyCreatorModel, RowViewModel } from "survey-creator-core";
import { CreatorModelComponent } from "./creator-model.component";
import { AngularComponentFactory } from "survey-angular-ui";

@Component({
  selector: "svc-row",
  templateUrl: "./row.component.html"
})
export class CreatorRowComponent extends CreatorModelComponent<RowViewModel> {
  @Input() componentData!: { creator: SurveyCreatorModel, row: QuestionRowModel };

  public model!: RowViewModel;

  public get row() {
    return this.componentData.row;
  }
  public get creator() {
    return this.componentData.creator;
  }
  protected getModel(): RowViewModel {
    return this.model;
  }
  createModel() {
    this.model = new RowViewModel(this.creator, this.row, <any>undefined);
  }
  getPropertiesToTrack(): string[] {
    return ["creator", "row"];
  }
  override ngOnDestroy(): void {
    super.ngOnDestroy();
    this.model.dispose();
  }

}

AngularComponentFactory.Instance.registerComponent("svc-row", CreatorRowComponent);
<ng-template #template>
  <div [class]="model.cssClasses">
    <div class="svc-row__drop-indicator svc-row__drop-indicator--top"></div>
    <div class="svc-row__drop-indicator svc-row__drop-indicator--bottom"></div>
    <sv-ng-row [row]="row"></sv-ng-row>
  </div>
</ng-template>
