// packages/survey-creator-vue/src/StringEditor.vue
<template>
  <span :class="className">
    <span class="svc-string-editor__content">
      <div
        class="svc-string-editor__border svc-string-editor__border--hover"
      ></div>
      <div
        class="svc-string-editor__border svc-string-editor__border--focus"
      ></div>
      <span class="svc-string-editor__input">
        <span
          role="textbox"
          v-if="!locString.hasHtml"
          class="sv-string-editor"
          spellcheck="false"
          @focus="onFocus"
          @paste="onPaste"
          @blur="onBlur"
          @input="baseModel?.onInput"
          @beforeInput="baseModel?.onBeforeInput"
          @keydown="baseModel?.onKeyDown"
          @keyup="baseModel?.onKeyUp"
          @compositionstart="baseModel?.onCompositionStart"
          @compositionend="baseModel?.onCompositionEnd"
          @mouseup="baseModel?.onMouseUp"
          @click="edit"
          :textContent="renderedHtml"
          :aria-placeholder="placeholder"
          :aria-label="placeholder || 'content editable'"
          :contenteditable="contentEditable"
          :tabindex="baseModel.tabIndex"
          ref="root"
        ></span>
        <span
          role="textbox"
          v-if="locString.hasHtml"
          class="sv-string-editor sv-string-editor--html"
          spellcheck="false"
          @focus="onFocus"
          @blur="onBlur"
          @keydown="baseModel?.onKeyDown"
          @keyup="baseModel?.onKeyUp"
          @compositionstart="baseModel?.onCompositionStart"
          @compositionend="baseModel?.onCompositionEnd"
          @mouseup="baseModel?.onMouseUp"
          @click="edit"
          :aria-placeholder="placeholder"
          :aria-label="placeholder || 'content editable'"
          :contenteditable="contentEditable"
          :tabindex="baseModel.tabIndex"
          v-html="renderedHtml"
          ref="root"
        ></span>
        <SvComponent
          :is="'sv-character-counter'"
          v-if="showCharacterCounter"
          :counter="characterCounter"
          :remainingCharacterCounter="getCharacterCounterClass"
        ></SvComponent>
      </span>
    </span>
    <span v-if="errorText" class="svc-string-editor__error">{{
      errorText
    }}</span>
  </span>
</template>
<script setup lang="ts">
import { SvComponent } from "survey-vue3-ui";
import type { LocalizableString } from "survey-core";
import {
  StringEditorViewModelBase,
  type SurveyCreatorModel,
} from "survey-creator-core";
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import { useCreatorModel } from "./creator-model";

const props = defineProps<{ locString: any }>();
const locString = computed<LocalizableString>(() => {
  return props.locString.locStr;
});
const creator = computed<SurveyCreatorModel>(() => {
  return props.locString.creator;
});
const root = ref<HTMLElement>();

const renderedHtml = ref<string>();

const baseModel = useCreatorModel(
  () => {
    const baseModel = new StringEditorViewModelBase(
      locString.value,
      creator.value
    );
    baseModel.setLocString(locString.value);
    baseModel.blurEditor = () => {
      if (root.value) {
        root.value.blur();
        root.value.spellcheck = false;
      }
    };
    baseModel.getEditorElement = () => root.value as HTMLElement;
    setTimeout(() => baseModel.afterRender());
    return baseModel;
  },
  [() => creator.value, () => locString.value],
  (baseModel) => {
    if (baseModel) {
      baseModel.blurEditor = undefined as any;
      baseModel.getEditorElement = undefined as any;
      baseModel.dispose();
    }
  }
);

const errorText = computed(() => baseModel.value?.errorText);
const className = computed(() => {
  return baseModel.value?.className(locString.value.renderedHtml);
});
const placeholder = computed(() => baseModel.value?.placeholder);
const contentEditable = computed(() => baseModel.value?.contentEditable);
const characterCounter = computed(() => baseModel.value?.characterCounter);
const showCharacterCounter = computed(
  () => baseModel.value?.showCharacterCounter
);
const getCharacterCounterClass = computed(
  () => baseModel.value?.getCharacterCounterClass
);

const onBlur = (event: any) => {
  if (root.value) root.value.spellcheck = false;
  (locString.value as any).__isEditing = false;
  baseModel.value?.onBlur(event);
  return baseModel.value?.errorText;
};

const onFocus = (event: any): void => {
  baseModel.value?.onFocus(event);
};
const onPaste = (event: any): void => {
  baseModel.value?.onPaste(event);
};
const edit = (event: any): void => {
  root.value?.focus();
  (locString.value as any).__isEditing = true;
  baseModel.value?.onClick(event);
};

const onChangeHandler = (): void => {
  renderedHtml.value = locString.value.renderedHtml;
};
const stopWatch = watch(
  () => locString.value,
  (newValue, oldValue) => {
    if (oldValue) {
      newValue.onStringChanged.remove(onChangeHandler);
    }
    if (newValue) {
      newValue.onStringChanged.add(onChangeHandler);
      onChangeHandler();
    }
  },
  {
    immediate: true,
  }
);
onMounted(() => {
  if ((locString.value as any).__isEditing) {
    root.value?.focus();
  }
});
onUnmounted(() => {
  stopWatch();
  locString.value.onStringChanged.remove(onChangeHandler);
});
</script>

// packages/survey-creator-angular/src/string-editor.component.ts
import { AfterViewInit, ChangeDetectorRef, Component, ElementRef, Input, NgZone, ViewChild, ViewContainerRef } from "@angular/core";
import { LocalizableString, CharacterCounter } from "survey-core";
import { StringEditorViewModelBase, SurveyCreatorModel, editableStringRendererName } from "survey-creator-core";
import { CreatorModelComponent } from "./creator-model.component";
import { AngularComponentFactory } from "survey-angular-ui";

@Component({
  selector: "svc-string-edtior",
  templateUrl: "./string-editor.component.html",
  styles: [":host { display: none; }"]
})
export class StringEditorComponent extends CreatorModelComponent<StringEditorViewModelBase> implements AfterViewInit {
  public baseModel!: StringEditorViewModelBase;
  private justFocused: boolean = false;
  @Input() model!: any;
  @ViewChild("container") container!: ElementRef<HTMLElement>;
  constructor(cdr: ChangeDetectorRef, vcr: ViewContainerRef, private ngZone: NgZone) {
    super(cdr, vcr);
  }
  public createModel(): void {
    this.baseModel = new StringEditorViewModelBase(this.locString, this.creator);
    this.baseModel.setLocString(this.locString);
    this.baseModel.blurEditor = () => {
      this.container.nativeElement.blur();
      this.container.nativeElement.spellcheck = false;
    };
    this.baseModel.getEditorElement = () => this.container.nativeElement;
    this.ngZone.runOutsideAngular(() => {
      setTimeout(() => this.baseModel.afterRender());
    });
  }
  public get locString(): LocalizableString {
    return this.model.locStr;
  }
  public get creator(): SurveyCreatorModel {
    return this.model.creator;
  }
  protected getModel(): StringEditorViewModelBase {
    return this.baseModel;
  }
  protected getPropertiesToTrack(): string[] {
    return ["creator", "locString"];
  }
  public get placeholder(): string {
    return this.baseModel.placeholder;
  }
  public get contentEditable(): boolean {
    return this.baseModel.contentEditable;
  }
  public get characterCounter(): CharacterCounter {
    return this.baseModel.characterCounter;
  }
  public get showCharacterCounter(): boolean {
    return this.baseModel.showCharacterCounter;
  }
  public get getCharacterCounterClass(): string {
    return this.baseModel.getCharacterCounterClass;
  }

  public get className(): string {
    return this.baseModel.className(this.locString.renderedHtml);
  }
  public get errorText(): string {
    return this.baseModel.errorText;
  }
  onChangeHandler = (): void => {
    this.detectChanges();
  }
  public onBlur(event: any): string {
    this.container.nativeElement.spellcheck = false;
    (<any>this.locString).__isEditing = false;
    this.justFocused = false;
    this.baseModel.onBlur(event);
    return this.baseModel.errorText;
  }
  public onFocus(event: any): void {
    this.baseModel.onFocus(event);
    this.justFocused = true;
  }
  public onPaste(event: any): void {
    this.baseModel.onPaste(event);
  }
  public done(event: any): void {
    this.baseModel.done(event);
    (<any>this.locString).__isEditing = false;
  }
  public edit(event: any): void {
    this.container.nativeElement.focus();
    (<any>this.locString).__isEditing = true;
    this.baseModel.onClick(event);
  }
  override ngOnInit(): void {
    super.ngOnInit();
    this.locString?.onStringChanged.add(this.onChangeHandler);
  }
  ngAfterViewInit(): void {
    if ((<any>this.locString).__isEditing) {
      this.container.nativeElement.focus();
    }
  }
  override ngOnDestroy(): void {
    this.baseModel.blurEditor = undefined as any;
    this.baseModel.getEditorElement = undefined as any;
    this.baseModel.dispose();
    this.locString?.onStringChanged.remove(this.onChangeHandler);
    super.ngOnDestroy();
  }
  get ariaLabel(): string {
    return this.placeholder || "content editable";
  }
}

AngularComponentFactory.Instance.registerComponent(editableStringRendererName, StringEditorComponent);
<ng-template #template>
  <span [class]="className">
    <span class="svc-string-editor__content">
      <div class="svc-string-editor__border svc-string-editor__border--hover"></div>
        <div class="svc-string-editor__border svc-string-editor__border--focus"></div>
        <span class="svc-string-editor__input">
          <span role="textbox" *ngIf="!locString.hasHtml" class="sv-string-editor" spellcheck="false"
              (focus)="onFocus($event)" (paste)="onPaste($event)" (blur)="onBlur($event)" (beforeinput)="baseModel.onBeforeInput($event)" (input)="baseModel.onInput($event)" (keydown)="baseModel.onKeyDown($event)" (keyup)="baseModel.onKeyUp($event)" (compositionstart)="baseModel.onCompositionStart($event)" (compositionend)="baseModel.onCompositionEnd($event)" (mouseup)="baseModel.onMouseUp($event)" (click)="edit($event)" [textContent]="locString.renderedHtml" [attr.aria-placeholder]="placeholder" [attr.aria-label]="ariaLabel" [attr.contenteditable]="contentEditable" [attr.tabIndex]="baseModel.tabIndex" #container></span>
          <span role="textbox" *ngIf="locString.hasHtml" class="sv-string-editor sv-string-editor--html" spellcheck="false"
          (focus)="onFocus($event)" (blur)="onBlur($event)" (keydown)="baseModel.onKeyDown($event)" (keyup)="baseModel.onKeyUp($event)" (compositionstart)="baseModel.onCompositionStart($event)" (compositionend)="baseModel.onCompositionEnd($event)" (mouseup)="baseModel.onMouseUp($event)"
          (click)="edit($event)" [attr.aria-placeholder]="placeholder" [attr.aria-label]="ariaLabel" [attr.contenteditable]="contentEditable" [attr.tabIndex]="baseModel.tabIndex" [innerHtml]="locString.renderedHtml | safeHtml" #container></span>
          <sv-ng-character-counter *ngIf="showCharacterCounter" [counter]="characterCounter" [remainingCharacterCounter]="getCharacterCounterClass"></sv-ng-character-counter>
        </span>
    </span>
    <span *ngIf="errorText" class="svc-string-editor__error">{{errorText}}</span>
  </span>
</ng-template>
