// packages/survey-creator-angular/src/tabbed-menu/tabbed-menu/tabbed-menu.component.ts
import { AfterViewInit, Component, ElementRef, Input, ViewChild } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { TabbedMenuContainer, TabbedMenuItem } from "survey-creator-core";

@Component({
  selector: "svc-tabbed-menu",
  templateUrl: "./tabbed-menu.component.html",
  styles: [":host { display: none; }"]
})
export class TabbledMenuComponent extends BaseAngular<TabbedMenuContainer> implements AfterViewInit {
  @Input() model!: TabbedMenuContainer;
  @ViewChild("container") container!: ElementRef<HTMLDivElement>;
  protected getModel(): TabbedMenuContainer {
    return this.model;
  }
  ngAfterViewInit(): void {
    this.model.initResponsivityManager(this.container.nativeElement);
  }
  override ngOnDestroy(): void {
    super.ngOnDestroy();
    this.model.resetResponsivityManager();
  }
  trackItemBy(_: number, item: TabbedMenuItem) {
    return item.renderedId;
  }

}
AngularComponentFactory.Instance.registerComponent("svc-tabbed-menu", TabbledMenuComponent);
<ng-template #template>
  <div class="svc-tabbed-menu" #container role="tablist" :style="model.getRootStyle()">
    <ng-container *ngFor="let action of model.renderedActions; trackBy: trackItemBy">
      <svc-tabbed-menu-item-wrapper [model]="action"></svc-tabbed-menu-item-wrapper>
    </ng-container>
  </div>
</ng-template>

// packages/survey-creator-vue/src/tabbed-menu/TabbedMenu.vue
<template>
  <div class="svc-tabbed-menu" ref="container" role="tablist" :style="model.getRootStyle()">
    <template v-for="action in model.renderedActions" :key="action.renderedId">
      <SvComponent
        :is="'svc-tabbed-menu-item-wrapper'"
        :item="action"
      ></SvComponent>
    </template>
  </div>
</template>
<script setup lang="ts">
import { SvComponent } from "survey-vue3-ui";
import type { TabbedMenuContainer } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { onMounted, onUnmounted, ref } from "vue";
const props = defineProps<{ model: TabbedMenuContainer }>();
const container = ref();
useBase(() => props.model);
onMounted(() => {
  props.model.initResponsivityManager(container.value)
});
onUnmounted(() => {
  props.model.resetResponsivityManager();
});
</script>
