// packages/survey-creator-angular/src/tabbed-menu/tabbed-menu/tabbed-menu-item.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { TabbedMenuItem } from "survey-creator-core";

@Component({
  selector: "svc-tabbed-menu-item",
  templateUrl: "./tabbed-menu-item.component.html",
  styles: [":host { display: none; }"]
})
export class TabbedMenuItemComponent extends BaseAngular<TabbedMenuItem> {
  @Input() model!: TabbedMenuItem;
  protected getModel(): TabbedMenuItem {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-tabbed-menu-item", TabbedMenuItemComponent);
<ng-template #template>
  <div
    [class]="model.getRootCss()"
    (click)="model.doAction()"
    [key2click]
    role="tab"
    [attr.id]="'tab-' + model.id"
    [attr.aria-selected]="model.active"
    [attr.aria-controls]="'scrollableDiv-' + model.id"
  >
    <span *ngIf="model.hasTitle" [class]="model.getTitleCss()">
      {{ model.title }}
    </span>
    <svg
      *ngIf="model.hasIcon"
      [iconName]="model.iconName"
      [size]="'auto'"
      [class]="model.getIconCss()"
      [title]="model.tooltip || model.title"
      sv-ng-svg-icon
    ></svg>
  </div>
</ng-template>

// packages/survey-creator-vue/src/tabbed-menu/TabbedMenuItem.vue
<template>
  <div
    class="svc-tabbed-menu-item"
    :class="item.getRootCss()"
    @click="item.action"
    v-key2click
  >
    <span v-if="item.hasTitle" :class="item.getTitleCss()">
      {{ item.title }}
    </span>
    <SvComponent
      v-if="item.hasIcon"
      :is="'sv-svg-icon'"
      :iconName="item.iconName"
      :size="'auto'"
      :class="item.getIconCss()"
      :title="item.tooltip || item.title"
    ></SvComponent>
  </div>
</template>
<script setup lang="ts">
import { SvComponent, key2ClickDirective as vKey2click } from "survey-vue3-ui";
import type { TabbedMenuItem } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
const props = defineProps<{ item: TabbedMenuItem }>();
useBase(() => props.item);
</script>
