// packages/survey-creator-vue/src/toolbox/AdaptiveToolbox.vue
<template>
  <div :class="toolbox.classNames" ref="root">
    <div @focusout="(e) => toolbox.focusOut(e)" class="svc-toolbox__panel">
      <div v-if="toolbox.showSearch" class="svc-toolbox__search-container">
        <template v-if="toolbox.isCompactRendered">
          <SvComponent
            :is="'svc-toolbox-tool'"
            :creator="creator"
            key="searchitem"
            :item="toolbox.searchItem"
            :parentModel="toolbox"
            :isCompact="toolbox.isCompactRendered"
          ></SvComponent>
        </template>
        <SvComponent
            :is="'svc-search'"
            :model="toolbox.searchManager"
        ></SvComponent>
        <div
            class="svc-toolbox__category-separator svc-toolbox__category-separator--search"
          ></div>
      </div>
      <div @focusout="(e) => toolbox.focusOut(e)" class="svc-toolbox__scroll-wrapper">
        <div
          class="svc-toolbox__scroller sv-drag-target-skipped"
          @scroll="
            (e) => {
              toolbox.onScroll(toolbox, e);
            }
          "
        >
          <div v-if="toolbox.showPlaceholder" class="svc-toolbox__placeholder">
            {{ toolbox.toolboxNoResultsFound }}
          </div>
          <div class="svc-toolbox__container">
            <template v-if="!toolbox.showInSingleCategory">
              <SvComponent
                :is="'svc-toolbox-category'"
                v-for="(category, index) in toolbox.categories"
                :key="index"
                :category="category"
                :toolbox="toolbox"
              ></SvComponent>
            </template>
            <template v-if="toolbox.showInSingleCategory">
              <div class="svc-toolbox__category">
                <template v-for="(item, index) in renderedActions" :key="index">
                  <SvComponent
                    :is="'svc-toolbox-tool'"
                    :creator="creator"
                    :item="item"
                    :parentModel="toolbox"
                    :isCompact="toolbox.isCompactRendered"
                  ></SvComponent>
                </template>
              </div>
            </template>
          </div>
        </div>
        <div class="svc-toolbox__scrollbar" @scroll="
            (e) => {
              toolbox.onScrollbarScroll(e);
            }
          ">
          <div class="svc-toolbox__scrollbar-sizer">
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import { VerticalResponsivityManager } from "survey-core";
import type { SurveyCreatorModel } from "survey-creator-core";
import { useBase } from "survey-vue3-ui";
import { computed, onMounted, onUnmounted, ref } from "vue";
const props = defineProps<{ creator: SurveyCreatorModel }>();
const toolbox = computed(() => {
  return props.creator.toolbox;
});

const root = ref<HTMLDivElement>();

useBase(() => toolbox.value);
let responsivityManager: VerticalResponsivityManager;
onMounted(() => {
  toolbox.value.setRootElement(root.value as HTMLDivElement);
  responsivityManager = new VerticalResponsivityManager(
    toolbox.value.containerElement as HTMLDivElement,
    toolbox.value,
    toolbox.value.itemSelector
  );
});
onUnmounted(() => {
  responsivityManager?.dispose();
  toolbox.value.setRootElement(undefined as any);
  toolbox.value.unsubscribeRootElement();
});
const renderedActions = computed(() => toolbox.value.renderedActions);
</script>

// packages/survey-creator-react/src/toolbox/AdaptiveToolbox.tsx
import * as React from "react";
import { VerticalResponsivityManager } from "survey-core";
import { ReactElementFactory } from "survey-react-ui";
import { ISurveyCreatorToolboxProps, Toolbox } from "./Toolbox";
import { SurveyCreatorToolboxTool } from "./ToolboxItem";
import { SearchComponent } from "../side-bar/Search";

export class AdaptiveToolbox extends Toolbox {
  private manager: VerticalResponsivityManager;
  private rootRef: React.RefObject<HTMLDivElement>;

  constructor(props: ISurveyCreatorToolboxProps) {
    super(props);
    this.rootRef = React.createRef();
  }

  componentDidMount() {
    super.componentDidMount();
    const container = this.rootRef.current;
    this.toolbox.setRootElement(container);
    if (!container) return;
    this.manager = new VerticalResponsivityManager(
      this.toolbox.containerElement as HTMLDivElement,
      this.toolbox,
      this.toolbox.itemSelector,
      null,
      undefined,
      (callback) => setTimeout(callback)
    );
  }
  componentWillUnmount() {
    this.manager && (this.manager.dispose());
    this.toolbox.unsubscribeRootElement();
    super.componentWillUnmount();
  }

  renderSearch() {
    const searchButton = this.toolbox.isCompactRendered ?
      <>
        <SurveyCreatorToolboxTool item={this.toolbox.searchItem as any} creator={this.creator} parentModel={this.toolbox} isCompact={this.toolbox.isCompactRendered} key={"searchitem"} ></SurveyCreatorToolboxTool>
        <div className="svc-toolbox__category-separator svc-toolbox__category-separator--search"></div>
      </> :
      null;
    return (<div className="svc-toolbox__search-container">
      {searchButton}
      <SearchComponent model={this.toolbox.searchManager}></SearchComponent>
    </div>);
  }

  render(): JSX.Element {
    if (!this.toolbox.hasActions) return null;
    const search = this.toolbox.showSearch ? this.renderSearch() : null;
    const placeholder = this.toolbox.showPlaceholder ? <div className="svc-toolbox__placeholder">{this.toolbox.toolboxNoResultsFound}</div> : null;
    return (
      <div ref={this.rootRef} className={this.toolbox.classNames}>
        <div onBlur={(e) => this.toolbox.focusOut(e)} className="svc-toolbox__panel">
          {search}
          <div onBlur={(e) => this.toolbox.focusOut(e)} className="svc-toolbox__scroll-wrapper">
            <div className="svc-toolbox__scroller sv-drag-target-skipped" onScroll={(event) => this.toolbox.onScroll(this.toolbox, event)}>
              {placeholder}
              <div className="svc-toolbox__container">
                {(this.toolbox.showInSingleCategory) ?
                  (<div className="svc-toolbox__category">
                    {this.renderItems(this.toolbox.renderedActions, this.toolbox.isCompactRendered)}
                  </div>)
                  : this.renderCategories()
                }
              </div>
            </div>
            <div className="svc-toolbox__scrollbar" onScroll={(event) => this.toolbox.onScrollbarScroll(event.nativeEvent)}>
              <div className="svc-toolbox__scrollbar-sizer">
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-adaptive-toolbox", (props) => {
  return React.createElement(AdaptiveToolbox, props);
});
