// packages/survey-creator-vue/src/toolbox/ToolboxCategory.vue
<template>
  <div
    class="svc-toolbox__category"
    :class="{
      'svc-toolbox__category--collapsed': category.collapsed,
      'svc-toolbox__category--empty': category.empty,
    }"
  >
    <div
      class="svc-toolbox__category-header"
      @click="category.toggleState()"
      v-key2click
      :class="{
        'svc-toolbox__category-header--collapsed':
          toolbox.canCollapseCategories,
      }"
    >
      <span class="svc-toolbox__category-title">{{ category.title }}</span>
      <div
        v-if="toolbox.canCollapseCategories"
        class="svc-toolbox__category-header__controls"
      >
        <div className="svc-toolbox__category-header-wrapper">
          <SvComponent
            :is="'sv-svg-icon'"
            :iconName="'icon-arrow-down'"
            class="svc-toolbox__category-header__button svc-string-editor__button--expand"
            :size="'auto'"
            v-show="category.collapsed"
          ></SvComponent>
        </div>
        <SvComponent
          :is="'sv-svg-icon'"
          :iconName="'icon-arrow-up'"
          class="svc-toolbox__category-header__button svc-string-editor__button--collapse"
          :size="'auto'"
          v-show="!category.collapsed"
        ></SvComponent>
      </div>
    </div>
    <SvComponent
      :is="'svc-toolbox-tool'"
      v-for="item in category.items"
      :item="item"
      :key="item.renderedId"
      :creator="toolbox.creator"
      :parentModel="toolbox"
      :isCompact="false"
    ></SvComponent>
  </div>
</template>
<script lang="ts" setup>
import { key2ClickDirective as vKey2click } from "survey-vue3-ui";
import { SvComponent } from "survey-vue3-ui";
import type {
  QuestionToolbox,
  QuestionToolboxCategory,
} from "survey-creator-core";
import { useBase } from "survey-vue3-ui";

const props = defineProps<{
  category: QuestionToolboxCategory;
  toolbox: QuestionToolbox;
}>();
useBase(() => props.category);
</script>

// packages/survey-creator-react/src/toolbox/ToolboxCategory.tsx
import * as React from "react";
import { Base } from "survey-core";
import { attachKey2click, ReactElementFactory, SurveyElementBase, SvgIcon } from "survey-react-ui";
import { QuestionToolbox, QuestionToolboxCategory } from "survey-creator-core";
import { SurveyCreatorToolboxTool } from "./ToolboxItem";

export interface ISurveyCreatorToolboxCategoryProps {
  category: QuestionToolboxCategory;
  toolbox: QuestionToolbox;
}

export class SurveyCreatorToolboxCategory extends SurveyElementBase<ISurveyCreatorToolboxCategoryProps, any> {

  public get category() {
    return this.props.category;
  }
  public get toolbox() {
    return this.props.toolbox;
  }
  public get class() {
    return "svc-toolbox__category" +
      (this.category.collapsed ? " svc-toolbox__category--collapsed" : "") +
      (this.category.empty ? " svc-toolbox__category--empty" : "");
  }

  protected getStateElement(): Base {
    return (this.category as any);
  }

  render(): React.JSX.Element {
    const header = this.renderCategoryHeader();
    const items = this.renderCategoryContent();
    return (
      <div className={this.class} key={this.category.name}>
        <div className="svc-toolbox__category-header-wrapper">
          {header}
        </div>
        {items}
      </div>
    );
  }

  renderCategoryHeader(): React.JSX.Element {
    let className = "svc-toolbox__category-header";
    if (this.toolbox.canCollapseCategories) {
      className += " svc-toolbox__category-header--collapsed";
    }
    return attachKey2click(
      <div className={className} onClick={e => this.category.toggleState()}>
        <span className="svc-toolbox__category-title">{this.category.title}</span>
        {this.renderButton()}
      </div>
    );
  }

  renderButton(): React.JSX.Element {
    if (!this.toolbox.canCollapseCategories) return null;

    const iconName = this.category.collapsed ? "arrow-down" : "arrow-up";
    const suffixName = this.category.collapsed ? "expand" : "collapse";
    const svgIconClassName = "svc-toolbox__category-header__button svc-string-editor__button--" + suffixName;
    return (<div className="svc-toolbox__category-header__controls">
      <SvgIcon className={svgIconClassName} iconName={"icon-" + iconName} size={"auto"}></SvgIcon>
    </div>);
  }

  protected renderCategoryContent(): Array<any> {
    return this.renderItems(this.category.items);
  }

  renderItems(items: Array<any>, isCompact = false) {
    return items.map((item, itemIndex) =>
      <SurveyCreatorToolboxTool item={(item as any)} creator={this.toolbox.creator} parentModel={this.toolbox} isCompact={isCompact} key={"item" + itemIndex} ></SurveyCreatorToolboxTool>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-toolbox-category", (props) => {
  return React.createElement(SurveyCreatorToolboxCategory, props);
});
