// packages/survey-creator-angular/src/toolbox/toolbox-item-group.component.ts
import { Component, Input } from "@angular/core";
import { ToolboxToolViewModel, SurveyCreatorModel, IQuestionToolboxItem } from "survey-creator-core";
import { BaseAngular, AngularComponentFactory } from "survey-angular-ui";

@Component({
  selector: "svc-toolbox-item-group",
  templateUrl: "./toolbox-item-group.component.html",
  styles: [":host { display: none; }"]
})
export class ToolboxItemGroupComponent extends BaseAngular<ToolboxToolViewModel> {
  @Input() creator!: SurveyCreatorModel;
  @Input() model!: IQuestionToolboxItem;
  @Input() isCompact: boolean = false;
  @Input() viewModel!: ToolboxToolViewModel
  protected getModel(): ToolboxToolViewModel {
    return this.viewModel;
  }
  public get item() {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("svc-toolbox-item-group", ToolboxItemGroupComponent);

<ng-template #template>
  <svc-toolbox-item [model]="item" [viewModel]="viewModel" [creator]="creator" [isCompact]="isCompact"></svc-toolbox-item>
  <div class="svc-toolbox__item-submenu-button" (mouseover)="viewModel.onMouseOver(item, $event)"
    (mouseleave)="viewModel.onMouseLeave(item, $event)">
    <svg [iconName]="item.subitemsButtonIcon" [size]="'auto'" sv-ng-svg-icon></svg>
    <sv-ng-popup [popupModel]="model.popupModel" [getArea]="model.getArea"></sv-ng-popup>
  </div>
</ng-template>

// packages/survey-creator-react/src/toolbox/ToolboxItemGroup.tsx
import * as React from "react";
import { Base } from "survey-core";
import { Popup, ReactElementFactory, SvgIcon } from "survey-react-ui";
import { CreatorModelElement } from "../ModelElement";
import { ISurveyCreatorToolboxItemProps, SurveyCreatorToolboxItem } from "./ToolboxItem";

export class SurveyCreatorToolboxItemGroup extends CreatorModelElement<ISurveyCreatorToolboxItemProps, any> {
  constructor(props) {
    super(props);
  }
  protected getUpdatedModelProps(): string[] {
    return ["creator", "item"];
  }
  public get item() {
    return this.props.item;
  }
  public get model() {
    return this.props.model;
  }
  public get creator() {
    return this.props.creator;
  }
  public get isCompact() {
    return this.props.isCompact;
  }
  public get parentModel() {
    return this.props.parentModel;
  }

  protected getStateElement(): Base {
    return this.item;
  }
  render(): JSX.Element {
    return <>
      <SurveyCreatorToolboxItem item={this.item} creator={this.creator} model={this.model} parentModel={this.parentModel} isCompact={this.isCompact} ></SurveyCreatorToolboxItem >
      <div className="svc-toolbox__item-submenu-button"
        onMouseOver={(event: any) => this.model.onMouseOver(this.item, event)}
        onMouseLeave={(event: any) => this.model.onMouseLeave(this.item, event)}
      >
        <SvgIcon size={"auto"} iconName={this.item.subitemsButtonIcon} ></SvgIcon>
        <Popup model={this.item.popupModel} getArea={this.item.getArea} />
      </div>
    </>;
  }
}

ReactElementFactory.Instance.registerElement("svc-toolbox-item-group", (props) => {
  return React.createElement(SurveyCreatorToolboxItemGroup, props);
});
