// packages/survey-creator-vue/src/components/ActionButton.vue
<template>
  <span
    v-if="disabled"
    class="svc-action-button svc-action-button--disabled"
    :class="classes"
    :title="title"
    >{{ text }}</span
  >
  <span
    v-if="!disabled"
    role="button"
    class="svc-action-button"
    @click="onClick"
    v-key2click
    :title="title"
    :class="{ 'svc-action-button--selected': selected, classes }"
    >{{ text }}</span
  >
</template>
<script lang="ts" setup>
const props = defineProps<{
  classes?: string;
  selected?: boolean;
  disabled?: boolean;
  text: string;
  title?: string;
  allowBubble?: boolean;
  click: () => void;
}>();

const onClick = (event: Event) => {
  props.click();
  if (!props.allowBubble) {
    event.stopPropagation();
  }
};
</script>

// packages/survey-creator-react/src/components/ActionButton.tsx
import React from "react";
import { attachKey2click, SurveyElementBase, } from "survey-react-ui";

export class ActionButton extends SurveyElementBase<any, any> {
  constructor(props: any) {
    super(props);
  }

  renderElement(): JSX.Element {
    let classes = this.props.classes + " svc-action-button";
    if (this.props.selected) {
      classes += " svc-action-button--selected";
    }
    if (this.props.disabled) {
      classes += " svc-action-button--disabled";
      return <span className={classes}>{this.props.text}</span>;
    }
    return (
      <>
        {attachKey2click(
          <span
            role="button"
            className={classes}
            onClick={(e) => {
              e.stopPropagation();
              this.props.click();
            }}
            title={this.props.title}
          >
            {this.props.text}
          </span>
        )}
      </>
    );
  }
}
