// packages/survey-creator-angular/src/adorners/cell-question-dropdown.component.ts
import { Component, Input } from "@angular/core";
import { ItemValue, QuestionDropdownModel } from "survey-core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";
import { QuestionAdornerViewModel } from "survey-creator-core";

@Component({
  selector: "svc-cell-dropdown-question",
  templateUrl: "./cell-question-dropdown.component.html",
  styles: [":host { display: none; }"]
})
export class CellQuestionDropdownComponent extends BaseAngular<QuestionDropdownModel> {
  @Input() componentName!: string;
  @Input() componentData!: any;
  protected getModel(): QuestionDropdownModel {
    return this.model;
  }
  public get model(): QuestionDropdownModel {
    return this.componentData.model;
  }
  public getItemValueComponentName(item: ItemValue): string {
    return this.model.getItemValueWrapperComponentName(item) || "sv-ng-selectbase-item";
  }
  public getItemValueComponentData(item: ItemValue): any {
    return {
      componentName: "sv-ng-selectbase-item",
      componentData: {
        question: this.model,
        model: item,
        inputType: "radio",
        data: this.model.getItemValueWrapperComponentData(item)
      }
    };
  }
}
AngularComponentFactory.Instance.registerComponent("svc-cell-dropdown-question", CellQuestionDropdownComponent);
<ng-template #template>
  <div class="svc-question__adorner">
    <div class="svc-question__content svc-question__content--selected-no-border">
      <ng-template [component]="{ name: componentName, data: componentData }"></ng-template>
      <div class="svc-question__dropdown-choices">
          <div *ngFor="let item of model.visibleChoices"class="svc-question__dropdown-choice">
            <ng-template [component]="{ name: getItemValueComponentName(item), data: getItemValueComponentData(item) }"></ng-template>
          </div>
    </div>

    </div>
  </div>
</ng-template>

// packages/survey-creator-react/src/components/CellQuestionDropdown.tsx
import { QuestionAdornerViewModel, toggleHovered } from "@survey/creator";
import React from "react";
import { ReactDragEvent, ReactMouseEvent } from "../events";
import { Base, ItemValue } from "survey-core";
import {
  ReactElementFactory,
  SurveyElementBase,
} from "survey-react-ui";
import { QuestionAdornerComponentProps } from "./Question";

export class CellQuestionDropdownAdornerComponent extends SurveyElementBase<
  QuestionAdornerComponentProps,
  any
> {
  model: QuestionAdornerViewModel;
  constructor(props: QuestionAdornerComponentProps) {
    super(props);
    this.model = new QuestionAdornerViewModel(
      this.props.componentData,
      this.props.question,
      null
    );
  }
  protected getStateElement(): Base {
    return this.model;
  }

  render(): JSX.Element {
    if (this.model.isDragged) {
      return null;
    }
    const question = this.props.question;
    return (
      <React.Fragment>
        <div
          data-svc-drop-target-element-name={this.model.surveyElement.name}
          className={"svc-question__adorner"}
        >
          <div
            className={" svc-question__content--selected-no-border svc-question__content"}
            onClick={(e) => this.model.select(this.model, new ReactMouseEvent(e))}
          >

            {this.props.element}

            <div className="svc-question__dropdown-choices">
                {(question.visibleChoices.map((item: ItemValue, index: number) => (
                  <div className="svc-question__dropdown-choice" key={`editable_choice_${index}`}>
                    {(question.survey["wrapItemValue"](SurveyElementBase.renderLocString(item.locText), question, item))}
                </div>
              )))}

            </div>

          </div>
        </div>
      </React.Fragment >
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "svc-cell-dropdown-question",
  (props: QuestionAdornerComponentProps) => {
    return React.createElement(CellQuestionDropdownAdornerComponent, props);
  }
);
