// packages/survey-creator-angular/src/components/component-container.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory, EmbeddedViewContentComponent } from "survey-angular-ui";
import { ComponentContainerModel } from "survey-creator-core";

@Component({
  selector: "svc-component-container",
  templateUrl: "./component-container.component.html",
  styles: [":host { display: none; }"]
})
export class ComponentContainerComponent extends EmbeddedViewContentComponent {
  @Input() model!: ComponentContainerModel;
}
AngularComponentFactory.Instance.registerComponent("svc-component-container", ComponentContainerComponent);
<ng-template #template>
  <ng-template #elementsTemplate>
    <ng-template *ngFor="let element of model.elements"
      [component]="{ name: element.componentName, data: element.componentData }"></ng-template>
  </ng-template>

  <ng-container *ngIf="model.wrapped; else unwrappedTemplate">
    <div [class]="model.cssClass">
      <sv-scroll *ngIf="model.scrollable; else wrappedPlainTemplate">
        <ng-container *ngTemplateOutlet="elementsTemplate"></ng-container>
      </sv-scroll>
      <ng-template #wrappedPlainTemplate>
        <ng-container *ngTemplateOutlet="elementsTemplate"></ng-container>
      </ng-template>
    </div>
  </ng-container>

  <ng-template #unwrappedTemplate>
    <sv-scroll *ngIf="model.scrollable; else unwrappedPlainTemplate">
      <ng-container *ngTemplateOutlet="elementsTemplate"></ng-container>
    </sv-scroll>
    <ng-template #unwrappedPlainTemplate>
      <ng-container *ngTemplateOutlet="elementsTemplate"></ng-container>
    </ng-template>
  </ng-template>
</ng-template>

// packages/survey-creator-react/src/components/ComponentContainer.tsx
import * as React from "react";
import { ComponentContainerModel } from "survey-creator-core";
import { ReactElementFactory, Scroll } from "survey-react-ui";

interface IComponentContainerProps {
  model: ComponentContainerModel;
}

export class ComponentContainer extends React.Component<IComponentContainerProps, any> {
  constructor(props: IComponentContainerProps) {
    super(props);
  }
  render(): React.JSX.Element {
    const children = this.props.model.elements.map((element, index) => {
      return ReactElementFactory.Instance.createElement(element.componentName, { ...element.componentData, key: index });
    });
    const inner = this.props.model.scrollable ? <Scroll> {children} </Scroll> : children;
    return (
      this.props.model.wrapped ? <div className={this.props.model.cssClass} > {inner} </div> : <>{inner}</>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-component-container",
  (props: IComponentContainerProps) => {
    return React.createElement(ComponentContainer, props);
  }
);
