// packages/survey-creator-vue/src/components/ComponentContainer.vue
<template>

  <div class="svc-component-container" >
    <SvComponent :is="element.componentName" :model="element.componentData" v-for="(element, index) in props.model.elements" :key="index" />
  </div>
</template>

<script lang="ts" setup>
import { SvComponent } from "survey-vue3-ui";
import type { ComponentContainerModel } from 'survey-creator-core';

const props = defineProps<{
  model: ComponentContainerModel;
}>();
</script>

// packages/survey-creator-react/src/components/ComponentContainer.tsx
import * as React from "react";
import { ComponentContainerModel } from "survey-creator-core";
import { ReactElementFactory } from "survey-react-ui";

interface IComponentContainerProps {
  model: ComponentContainerModel;
}

export class ComponentContainer extends React.Component<IComponentContainerProps, any> {
  constructor(props: IComponentContainerProps) {
    super(props);
  }
  render(): React.JSX.Element {
    return (
      <div className="svc-component-container" >
        {this.props.model.elements.map((element, index) => {
          return ReactElementFactory.Instance.createElement(element.componentName, { ...element.componentData, key: index });
        })}
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-component-container",
  (props: IComponentContainerProps) => {
    return React.createElement(ComponentContainer, props);
  }
);
