// packages/survey-creator-angular/src/question.component.ts
import { ChangeDetectorRef, Component, Input, ViewContainerRef } from "@angular/core";
import { AngularComponentFactory, BaseAngular, EmbeddedViewContentComponent } from "survey-angular-ui";
import { PageModel, Question, SurveyModel } from "survey-core";
import { CreatorBase, QuestionAdornerViewModel } from "survey-creator-core";
import { CreatorModelComponent } from "./creator-model.component";

@Component({
  selector: "svc-question",
  templateUrl: "./question.component.html",
  styles: [":host { display: none; }"]
})
export class QuestionDesignerComponent extends CreatorModelComponent<QuestionAdornerViewModel> {
  @Input() model!: any;
  @Input() componentData!: CreatorBase;
  public adorner!: QuestionAdornerViewModel;
  private get creator() {
    return this.componentData;
  }
  protected createModel(): void {
    if (this.model) {
      this.adorner = new QuestionAdornerViewModel(this.creator, this.model, <any>null);
    }
  }
  protected getPropertiesToTrack(): string[] {
    return ["model", "componentData"];
  }
  protected getModel(): QuestionAdornerViewModel {
    return this.adorner;
  }
  public selectQuestionType(event: any) {
    event.stopPropagation();
    this.adorner.questionTypeSelectorModel.action(this.adorner.questionTypeSelectorModel, event);
  }
}

AngularComponentFactory.Instance.registerComponent("svc-question", QuestionDesignerComponent);


<ng-template #template>
  <div *ngIf="model && adorner" class="svc-question__adorner" [class]="adorner.rootCss()"
    (mouseover)="adorner.hover($event, $event.target)" (mouseleave)="adorner.hover($event, $event.target)"
    [attr.data-sv-drop-target-survey-element]="adorner.element.name || null"
    data-bind="css: rootCss(), attr: { 'data-sv-drop-target-survey-element': element.name || null }, event: { mouseover: function(m, e) { hover(e, $element); }, mouseleave: function(m, e) { hover(e, $element); } }">

    <div *ngIf="adorner.element.isInteractiveDesignElement" class="svc-question__content" [class]="adorner.css()"
      [key2click] (click)="adorner.select(adorner, $event)"
      data-bind="click: koSelect, key2click, clickBubble: false, css: css()">
      <div *ngIf="adorner.allowDragging" class="svc-question__drag-area"
        data-bind="event: {pointerdown: (model, event)=>{onPointerDown(event)}}">
        <svg class="svc-question__drag-element" [iconName]="'icon-drag-area-indicator_24x16'" [size]="24"
          sv-ng-svg-icon></svg>
      </div>

      <ng-template [component]="{ name: 'sv-template-renderer', data: { model: model } }"></ng-template>

      <div *ngIf="adorner.isEmptyElement" class="svc-panel__placeholder_frame">
        <div class="svc-panel__placeholder" data-bind="text: placeholderText"></div>
        <div *ngIf="adorner.element.isPanel && adorner.showAddQuestionButton"
          class="svc-panel__add-new-question svc-action-button" [key2click] (click)="adorner.addNewQuestion()"
          data-bind="click: addNewQuestion, key2click, clickBubble: false">
          <span class="svc-text svc-text--normal svc-text--bold" data-bind="text: $data.addNewQuestionText">
            {{ adorner.addNewQuestionText }}
          </span>
        </div>
      </div>

      <!-- ko if: adornerComponent -->
      <!-- ko component: { name: adornerComponent, params: { model: $data } } -->
      <!-- /ko -->
      <!-- /ko -->

      <div *ngIf="!adorner.isEmptyElement && model.isPanel && adorner.showAddQuestionButton"
        class="svc-panel__add-new-question-container">
        <div class="svc-panel__add-new-question svc-action-button" [key2click] (click)="adorner.addNewQuestion()"
          data-bind="click: addNewQuestion, key2click, clickBubble: false">
          <span class="svc-text svc-text--normal svc-text--bold" data-bind="text: $data.addNewQuestionText">
            {{ adorner.addNewQuestionText }}
          </span>
        </div>
        <!-- ko with: questionTypeSelectorModel -->
        <button type="button" [attr.title]="adorner.addNewQuestionText" [key2click]
          (click)="adorner.questionTypeSelectorModel.action(adorner.questionTypeSelectorModel, $event)"
          data-bind="click: action, key2click, clickBubble: false, attr: { title: $data.addNewQuestionText }"
          class="svc-panel__question-type-selector">
          <svg class="svc-panel__question-type-selector-icon" [iconName]="adorner.questionTypeSelectorModel.iconName"
            [size]="24" sv-ng-svg-icon></svg>
          <!-- <sv-popup params="model: popupModel"></sv-popup> -->
        </button>
        <!-- /ko -->
      </div>

      <div class="svc-question__content-actions">
        <sv-action-bar [model]="adorner.actionContainer"></sv-action-bar>
      </div>
    </div>

    <ng-container *ngIf="!adorner.element.isInteractiveDesignElement">
      <ng-template [component]="{ name: 'sv-template-renderer', data: { model: model } }"></ng-template>

      <div *ngIf="adorner.isEmptyElement" class="svc-panel__placeholder_frame">
        <div class="svc-panel__placeholder" data-bind="text: placeholderText"></div>
        <div *ngIf="adorner.showAddQuestionButton" class="svc-panel__add-new-question svc-action-button" [key2click]
          (click)="adorner.addNewQuestion()" data-bind="click: addNewQuestion, key2click, clickBubble: false">
          <span class="svc-text svc-text--normal svc-text--bold" data-bind="text: $data.addNewQuestionText">
            {{ adorner.addNewQuestionText }}
          </span>
        </div>
      </div>

      <div *ngIf="!adorner.isEmptyElement" class="svc-panel__add-new-question-container">
        <div class="svc-panel__add-new-question svc-action-button" [key2click] (click)="adorner.addNewQuestion()"
          data-bind="click: addNewQuestion, key2click, clickBubble: false">
          <span class="svc-text svc-text--normal svc-text--bold" data-bind="text: $data.addNewQuestionText">
            {{ adorner.addNewQuestionText }}
          </span>
        </div>
        <!-- ko with: questionTypeSelectorModel -->
        <button type="button" [key2click]
          (click)="adorner.questionTypeSelectorModel.action(adorner.questionTypeSelectorModel, $event)"
          data-bind="click: action, key2click, clickBubble: false, attr: { title: $data.addNewQuestionText }"
          class="svc-panel__question-type-selector">
          <svg class="svc-panel__question-type-selector-icon" [iconName]="adorner.questionTypeSelectorModel.iconName"
            [size]="24" sv-ng-svg-icon></svg>
          <!-- <sv-popup params="model: popupModel"></sv-popup> -->
        </button>
        <!-- /ko -->
      </div>

    </ng-container>
  </div>
</ng-template>

// packages/survey-creator-react/src/components/Question.tsx
import { QuestionAdornerViewModel, toggleHovered } from "@survey/creator";
import React from "react";
import { ReactDragEvent, ReactMouseEvent } from "../events";
import { Base, Question } from "survey-core";
import {
  SurveyActionBar,
  ReactElementFactory,
  SurveyElementBase,
  SurveyQuestion,
  attachKey2click,
  SvgIcon,
  Popup
} from "survey-react-ui";

export interface QuestionAdornerComponentProps {
  element: JSX.Element;
  question: Question;
  componentData: any;
}

export class QuestionAdornerComponent extends SurveyElementBase<
  QuestionAdornerComponentProps,
  any
> {
  private modelValue: QuestionAdornerViewModel;
  protected rootRef: React.RefObject<HTMLDivElement>;

  constructor(props: QuestionAdornerComponentProps) {
    super(props);
    this.modelValue = this.createQuestionViewModel();
  }
  protected createQuestionViewModel(): QuestionAdornerViewModel {
    return new QuestionAdornerViewModel(
      this.props.componentData,
      this.props.question,
      null
    );
  }
  public get model(): QuestionAdornerViewModel {
    return this.modelValue;
  }
  protected getStateElement(): Base {
    return this.model;
  }
  protected canRender(): boolean {
    return super.canRender() && !this.model.isDragged;
  }

  renderElement(): JSX.Element {
    const allowInteractions = this.model.surveyElement
      .isInteractiveDesignElement;
    const content = this.renderContent(allowInteractions);
    return (
      <React.Fragment>
        <div
          data-sv-drop-target-survey-element={this.model.surveyElement.name}
          ref={this.rootRef}
          className={"svc-question__adorner" + this.model.rootCss()}
          onMouseOut={(e) =>
            allowInteractions && toggleHovered(e.nativeEvent, e.currentTarget)
          }
          onMouseOver={(e) =>
            allowInteractions && toggleHovered(e.nativeEvent, e.currentTarget)
          }
        >
          {content}
        </div>
      </React.Fragment>
    );
  }
  protected renderContent(allowInteractions: boolean): JSX.Element {
    var content = this.renderElementContent();
    if (!allowInteractions) return content;
    return attachKey2click(
      <div
        className={"svc-question__content " + this.model.css()}
        onClick={(e) => this.model.select(this.model, new ReactMouseEvent(e))}
      >
        {this.renderContentOnTop()}
        {this.renderDragAria()}
        {content}
        {this.model.surveyElement.isPanel && this.model.allowEdit ? attachKey2click(<div
          className="svc-panel__add-new-question"
          onClick={(e) => {
            e.stopPropagation();
            this.model.addNewQuestion();
          }}
        >
          <span className="svc-text svc-text--normal svc-text--bold">
            {this.model.addNewQuestionText}
          </span>

          {attachKey2click(<button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              this.model.questionTypeSelectorModel.action();
            }}
            className="svc-panel__question-type-selector"
            title={this.model.addNewQuestionText}
          >
            <span className="svc-panel__question-type-selector-icon">
              <SvgIcon
                iconName={this.model.questionTypeSelectorModel.iconName}
                size={24}
              ></SvgIcon>
            </span>
            <Popup model={this.model.questionTypeSelectorModel.popupModel}></Popup>
          </button>)}
        </div>) : null}

        <div className="svc-question__content-actions">
          <SurveyActionBar model={this.model.actionContainer}></SurveyActionBar>
        </div>
      </div>
    );
  }
  protected renderElementContent(): JSX.Element {
    return (
      <>
        {this.props.element}
        {this.renderElementPlaceholder()}
      </>
    );
  }
  protected renderContentOnTop(): JSX.Element {
    return null;
  }
  protected renderDragAria(): JSX.Element {
    if (!this.model.allowDragging) return null;
    return (
      <div className={"svc-question__drag-area"}
        onPointerDown={(event: any) =>
          this.model.startDragSurveyElement(event)
        }
      >
        <div
          className={"svc-question__drag-element"}
        ></div>
      </div>
    );
  }
  renderElementPlaceholder(): JSX.Element {
    if (!this.model.isEmptyElement) {
      return null;
    }
    return (
      <div className="svc-panel__placeholder_frame">
        <div className="svc-panel__placeholder">
          {this.model.placeholderText}
        </div>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "svc-question",
  (props: QuestionAdornerComponentProps) => {
    return React.createElement(QuestionAdornerComponent, props);
  }
);

ReactElementFactory.Instance.registerElement(
  "svc-panel",
  (props: QuestionAdornerComponentProps) => {
    return React.createElement(QuestionAdornerComponent, props);
  }
);
