// packages/survey-creator-angular/src/adorners/question-image.component.ts
import { AfterViewInit, Component, ElementRef, Input, ViewChild } from "@angular/core";
import { AngularComponentFactory, EmbeddedViewContentComponent } from "survey-angular-ui";
import { QuestionImageAdornerViewModel } from "survey-creator-core";
import { QuestionDesignerComponent } from "../question.component";

@Component({
  selector: "svc-image-question",
  templateUrl: "../question.component.html",
  styles: [":host { display: none; }"]
})
export class QuestionImageDesignerComponent extends QuestionDesignerComponent implements AfterViewInit {
  @ViewChild("container", { read: ElementRef }) container!: ElementRef<HTMLDivElement>

  protected override createModel(): void {
    if (this.componentData) {
      this.adorner = new QuestionImageAdornerViewModel(this.creator, this.model, <any>null, this.viewContainerRef?.element.nativeElement.nextSibling);
    }
  }
  public override adornerComponent = "svc-image-question-adorner";
  ngAfterViewInit(): void {
    (<QuestionImageAdornerViewModel>this.adorner).questionRoot = this.container.nativeElement;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-image-question", QuestionImageDesignerComponent);

@Component({
  selector: "svc-image-question-adorner",
  templateUrl: "./question-image.component.html",
  styles: [":host { display: none; }"]
})
export class QuestionImageAdornerDesignerComponent extends EmbeddedViewContentComponent {
  @Input() adorner!: QuestionImageAdornerViewModel;
  @Input() question!: any;
}

AngularComponentFactory.Instance.registerComponent("svc-image-question-adorner", QuestionImageAdornerDesignerComponent);


<ng-template #template>
  <div class="svc-image-question-controls">
    <ng-container *ngIf="adorner.allowEdit">
      <input type="file" aria-hidden="true" tabindex="-1" accept="image/*" class="svc-choose-file-input" />
      <span class="svc-image-question-controls__button" [key2click] [attr.title]="undefined" [attr.aria-label]="undefined">
        <svg  [iconName]="'icon-file'" [size]="24" (click)="adorner.chooseFile(adorner)" sv-ng-svg-icon></svg>
      </span>
    </ng-container>
  </div>
</ng-template>

// packages/survey-creator-react/src/components/QuestionImage.tsx
import {
  QuestionImageAdornerViewModel,
  QuestionAdornerViewModel
} from "@survey/creator";
import React from "react";
import { attachKey2click, ReactElementFactory, SvgIcon } from "survey-react-ui";
import {
  QuestionAdornerComponent,
  QuestionAdornerComponentProps
} from "./Question";

export class QuestionImageAdornerComponent extends QuestionAdornerComponent {
  constructor(props: QuestionAdornerComponentProps) {
    super(props);
    this.rootRef = React.createRef();
  }
  protected createQuestionViewModel(): QuestionAdornerViewModel {
    return new QuestionImageAdornerViewModel(
      this.props.componentData,
      this.props.question as any,
      null,
      null
    );
  }
  public get imageModel(): QuestionImageAdornerViewModel {
    return this.model as QuestionImageAdornerViewModel;
  }
  componentDidMount() {
    super.componentDidMount();
    this.imageModel.questionRoot = this.rootRef.current;
  }
  protected renderContentOnTop(): JSX.Element {
    return (
      <input
        type="file"
        aria-hidden="true"
        tabIndex={-1}
        accept="image/*"
        className="svc-choose-file-input"
        style={{
          position: "absolute",
          opacity: 0,
          width: "1px",
          height: "1px",
          overflow: "hidden"
        }}
      />
    );
  }

  renderElementPlaceholder(): JSX.Element {
    return (
      <div className="svc-image-question-controls">
        {this.model.allowEdit ? attachKey2click(<span
          className="svc-image-question-controls__button svc-image-question-controls__choose-file"
          onClick={() => this.imageModel.chooseFile(this.imageModel)}
        >
          <SvgIcon size={24} iconName={"icon-file"}></SvgIcon>
        </span>) : null}
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "svc-image-question",
  (props: QuestionAdornerComponentProps) => {
    return React.createElement(QuestionImageAdornerComponent, props);
  }
);
