// packages/survey-creator-angular/src/adorners/question-rating.component.ts
import { AfterViewInit, Component, ElementRef, Input, ViewChild } from "@angular/core";
import { CreatorModelComponent } from "../creator-model.component";
import { AngularComponentFactory, EmbeddedViewContentComponent } from "survey-angular-ui";
import { CreatorBase, QuestionRatingAdornerViewModel } from "survey-creator-core";
import { QuestionDesignerComponent } from "../question.component";
import { QuestionRatingModel } from "survey-core";

@Component({
  selector: "svc-rating-question",
  templateUrl: "../question.component.html",
  styles: [":host { display: none; }"]
})
export class QuestionRatingDesignerComponent extends QuestionDesignerComponent {
  public override adornerComponent = "";
}

AngularComponentFactory.Instance.registerComponent("svc-rating-question", QuestionRatingDesignerComponent);

@Component({
  selector: "svc-rating-question-content",
  templateUrl: "./question-rating.component.html",
  styles: [":host { display: none; }"]
})
export class QuestionRatingAdornerDesignerComponent extends CreatorModelComponent<QuestionRatingAdornerViewModel> {
  @Input() componentName!: string;
  @Input() componentData!: any;
  public adorner!: QuestionRatingAdornerViewModel;

  protected createModel(): void {
    if (this.componentData) {
      this.adorner = new QuestionRatingAdornerViewModel(this.componentData.data, this.componentData.model, <any>null);
    }
  }
  protected getPropertiesToTrack(): string[] {
    return ["model", "creator"];
  }
  protected getModel(): QuestionRatingAdornerViewModel {
    return this.adorner;
  }
}

AngularComponentFactory.Instance.registerComponent("svc-rating-question-content", QuestionRatingAdornerDesignerComponent);


<ng-template #template>
  <div class="svc-rating-question-content">
    <div class="svc-rating-question-controls svc-item-value-controls">
      <svg *ngIf="adorner.allowRemove" [iconName]="'icon-remove_16x16'" [size]="16" [key2click] (click)="adorner.removeItem(adorner)"
      class="svc-item-value-controls__button svc-item-value-controls__remove" [attr.title]="adorner.removeTooltip" [attr.aria-label]="adorner.removeTooltip" sv-ng-svg-icon></svg>
      <svg *ngIf="adorner.allowAdd" [iconName]="'icon-add_16x16'" [size]="16" [key2click] (click)="adorner.addItem(adorner)"
      class="svc-item-value-controls__button svc-item-value-controls__add" [attr.title]="adorner.addTooltip" [attr.aria-label]="adorner.addTooltip"sv-ng-svg-icon></svg>
    </div>
    <ng-template [component]="{ name: componentName, data: componentData }"></ng-template>
  </div>
</ng-template>

// packages/survey-creator-react/src/components/QuestionRating.tsx
import {
  QuestionAdornerViewModel,
  QuestionRatingAdornerViewModel
} from "@survey/creator";
import React from "react";
import {
  QuestionAdornerComponent,
  QuestionAdornerComponentProps
} from "./Question";
import { attachKey2click, ReactElementFactory, SvgIcon } from "survey-react-ui";

export class QuestionRatingAdornerComponent extends QuestionAdornerComponent {
  protected createQuestionViewModel(): QuestionAdornerViewModel {
    return new QuestionRatingAdornerViewModel(
      this.props.componentData,
      this.props.question as any,
      null
    );
  }
  public get ratingModel(): QuestionRatingAdornerViewModel {
    return this.model as QuestionRatingAdornerViewModel;
  }

  renderElementPlaceholder(): JSX.Element {
    const question = this.props.question;
    const model = this.ratingModel;
    return (
      <div className="svc-rating-question-controls svc-item-value-controls">
        {model.allowRemove ? attachKey2click(<span
          className="svc-item-value-controls__button svc-item-value-controls__remove"
          onClick={() => model.removeItem(model)}
        >
          <SvgIcon size={16} iconName={"icon-remove_16x16"}></SvgIcon>
        </span>) : null}
        {model.allowAdd ? attachKey2click(<span
          className="svc-item-value-controls__button svc-item-value-controls__add"
          onClick={() => model.addItem(model)}
        >
          <SvgIcon size={16} iconName={"icon-add_16x16"}></SvgIcon>
        </span>) : null}
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "svc-rating-question",
  (props: QuestionAdornerComponentProps) => {
    return React.createElement(QuestionRatingAdornerComponent, props);
  }
);
