// packages/survey-creator-vue/src/StringEditor.vue
<template>
  <span :class="className">
    <span class="svc-string-editor__content">
      <div class="svc-string-editor__border">
        <svg
          class="svc-string-editor__button svc-string-editor__button--edit"
          sv-ng-svg-icon
          @click="edit"
          :iconName="'icon-edit'"
          :size="16"
        ></svg>
      </div>
      <span class="svc-string-editor__input">
        <span
          role="textbox"
          v-if="!locString.hasHtml"
          class="sv-string-editor"
          spellcheck="false"
          @focus="onFocus"
          @paste="onPaste"
          @blur="onBlur"
          @input="baseModel?.onInput"
          @keydown="baseModel?.onKeyDown"
          @keyup="baseModel?.onKeyUp"
          @mouseup="baseModel?.onMouseUp"
          @click="edit"
          :textContent="editValue"
          :aria-placeholder="placeholder"
          :contenteditable="contentEditable"
          ref="root"
        ></span>
        <span
          role="textbox"
          v-if="locString.hasHtml"
          class="sv-string-editor sv-string-editor--html"
          spellcheck="false"
          @focus="onFocus"
          @blur="onBlur"
          @keydown="baseModel?.onKeyDown"
          @keyup="baseModel?.onKeyUp"
          @mouseup="baseModel?.onMouseUp"
          @click="edit"
          :aria-placeholder="placeholder"
          :contenteditable="contentEditable"
          :innerHtml="editValue"
          ref="root"
        ></span>
        <sv-character-counter
          v-if="showCharacterCounter"
          :counter="characterCounter"
          :remainingCharacterCounter="getCharacterCounterClass"
        ></sv-character-counter>
      </span>
    </span>
    <span v-if="errorText" class="svc-string-editor__error">{{
      errorText
    }}</span>
  </span>
</template>
<script setup lang="ts">
import type { LocalizableString } from "survey-core";
import {
  StringEditorViewModelBase,
  type CreatorBase,
} from "survey-creator-core";
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import { useCreatorModel } from "./creator-model";

const props = defineProps<{ locString: any }>();
const locString = computed<LocalizableString>(() => {
  return props.locString.locStr;
});
const creator = computed<CreatorBase>(() => {
  return props.locString.creator;
});
const root = ref<HTMLElement>();

const renderedHtml = ref<string>();

const baseModel = useCreatorModel(
  () => {
    const baseModel = new StringEditorViewModelBase(
      locString.value,
      creator.value
    );
    baseModel.setLocString(locString.value);
    baseModel.blurEditor = () => {
      if (root.value) {
        root.value.blur();
        root.value.spellcheck = false;
      }
      baseModel.getEditorElement = () => root.value as HTMLElement;
      setTimeout(() => baseModel.afterRender());
    };
    return baseModel;
  },
  [() => creator.value, () => locString.value],
  (baseModel) => {
    if (baseModel) {
      baseModel.blurEditor = undefined as any;
      baseModel.getEditorElement = undefined as any;
      baseModel.dispose();
    }
  }
);

const editValue = computed<string>(
  () =>
    (baseModel.value?.focused &&
      baseModel.value.editAsText &&
      locString.value.text) ||
    (renderedHtml.value as string)
);
const errorText = computed(() => baseModel.value?.errorText);
const className = computed(() => {
  return baseModel.value?.className(locString.value.renderedHtml);
});
const placeholder = computed(() => baseModel.value?.placeholder);
const contentEditable = computed(() => baseModel.value?.contentEditable);
const characterCounter = computed(() => baseModel.value?.characterCounter);
const showCharacterCounter = computed(
  () => baseModel.value?.showCharacterCounter
);
const getCharacterCounterClass = computed(
  () => baseModel.value?.getCharacterCounterClass
);

const onBlur = (event: any) => {
  if (root.value) root.value.spellcheck = false;
  (locString.value as any).__isEditing = false;
  baseModel.value?.onBlur(event);
  return baseModel.value?.errorText;
};

const onFocus = (event: any): void => {
  baseModel.value?.onFocus(event);
};
const onPaste = (event: any): void => {
  baseModel.value?.onPaste(event);
};
const edit = (event: any): void => {
  root.value?.focus();
  (locString.value as any).__isEditing = true;
  baseModel.value?.onClick(event);
};

const onChangeHandler = (): void => {
  renderedHtml.value = locString.value.renderedHtml;
};
const stopWatch = watch(
  () => locString.value,
  (newValue, oldValue) => {
    if (oldValue) {
      newValue.onStringChanged.remove(onChangeHandler);
    }
    if (newValue) {
      newValue.onStringChanged.add(onChangeHandler);
      onChangeHandler();
    }
  },
  {
    immediate: true,
  }
);
onMounted(() => {
  if ((locString.value as any).__isEditing) {
    root.value?.focus();
  }
});
onUnmounted(() => {
  stopWatch();
  locString.value.onStringChanged.remove(onChangeHandler);
});
</script>

// packages/survey-creator-react/src/components/StringEditor.tsx
import React from "react";
import { LocalizableString, Serializer, JsonObjectProperty, Base } from "survey-core";
import { ReactElementFactory, SurveyElementBase, SvgIcon } from "survey-react-ui";
import { CreatorBase, StringEditorViewModelBase } from "@survey/creator";

export class SurveyLocStringEditor extends SurveyElementBase<any, any> {
  private baseModel: StringEditorViewModelBase;
  private svStringEditorRef: React.RefObject<HTMLDivElement>;
  private blurredByEscape: boolean = false;
  constructor(props: any) {
    super(props);
    this.state = { changed: 0 };
    this.baseModel = new StringEditorViewModelBase(this.locString, this.creator);
    this.svStringEditorRef = React.createRef();
    this.baseModel.blurEditor = () => {
      this.svStringEditorRef.current.blur();
      this.svStringEditorRef.current.spellcheck = false;
    };
  }
  private get locString(): LocalizableString {
    return this.props.locStr.locStr;
  }
  private get creator(): CreatorBase {
    return this.props.locStr.creator;
  }
  private get style(): any {
    return this.props.style;
  }

  protected getStateElement(): Base {
    return this.baseModel;
  }

  public get errorText(): string {
    return this.baseModel.errorText;
  }

  public componentDidMount() {
    if (!this.locString) return;
    const self: SurveyLocStringEditor = this;
    this.locString.onChanged = function () {
      self.setState({ changed: self.state.changed + 1 });
    };
    if (this.locString["__isEditing"]) {
      this.svStringEditorRef.current.focus();
      // document.execCommand('selectAll', false, null);
    }
  }
  public componentWillUnmount() {
    if (!this.locString) return;
    this.locString.onChanged = function () { };
  }
  private get placeholder(): string {
    return this.baseModel.placeholder;
  }
  private get contentEditable(): boolean {
    return this.baseModel.contentEditable;
  }
  private onBlur = (event: any) => {
    this.svStringEditorRef.current.spellcheck = false;
    this.locString["__isEditing"] = false;
    this.justFocused = false;
    this.baseModel.onInput(event.nativeEvent);
    return this.baseModel.errorText;
  };
  private justFocused = false;
  private onFocus = (event: any) => {
    this.baseModel.onFocus(event.nativeEvent);
    this.justFocused = true;
  };
  private onKeyDown = (event: React.KeyboardEvent<HTMLSpanElement>) => {
    return this.baseModel.onKeyDown(event.nativeEvent);
  };
  private onMouseUp = (event: React.MouseEvent<HTMLSpanElement>): boolean => {
    if(this.justFocused) {
      this.justFocused = false;
      event.nativeEvent.preventDefault();
      return false;
    }
    return undefined;
  };
  private done = (event: any) => {
    this.baseModel.done(event);
    this.locString["__isEditing"] = false;
  };
  private edit = (event: any) => {
    this.svStringEditorRef.current.focus();
    // document.execCommand('selectAll', false, null);
    this.locString["__isEditing"] = true;
    this.baseModel.onClick(event);
  };
  private get className() {
    return this.baseModel.className(this.locString.renderedHtml);
  }
  public render(): JSX.Element {
    if (!this.locString) {
      return null;
    }
    else {
      this.baseModel.setLocString(this.locString);
    }
    let control = null;
    if (this.locString.hasHtml) {
      const htmlValue = { __html: this.baseModel.focused && this.locString.text || this.locString.renderedHtml };
      control = (
        <span
          ref={this.svStringEditorRef}
          className="sv-string-editor"
          contentEditable={this.contentEditable}
          spellCheck={false}
          aria-placeholder={this.placeholder}
          suppressContentEditableWarning={true}
          // style={this.style}
          dangerouslySetInnerHTML={htmlValue}
          onBlur={this.onBlur}
          onFocus={this.onFocus}
          onKeyDown={this.onKeyDown}
          onMouseUp={this.onMouseUp}
          onClick={this.edit}
        />
      );
    } else {
      control = (
        <span
          ref={this.svStringEditorRef}
          className="sv-string-editor"
          contentEditable={this.contentEditable}
          spellCheck={false}
          aria-placeholder={this.placeholder}
          suppressContentEditableWarning={true}
          // style={this.style}
          onBlur={this.onBlur}
          onFocus={this.onFocus}
          onKeyDown={this.onKeyDown}
          onMouseUp={this.onMouseUp}
          onClick={this.edit}
        >
          {this.locString.renderedHtml}
        </span>
      );
    }
    return (
      <span className={this.className}>
        <span className="svc-string-editor__content">
          <div className="svc-string-editor__border"
            onClick={this.edit}
          >
            <SvgIcon
              className="svc-string-editor__button svc-string-editor__button--edit"
              size={16}
              iconName={"icon-edit"}
            ></SvgIcon>

          </div>
          {control}
          <div className="svc-string-editor__controls"
            onClick={this.edit}>
          </div>
        </span>
        {this.errorText ? <span className="svc-string-editor__error">{this.errorText}</span> : ""}
      </span>
    );
  }
}

export const editableStringRendererName = "svc-string-editor";
ReactElementFactory.Instance.registerElement(
  editableStringRendererName,
  (props) => {
    return React.createElement(SurveyLocStringEditor, props);
  }
);
