// packages/survey-creator-angular/src/tabs/json/json-editor-textarea.component.ts
import { TabJsonEditorTextareaPlugin, TextareaJsonEditorModel } from "survey-creator-core";
import { Component, Input, OnInit } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-tab-json-editor-textarea",
  templateUrl: "./json-editor-textarea.component.html",
  styles: [":host { display: none; }"]
})
export class TextareaJsonEditorComponent extends BaseAngular<TextareaJsonEditorModel> implements OnInit {
  @Input() model!: TextareaJsonEditorModel;
  protected getModel(): TextareaJsonEditorModel {
    return this.model;
  }

  public onChange(event: any): void {
    this.model.text = event.target.value;
  }

  public override ngOnInit(): void {
    this.model.canShowErrors = false;
    super.ngOnInit();
  }
}
AngularComponentFactory.Instance.registerComponent("svc-tab-json-editor-textarea", TextareaJsonEditorComponent);
<ng-template #template>
  <div class="svc-creator-tab__content">
    <div class="svc-json-editor-tab__content">
      <textarea class="svc-json-editor-tab__content-area"
        [attr.aria-label]="model.ariaLabel"
        [disabled]="model.readOnly"
        [value]="model.text"
        (change)="onChange($event)"
        (keydown)="model.checkKey(model, $event)">
      </textarea>
      <button type="button" *ngIf="model.userFriendlyErrors.length !== 0" class="svc-json-editor-tab__errros_button"
        (click)="model.toggleErrors">{{model.errorButtonText}}</button>
      <ng-container *ngIf="model.canShowErrors">
        <div class="svc-json-editor-tab__content-errors" *ngFor="let error of model.userFriendlyErrors">
          <span><b>Error:</b></span>
          <span>{{error}}</span>
        </div>
      </ng-container>
    </div>
  </div>
</ng-template>

// packages/survey-creator-react/src/components/tabs/JsonEditorTextarea.tsx
import React, { ChangeEvent } from "react";
import { Base } from "survey-core";
import { ReactElementFactory, SurveyElementBase } from "survey-react-ui";
import { TextareaJsonEditorModel } from "@survey/creator";

interface ITabJsonEditorTextareaComponentProps {
  data: TextareaJsonEditorModel;
}

export class TabJsonEditorTextareaComponent extends SurveyElementBase<
  ITabJsonEditorTextareaComponentProps,
  any
> {
  constructor(props) {
    super(props);
    this.model.canShowErrors = false;
  }
  protected getStateElement(): Base {
    return this.model;
  }
  private get model(): TextareaJsonEditorModel {
    return this.props.data;
  }
  renderElement(): JSX.Element {
    const errors: JSX.Element[] = [];
    var key = 1;
    const userFriendlyErrors: any[] = this.model.userFriendlyErrors;
    for (let i: number = 0; i < userFriendlyErrors.length; i++) {
      errors.push(<span key={key}><b>Error: </b></span>);
      key++;
      errors.push(<span key={key}>{userFriendlyErrors[i]}</span>);
      key++;
    }
    return (
      <div className="svc-creator-tab__content">
        <div className="svc-json-editor-tab__content">
          <textarea
            className="svc-json-editor-tab__content-area"
            value={this.model.text}
            onChange={(e: ChangeEvent<HTMLTextAreaElement>) =>
              (this.model.text = e.target.value)
            }
            disabled={this.model.readOnly}
            aria-label={this.model.ariaLabel}
          ></textarea>
          { errors.length > 0 &&
              <button className="svc-json-editor-tab__errros_button" onClick={() => this.model.toggleErrors()}>
                {this.model.errorButtonText}
              </button>
          }
          { this.model.canShowErrors && 
            <div className="svc-json-editor-tab__content-errors">{errors}</div>
          }
        </div>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "svc-tab-json-editor-textarea",
  (props: ITabJsonEditorTextareaComponentProps) => {
    return React.createElement(TabJsonEditorTextareaComponent, props);
  }
);
