// packages/survey-creator-angular/src/tabs/json/json-editor-ace.component.ts

import { AceJsonEditorModel, TabJsonEditorAcePlugin } from "survey-creator-core";
import { AfterViewInit, Component, ElementRef, Input, OnInit, ViewChild } from "@angular/core";
import { AngularComponentFactory, BaseAngular } from "survey-angular-ui";

@Component({
  selector: "svc-tab-json-editor-ace",
  templateUrl: "./json-editor-ace.component.html",
  styles: [":host { display: none; }"]
})
export class AceJsonEditorComponent extends BaseAngular<AceJsonEditorModel> implements AfterViewInit {
  @Input() model!: AceJsonEditorModel;
  @ViewChild("inputEl") inputEl!: ElementRef<HTMLElement>;
  protected getModel(): AceJsonEditorModel {
    return this.model;
  }

  public ngAfterViewInit(): void {
    //todo fix ts 
    this.model.init((<any>window).ace.edit(
      this.inputEl.nativeElement
    ));
  }
}
AngularComponentFactory.Instance.registerComponent("svc-tab-json-editor-ace", AceJsonEditorComponent);
<ng-template #template>
    <div class="svc-creator-tab__content">
        <div class="svc-json-editor-tab__content">
            <div class="svc-json-editor-tab__ace-editor" #inputEl></div>
            <div className="svc-json-editor-tab__errros_list" [visible]="model.hasErrors">
                <sv-ng-list [model]="model.errorList"></sv-ng-list>
            </div>
        </div>
    </div>
</ng-template>

// packages/survey-creator-react/src/components/tabs/JsonEditorAce.tsx
import React from "react";
import { Base } from "survey-core";
import { ReactElementFactory, SurveyElementBase } from "survey-react-ui";
import { TabJsonEditorAcePlugin, AceJsonEditorModel } from "@survey/creator";

interface ITabJsonEditorAceComponentProps {
  data: TabJsonEditorAcePlugin;
}

export class TabJsonEditorAceComponent extends SurveyElementBase<ITabJsonEditorAceComponentProps, any> {
  private model: AceJsonEditorModel;
  private aceEditorrRef: React.RefObject<HTMLDivElement>;
  constructor(props: ITabJsonEditorAceComponentProps) {
    super(props);
    this.model = props.data.model;
    this.aceEditorrRef = React.createRef();
  }
  protected getStateElement(): Base {
    return this.model;
  }
  componentDidMount() {
    this.model.init(ace.edit(this.aceEditorrRef.current as HTMLElement));
  }
  render(): JSX.Element {
    return (
      <div className="svc-creator-tab__content">
        <div className="svc-json-editor-tab__content">
          <div
            className="svc-json-editor-tab__ace-editor"
            ref={this.aceEditorrRef}
          ></div>
        </div>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement("svc-tab-json-editor-ace",
  (props: ITabJsonEditorAceComponentProps) => {
    return React.createElement(TabJsonEditorAceComponent, props);
  }
);
