// packages/survey-creator-vue/src/tabs/translation/Translation.vue
<template>
  <div class="svc-creator-tab__content svc-translation-tab">
    <div class="st-content">
      <div v-if="model.isEmpty" class="st-no-strings">
        <span>{{ model.noStringsText }}</span>
      </div>
      <div v-if="!model.isEmpty" class="svc-flex-column st-strings-wrapper">
        <div class="svc-flex-row st-strings-header">
          <SurveyComponent :model="model.stringsHeaderSurvey"></SurveyComponent>
        </div>
        <div class="svc-flex-row svc-plugin-tab__content st-strings">
          <SurveyComponent :model="model.stringsSurvey"></SurveyComponent>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import type { Translation } from "survey-creator-core";
import { useBase, SurveyComponent } from "survey-vue3-ui";
const props = defineProps<{ model: Translation }>();
useBase(() => props.model);
</script>

// packages/survey-creator-react/src/components/tabs/Translation.tsx
import React from "react";
import { Base } from "survey-core";
import {
  ReactElementFactory,
  SurveyElementBase,
  Survey
} from "survey-react-ui";
import { Translation } from "@survey/creator";

export class TabTranslationComponent extends SurveyElementBase<any, any> {
  private get model(): Translation {
    return this.props.data;
  }
  protected getStateElement(): Base {
    return this.model;
  }
  renderElement(): JSX.Element {
    if (!this.model) return null;
    return (
      <div className="svc-creator-tab__content svc-translation-tab">
        {this.renderElementContent()}
      </div>
    );
  }
  renderElementContent(): JSX.Element {
    if(this.model.isEmpty) {
      return (
        <div className="st-no-strings">
          <span>{this.model.noStringsText}</span>
        </div>
      );
    } else {
      return (
        <div className="st-content">
          <div className="svc-flex-column st-strings-wrapper">
            <div className="svc-flex-row st-strings-header">
              <Survey model={this.model.stringsHeaderSurvey}></Survey>
            </div>
            <div className="svc-flex-row svc-plugin-tab__content st-strings">
              <Survey model={this.model.stringsSurvey}></Survey>
            </div>
          </div>
          {/* <div className="svc-flex-column st-property-panel">
            <Survey model={this.model.settingsSurvey}></Survey>
          </div> */}
        </div>
      );
    }
  }
}

ReactElementFactory.Instance.registerElement("svc-tab-translation", (props) => {
  return React.createElement(TabTranslationComponent, props);
});
